ALTER TABLE `tournament_match_summaries` ADD COLUMN `winner_side` INTEGER NOT NULL DEFAULT 1;
--> statement-breakpoint
UPDATE `tournament_match_summaries` SET `evidence_status`='VERIFIED',`source_name`='User-confirmed video analysis summary' WHERE `id` IN ('dallas-2026-grand-final-mihawk-enel','dallas-2026-top16-sabo-rocks');
--> statement-breakpoint
UPDATE `tournament_match_summaries` SET `winner_side`=2 WHERE `id`='dallas-2026-top16-sabo-rocks';
--> statement-breakpoint
INSERT INTO `tournament_match_summaries` (`id`,`event_id`,`round`,`best_of`,`leader_one_code`,`archetype_one`,`player_one_name`,`leader_two_code`,`archetype_two`,`player_two_name`,`score_one`,`score_two`,`winner_leader_code`,`winner_side`,`summary`,`source_name`,`source_url`,`evidence_status`) VALUES
('dallas-2026-semi-enel-mirror','dallas-na-finals-2026','Semifinal',3,'OP15-058','Purple Enel · Frankie-focused, four 6-cost Enel','Yonas','OP15-058','Purple Enel · Gamma Knife / dog package','Shisho',2,1,'OP15-058',1,'Yonas wins the Purple Enel mirror 2–1. Game 1: Yonas goes first and chooses aggression rather than starving, using Satori and Pudding to pressure life while developing vassals. Both players trade with Mamaragan, Lightning Dragon, El Thor, and Law hand-rip. Yonas establishes Frankie plus vassals and repeatedly forces awkward 6k–7k attacks, draining Shisho’s Mamaragan, counters, and events. Gum-Gum Lightning and El Thor remove Senior Pink, Holly, and M; Frankie keeps Yonas’s hand moving. Yonas returns DON, removes Sanji with Gum-Gum Lightning, then puts the DON onto Frankie for an 11k attack at Shisho’s zero life to win. Game 2: Shisho goes first and attacks early with M, Mamaragan, and Law hand-rip, stripping Yonas’s Law and Mamaragan while repeated 7k leader and Pudding swings quickly put Yonas at one life. Shisho’s extra dogs, Gum-Gum Lightning, and Gamma Knife create tempo swings. Yonas stabilizes with Frankie, vassals, and Senior Pink, but Shisho chains Mamaragan, Kiten, and events to rest and shrink threats, then sets up Shura and leader pressure. Shisho finishes with a 7k Shura attack that Yonas cannot counter. Game 3: Yonas again goes first and pressures early with Pudding, Satori, and 6-cost Enel, using Enel as a 10k body and filter. Both players deploy 6-cost Enel, creating a standoff where attacking risks Gamma Knife. A Law hand-rip removes Shisho’s Law and Divine Departure; Satori and Frankie help Yonas find removal and counters. Shisho clears Yonas’s blocker Law with Gamma Knife and Gum-Gum Lightning and lands a 14k Enel attack, but Yonas holds enough counter. Extra 5-cost bodies, vassals, and Gum-Gum Lightning let Yonas control dogs and M. At one life each, Yonas builds a board, uses Satori to improve the next draw, then closes with an 11k attack Shisho cannot stop.','User-confirmed video analysis summary','https://www.youtube.com/watch?v=IoRlCxsn474','VERIFIED'),
('dallas-2026-top8-enel-sabo','dallas-na-finals-2026','Top 8',3,'OP15-058','Purple Enel','Yonas','OP13-004','Red/Black Sabo',NULL,2,0,'OP15-058',1,'Yonas’s Purple Enel beats Red/Black Sabo 2–0. Game 1: Sabo develops Usopp and the Elbaf engine, Pirates Docking Six, Loki, and Saul, but Enel controls the board with Pudding, Ohm, Shura, and Law hand-rip. Lightning Dragon cycles and freezes; Gum-Gum Lightning removes Pirates Docking Six; El Thor removes small bodies and buffs attacks. Double 6-cost Enel presents 10k threats without extra DON, forcing Sabo to spend counters. Enel closes with DON-minus events including Veri and El Thor to raise a leader attack above 10k, followed by a large 6-cost Enel attack Sabo cannot cover. Game 2: Sabo goes first and initially withholds attacks to deny Enel resources while setting up Usopp, Nami, and Pirates Docking Six. Yonas’s Law hand-rip discards Loki and Sanji, then Mamaragan, Gum-Gum Lightning, and El Thor remove Usopp and Pirates Docking Six while stripping counters. Enel uses the leader ability to turn small vassals into efficient 6k attacks. Sabo rebuilds, but Enel’s 6-cost Enel, Kiten, and Mamaragan sequence shrinks, rests, and attacks through the board. Frankie blocker stops Sabo assembling lethal; Enel closes from zero life with a leader attack and a roughly 16k 6-cost Enel attack that Sabo cannot defend. Enel advances to Top 4.','User-confirmed video analysis summary','https://www.youtube.com/watch?v=IoRlCxsn474','VERIFIED');
