ALTER TABLE `tournament_match_summaries` ADD COLUMN `series_complete` INTEGER NOT NULL DEFAULT 1;
--> statement-breakpoint
ALTER TABLE `tournament_match_summaries` ADD COLUMN `score_complete` INTEGER NOT NULL DEFAULT 1;
--> statement-breakpoint
UPDATE `tournament_events`
SET `event_date`='2026-09-19',
    `source_name`='SangSang Events / Limitless TCG',
    `source_url`='https://onepiece.limitlesstcg.com/tournaments/467'
WHERE `id`='sangsang-mexico-2026';
--> statement-breakpoint
INSERT INTO `tournament_match_summaries` (`id`,`event_id`,`round`,`best_of`,`leader_one_code`,`archetype_one`,`player_one_name`,`leader_two_code`,`archetype_two`,`player_two_name`,`score_one`,`score_two`,`winner_leader_code`,`winner_side`,`series_complete`,`score_complete`,`summary`,`source_name`,`source_url`,`evidence_status`) VALUES
('mexico-city-2026-featured-kaido-robin','sangsang-mexico-2026','Featured match · round unspecified',3,'OP17-058','Purple Kaido',NULL,'OP09-062','Purple/Yellow Nico Robin',NULL,0,2,'OP09-062',2,1,1,'Purple/Yellow Robin defeats Purple Kaido 2–0. Game 1: Kaido misses early ramp and six-cost King turns, leaving weak boards and mostly 5k attacks. Robin ramps with leader and Yamato, resolves repeated 10-cost Big Mom plays, and converts Oven, Pudding, and Teach into 8k attackers while healing. Kaido finds banish pressure with Queen, leader, and a late rush Kaido, but Robin’s Perospero, Oven, and Pudding triggers keep rebuilding the board. Kaido commits to large attacks, Robin defends, then closes with leader banish and stacked 8k–10k attacks. Game 2: Kaido again misses early Queen/Yamato ramp and passes with unused DON. Robin develops Pudding and Big Mom, then floods the board with 8k attackers. Kaido eventually plays 10-cost Big Mom and multiple Linlins, but Robin answers with Teach and Sweet 3 Generals and repeatedly chooses between burning Kaido’s life and healing. Kaido stabilizes briefly with blocker Kaido and King, but Robin’s life and wide board carry the final attacks.','User-provided video analysis summary · event details verified via Limitless','https://onepiece.limitlesstcg.com/tournaments/467','VERIFIED'),
('mexico-city-2026-swiss-robin-mirror-sto-julian','sangsang-mexico-2026','Final Swiss round · featured game',3,'OP09-062','Purple/Yellow Nico Robin · Sto','Sto','OP09-062','Purple/Yellow Nico Robin · Julian','Julian',1,0,'OP09-062',1,1,0,'Sto wins the reported final Swiss-round match against Julian and finishes the Swiss rounds undefeated. The recap covers one featured game, not the complete match score. Both players ramp with leader and Yamato; Julian reaches 10 DON and plays 10-cost Linlin first, healing and turning trigger bodies into 8k attackers. Sto answers with Teach and 10-cost Big Mom, then develops Pudding, Oven, and Perospero as 8k attackers. The mirror becomes a resource battle over Linlin activations, trigger bodies, and well-timed Gum-Gum Giant counters. Sto has more counters and one additional 10-cost Big Mom; Julian spends Giants and 2k counters to survive and eventually runs out. Sto closes with Big Mom and repeated 8k attacks.','User-provided video analysis summary · event details verified via Limitless','https://onepiece.limitlesstcg.com/tournaments/467','VERIFIED'),
('mexico-city-2026-top32-luffy-enel-partial','sangsang-mexico-2026','Top 32',3,'ST30-001','Red/Green Luffy & Ace',NULL,'OP15-058','Purple Enel',NULL,1,1,'',0,0,0,'Partial match record: the recap covers Games 1 and 2, which are tied 1–1; Game 3 and the match winner are not provided. Game 1: Luffy & Ace opens with Nami, misses the first search, then uses Sanji and OP12 Luffy to establish a board and pressure Enel. Enel answers with Shura, M, El Thor, Kiten, and Lightning Dragon to shrink and freeze threats, but Luffy re-establishes with more Sleep Luffys. At zero life, Luffy protects a counter-rich hand while Enel spends events and DON trying to clear the board and push lethal. Luffy & Ace survives and closes with leader and Luffy attacks. Game 2: Enel has a stronger Pudding/Shura start, then uses Vary, Gamma Knife, Lightning Dragon, and event pressure to control Sleep Luffy and test Luffy’s hand. A judge discussion over Sanji’s DON discount causes a temporary rewind; the supplied recap says the resulting game state is equivalent. Enel eventually removes a key body with Gamma Knife and closes with large Shura and Enel attacks while Luffy is low on life and counters. The excerpt ends with the match tied 1–1.','User-provided video analysis summary · event details verified via Limitless','https://onepiece.limitlesstcg.com/tournaments/467','VERIFIED'),
('mexico-city-2026-top16-rocks-mihawk-partial','sangsang-mexico-2026','Top 16',3,'OP17-039','Blue Rocks.D.Xebec',NULL,'OP14-020','Green Dracule Mihawk',NULL,1,1,'',0,0,0,'Partial match record: the recap covers Games 1 and 2, which are tied 1–1; Game 3 and the match winner are not provided. The Rocks leader is Blue (OP17-039). Game 1: Rocks develops Streusen, Wongji, and its leader, using cost manipulation and removal to disrupt Mihawk’s Kin’emon and Perona engine. Mihawk establishes Coffin Boat, Samurai, six-cost Mihawk, Oden, Law, and Yasopp, then tries to race with 10-cost Shanks. Rocks answers with Gloriosa, leader, and Shiki effects to shrink Shanks and refill its board. 10-cost Rocks, Shiki, Captain John, and Usopp event effects lock down blockers and clear threats; Mihawk runs out of defensive events and concedes. Game 2: Mihawk goes first, develops Kin’emon, Perona, and Samurai, then establishes Law, Oden, Coffin Boat, and 10-cost Shanks. Rocks misses Wongji and falls behind on board. Coffin Boat and Samurai refill Mihawk’s hand, and Mihawk chains Shanks and large attacks while removing Shiki and other threats. Rocks cannot defend the final attacks, tying the featured games 1–1.','User-provided video analysis summary · event details verified via Limitless','https://onepiece.limitlesstcg.com/tournaments/467','VERIFIED');
