'use client';

import {OrderReview} from '@/components/tcg/market-reputation';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {ArrowCounterClockwiseIcon as Refresh} from '@phosphor-icons/react';
import {MarketActivityEmpty,MarketActivityLoading,MarketCardStack,type MarketActivityCard} from '@/components/tcg/vault/tabs/market-activity-state';

type Order={id:string;kind:string;status:string;amount:number;subtotal:number;sellerNetAmount:number|null;currency:string;createdAt:string;expiresAt:string|null;role:'buyer'|'seller';listingTitle:string|null;shippingStatus:string|null;trackingId:string|null;waybillId:string|null;trackingUrl:string|null;trackingStatus:string|null;shippingFee:number;cards:MarketActivityCard[]};
const money=(amount:number,currency:string)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:currency||'IDR',maximumFractionDigits:0}).format(amount);
const dateLabel=(value:string,id:boolean)=>new Intl.DateTimeFormat(id?'id-ID':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(`${value.replace(' ','T')}Z`));
export function OrdersTab({language,initialOrderId}:{language:'EN'|'ID';initialOrderId?:string|null}){
  const id=language==='ID';
  const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [now,setNow]=useState(0);
  const [shipmentOrder,setShipmentOrder]=useState('');const [shipmentBusy,setShipmentBusy]=useState('');const [tracking,setTracking]=useState<Record<string,{status?:string;history?:Array<{status?:string;note?:string;updated_at?:string}>}>>({});
  const refresh=useCallback(async(silent=false)=>{if(!silent){setLoading(true);setError('')}try{const response=await fetch('/api/checkout/orders/mine',{cache:'no-store'});const data=await response.json() as {orders?:Order[];error?:string};if(!response.ok)throw new Error(data.error||(id?'Pesanan tidak dapat dimuat.':'Orders could not be loaded.'));setNow(Date.now());setOrders(data.orders??[])}catch(reason){if(!silent)setError(reason instanceof Error?reason.message:(id?'Pesanan tidak dapat dimuat.':'Orders could not be loaded.'))}finally{if(!silent)setLoading(false)}},[id]);
  // Initial loading is represented by the initial state; manual refreshes toggle it later.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>void refresh(true),10_000);return()=>window.clearInterval(timer)},[refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),60_000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{if(!loading&&initialOrderId)document.getElementById(`market-order-${initialOrderId}`)?.scrollIntoView({behavior:'smooth',block:'center'})},[initialOrderId,loading,orders]);
  const arrangeShipping=async(orderId:string)=>{setShipmentBusy(orderId);setError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/shipment`,{method:'POST'});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||(id?'Pengiriman tidak dapat dibuat.':'Shipment could not be created.'));setShipmentOrder('');await refresh()}catch(reason){setError(reason instanceof Error?reason.message:(id?'Pengiriman tidak dapat dibuat.':'Shipment could not be created.'))}finally{setShipmentBusy('')}};
  const loadTracking=async(orderId:string)=>{try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/tracking`,{cache:'no-store'});const data=await response.json() as {tracking?:{status?:string;history?:Array<{status?:string;note?:string;updated_at?:string}>};error?:string};if(!response.ok)throw new Error(data.error||'Tracking could not be loaded.');setTracking(current=>({...current,[orderId]:data.tracking??{}}))}catch(reason){setError(reason instanceof Error?reason.message:'Tracking could not be loaded.')}};
  if(loading)return <MarketActivityLoading kind="orders" label={id?'Memuat pesanan…':'Loading your orders…'}/>;
  return <section className="market-activity-panel" aria-label={id?'Pesanan Market':'Market orders'}>
    <div className="market-activity-toolbar"><p>{id?'Pembelian dan pesanan penjual. Checkout yang belum dibayar berakhir setelah 24 jam.':'Purchases and seller orders. Unpaid checkouts expire after 24 hours.'}</p><button type="button" className="market-activity-refresh" onClick={()=>void refresh()}><Refresh size={15}/>{id?'Muat ulang':'Refresh'}</button></div>
    {error&&<div className="market-activity-error" role="alert"><span>{error}</span><button type="button" onClick={()=>void refresh()}>{id?'Coba lagi':'Try again'}</button></div>}
    {!orders.length?<MarketActivityEmpty title={id?'Belum ada pesanan':'No orders yet'} description={id?'Pembelian dan pesanan penjual akan muncul di sini.':'Your purchases and seller orders will appear here.'}/>:<div className="market-activity-list">{orders.map(order=>{
      const expired=order.status==='PENDING_PAYMENT'&&order.expiresAt&&new Date(`${order.expiresAt.replace(' ','T')}Z`).getTime()<=now;
      const status=expired?'EXPIRED':order.status;
      const statusLabels:Record<string,string>=id?{PENDING_PAYMENT:'Menunggu pembayaran',PROCESSING:'Diproses',PAID:'Dibayar',SHIPPED:'Dikirim',RECEIVED:'Diterima',COMPLETED:'Selesai',CANCELLED:'Dibatalkan',EXPIRED:'Kedaluwarsa'}:{PENDING_PAYMENT:'Pending payment',PROCESSING:'Processing',PAID:'Paid',SHIPPED:'Shipped',RECEIVED:'Received',COMPLETED:'Completed',CANCELLED:'Cancelled',EXPIRED:'Expired'};
      return <article id={`market-order-${order.id}`} className={`market-activity-row market-order-row${initialOrderId===order.id?' is-targeted':''}`} key={order.id}>
      <MarketCardStack cards={order.cards??[]}/>
      <div className="market-activity-row-main"><div className="market-activity-row-title"><span className={`market-order-role is-${order.role}`}>{id?(order.role==='buyer'?'Pembelian':'Penjualan'):(order.role==='buyer'?'Purchase':'Sale')}</span><span className={`vault-listing-status is-${status.toLowerCase()}`}>{statusLabels[status]??status}</span></div><h3>{order.listingTitle||(order.kind==='PRO'?'Market Pro':id?'Pesanan Market':'Market order')}</h3><p>{dateLabel(order.createdAt,id)}</p>{status==='PENDING_PAYMENT'&&order.expiresAt&&<small>{id?'Bayar sebelum ':'Payment due '}{dateLabel(order.expiresAt,id)}</small>}<div className="market-order-breakdown"><span>{id?'Kartu':'Cards'} <b>{money(order.subtotal||0,order.currency)}</b></span>{order.shippingFee>0&&<span>{id?'Pengiriman':'Shipping'} <b>{money(order.shippingFee,order.currency)}</b></span>}{order.role==='seller'&&order.kind==='MARKET'&&order.sellerNetAmount!==null&&<><span>{id?'Biaya layanan':'Market fee'} <b>{money(Math.max(0,order.subtotal-order.sellerNetAmount),order.currency)}</b></span><span className="market-order-net">{id?'Anda terima':'You receive'} <b>{money(order.sellerNetAmount,order.currency)}</b></span></>}</div></div>
      <strong className="market-activity-price">{money(order.amount,order.currency)}</strong>
      {order.role==='buyer'&&<Link className="button secondary" href={`/checkout/order/${order.id}`}>{id?'Lihat pesanan':'View order'}</Link>}
      {order.role==='seller'&&order.status==='PAID'&&<div className="market-order-shipping-actions" style={{gridColumn:'1 / -1',display:'flex',flexWrap:'wrap',alignItems:'center',gap:10}}><button type="button" className="button" disabled={shipmentBusy===order.id} onClick={()=>shipmentOrder===order.id?void arrangeShipping(order.id):setShipmentOrder(order.id)}>{shipmentBusy===order.id?(id?'Menyiapkan…':'Preparing…'):shipmentOrder===order.id?(id?'Buat pengiriman':'Create shipment'):(id?'Atur pengiriman':'Arrange shipping')}</button></div>}
      {(order.status==='SHIPPED'||order.trackingId)&&<div className="market-order-shipping-actions" style={{gridColumn:'1 / -1',display:'flex',flexWrap:'wrap',alignItems:'center',gap:10}}>{order.waybillId&&<span>{id?'Resi':'Tracking'}: {order.waybillId}</span>}<button type="button" className="button secondary" onClick={()=>void loadTracking(order.id)}>{id?'Lacak':'Track'}</button>{order.role==='seller'&&<a href={`/api/checkout/order/${encodeURIComponent(order.id)}/label`} target="_blank" rel="noreferrer">{id?'Cetak label':'Print label'}</a>}{order.trackingUrl&&<a href={order.trackingUrl} target="_blank" rel="noreferrer">{id?'Buka kurir':'Courier tracking'}</a>}{order.trackingStatus&&<strong>{order.trackingStatus}</strong>}{tracking[order.id]?.status&&<strong>{tracking[order.id].status}</strong>}{tracking[order.id]?.history?.map((event,index)=><small key={`${event.updated_at}-${index}`}>{event.updated_at?dateLabel(event.updated_at,id):''} {event.status||event.note}</small>)}</div>}
      {order.kind==='MARKET'&&['RECEIVED','COMPLETED'].includes(order.status)&&<div style={{gridColumn:'1 / -1'}}><OrderReview orderId={order.id} role={order.role} language={language}/></div>}
    </article>})}</div>}
  </section>;
}
