'use client';

import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowCounterClockwiseIcon as Refresh,CaretDownIcon as CaretDown,CalendarBlankIcon as Calendar,PackageIcon as Package,TruckIcon as Truck,CheckCircleIcon as CheckCircle,ArrowSquareOutIcon as ExternalLink} from '@phosphor-icons/react';
import {OrderReview} from '@/components/tcg/market-reputation';
import {formatMoney} from '@/packages/domain';
import {MarketActivityEmpty,MarketActivityLoading,MarketCardStack,type MarketActivityCard} from '@/components/tcg/vault/tabs/market-activity-state';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';

type OrderItem={printingId:string;quantity:number;unitAmount?:number;condition?:string;card?:{name:string;code:string;language:string;variant:string;rarity:string;imageUrl:string|null}|null};
type ShippingInfo={recipientName?:string;addressLine?:string;city?:string;postalCode?:string;phone?:string;label?:string;courierName?:string;courierServiceName?:string;waybillId?:string|null;trackingUrl?:string|null}|null;
type OrderDetail={id:string;status:string;viewerRole:'buyer'|'seller';items:OrderItem[];shipping:ShippingInfo;subtotal:number;shippingFee:number;amount:number;currency:string;sellerNetAmount:number|null;marketFeePercent:number;marketSellerTier:'free'|'pro'|null;marketStandardFeePercent:number|null;marketBuyerFeePercent:number;marketBuyerFeeAmount:number;shippingDiscount:number;paymentFee:number|null;paymentMethod:string|null;paymentQrImage:string|null;paymentQrString:string|null;paymentExpiresAt:string|null;paymentExpired:boolean;expiresAt:string|null;canCancel:boolean;hasActivePayment:boolean};
type Order={id:string;kind:string;status:string;amount:number;subtotal:number;sellerNetAmount:number|null;currency:string;createdAt:string;expiresAt:string|null;role:'buyer'|'seller';listingTitle:string|null;printingId:string|null;shippingStatus:string|null;trackingId:string|null;waybillId:string|null;trackingUrl:string|null;trackingStatus:string|null;shippingFee:number;cards:MarketActivityCard[];marketFeePercent:number;marketSellerTier:'free'|'pro';marketStandardFeePercent:number|null;marketProSavings:number;marketBuyerFeePercent:number;marketBuyerFeeAmount:number;canCancel:boolean;hasActivePayment:boolean};
type Tracking={status?:string;history?:Array<{status?:string;note?:string;updated_at?:string}>};
const money=(amount:number,currency:string)=>formatMoney(amount,currency||'IDR');
const parseDate=(value:string)=>{const normalized=value.replace(' ','T');return new Date(/Z$|[+-]\d{2}:?\d{2}$/.test(normalized)?normalized:`${normalized}Z`)};
const dateLabel=(value:string,id:boolean)=>new Intl.DateTimeFormat(id?'id-ID':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(parseDate(value));
const safeDate=(value:string|null,id:boolean)=>value?dateLabel(value,id):'';
const qrisExpiryLabel=(value:string,id:boolean)=>`${new Intl.DateTimeFormat(id?'id-ID':'en-US',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value))} WIB`;

export function OrdersTab({language,initialOrderId}:{language:'EN'|'ID';initialOrderId?:string|null}){
  const id=language==='ID';
  const [orders,setOrders]=useState<Order[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [now,setNow]=useState(0);
  const [roleFilter,setRoleFilter]=useState<'all'|'buyer'|'seller'>('all');const [statusFilter,setStatusFilter]=useState('all');const [dateFrom,setDateFrom]=useState('');const [dateTo,setDateTo]=useState('');
  const [datesOpen,setDatesOpen]=useState(false);
  const [expanded,setExpanded]=useState('');const [details,setDetails]=useState<Record<string,OrderDetail>>({});const [detailBusy,setDetailBusy]=useState('');const [detailError,setDetailError]=useState('');const [paymentBusy,setPaymentBusy]=useState('');
  const [shipmentOrder,setShipmentOrder]=useState('');const [shipmentBusy,setShipmentBusy]=useState('');const [confirmBusy,setConfirmBusy]=useState('');const [cancelPrompt,setCancelPrompt]=useState('');const [cancelBusy,setCancelBusy]=useState('');const [tracking,setTracking]=useState<Record<string,Tracking>>({});
  const focusedOrder=useRef('');
  const refresh=useCallback(async(silent=false)=>{if(!silent){setLoading(true);setError('')}try{const response=await fetch('/api/checkout/orders/mine',{cache:'no-store'});const data=await response.json() as {orders?:Order[];error?:string};if(!response.ok)throw new Error(data.error||(id?'Pesanan tidak dapat dimuat.':'Orders could not be loaded.'));setNow(Date.now());setOrders(data.orders??[])}catch(reason){if(!silent)setError(reason instanceof Error?reason.message:(id?'Pesanan tidak dapat dimuat.':'Orders could not be loaded.'))}finally{if(!silent)setLoading(false)}},[id]);
  // Initial loading is represented by the initial state; manual refreshes toggle it later.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void refresh(true)},30_000);return()=>window.clearInterval(timer)},[refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),60_000);return()=>window.clearInterval(timer)},[]);
  const loadDetails=async(orderId:string)=>{setDetailBusy(orderId);setDetailError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}`,{cache:'no-store'});const data=await response.json() as OrderDetail&{error?:string};if(!response.ok)throw new Error(data.error||(id?'Detail pesanan tidak dapat dimuat.':'Order details could not be loaded.'));setDetails(current=>({...current,[orderId]:data}))}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Detail pesanan tidak dapat dimuat.':'Order details could not be loaded.'))}finally{setDetailBusy('')}};
  const createQris=async(orderId:string)=>{setPaymentBusy(orderId);setDetailError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/instrument`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const data=await response.json() as {paymentMethod?:string;qrImage?:string;qrString?:string|null;paymentFee?:number|null;expiresAt?:string|null;error?:string};if(!response.ok||data.paymentMethod!=='qris'||!data.qrImage)throw new Error(data.error||(id?'Kode QRIS tidak dapat dimuat.':'The QRIS code could not be loaded.'));setDetails(current=>({...current,[orderId]:{...current[orderId],paymentMethod:'qris',paymentQrImage:data.qrImage!,paymentQrString:data.qrString??null,paymentFee:data.paymentFee??null,paymentExpiresAt:data.expiresAt??null,canCancel:false,hasActivePayment:true}}));setOrders(current=>current.map(order=>order.id===orderId?{...order,canCancel:false,hasActivePayment:true}:order))}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Kode QRIS tidak dapat dimuat.':'The QRIS code could not be loaded.'))}finally{setPaymentBusy('')}};
  const toggleDetails=(orderId:string)=>{if(expanded===orderId){setExpanded('');setDetailError('');return}setExpanded(orderId);if(!details[orderId])void loadDetails(orderId)};
  useEffect(()=>{if(!loading&&initialOrderId&&focusedOrder.current!==initialOrderId){focusedOrder.current=initialOrderId;document.getElementById(`market-order-${initialOrderId}`)?.scrollIntoView({behavior:'smooth',block:'center'});setExpanded(initialOrderId);if(!details[initialOrderId])void loadDetails(initialOrderId)}},[initialOrderId,loading]);
  const arrangeShipping=async(orderId:string)=>{setShipmentBusy(orderId);setDetailError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/shipment`,{method:'POST'});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||(id?'Pengiriman tidak dapat dibuat.':'Shipment could not be created.'));setShipmentOrder('');await refresh(true);await loadDetails(orderId)}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Pengiriman tidak dapat dibuat.':'Shipment could not be created.'))}finally{setShipmentBusy('')}};
  const loadTracking=async(orderId:string)=>{try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/tracking`,{cache:'no-store'});const data=await response.json() as {tracking?:Tracking;error?:string};if(!response.ok)throw new Error(data.error||(id?'Status pengiriman tidak dapat dimuat.':'Tracking could not be loaded.'));setTracking(current=>({...current,[orderId]:data.tracking??{}}))}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Status pengiriman tidak dapat dimuat.':'Tracking could not be loaded.'))}};
  const confirmReceived=async(orderId:string)=>{setConfirmBusy(orderId);setDetailError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}`,{method:'POST'});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||(id?'Penerimaan pesanan tidak dapat disimpan.':'Delivery confirmation could not be saved.'));await refresh(true);await loadDetails(orderId)}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Penerimaan pesanan tidak dapat disimpan.':'Delivery confirmation could not be saved.'))}finally{setConfirmBusy('')}};
  const cancelOrder=async(orderId:string)=>{setCancelBusy(orderId);setDetailError('');try{const response=await fetch(`/api/checkout/order/${encodeURIComponent(orderId)}/cancel`,{method:'POST'});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||(id?'Pesanan tidak dapat dibatalkan.':'This order could not be cancelled.'));setCancelPrompt('');await refresh(true);await loadDetails(orderId)}catch(reason){setDetailError(reason instanceof Error?reason.message:(id?'Pesanan tidak dapat dibatalkan.':'This order could not be cancelled.'))}finally{setCancelBusy('')}};
  const statusLabels:Record<string,string>=id?{PENDING_PAYMENT:'Menunggu pembayaran',PROCESSING:'Diproses',PAID:'Dibayar',SHIPPED:'Dikirim',RECEIVED:'Diterima',COMPLETED:'Selesai',CANCELLED:'Dibatalkan',EXPIRED:'Kedaluwarsa',PAYMENT_REVIEW:'Perlu pemeriksaan pembayaran'}:{PENDING_PAYMENT:'Pending payment',PROCESSING:'Processing',PAID:'Paid',SHIPPED:'Shipped',RECEIVED:'Received',COMPLETED:'Completed',CANCELLED:'Cancelled',EXPIRED:'Expired',PAYMENT_REVIEW:'Payment review'};
  const filteredOrders=useMemo(()=>orders.filter(order=>{
    if(roleFilter!=='all'&&order.role!==roleFilter)return false;
    const expired=order.status==='PENDING_PAYMENT'&&order.expiresAt&&new Date(`${order.expiresAt.replace(' ','T')}Z`).getTime()<=now;
    const visibleStatus=expired?'EXPIRED':order.status;
    if(statusFilter!=='all'&&visibleStatus!==statusFilter)return false;
    const created=parseDate(order.createdAt).getTime();
    if(dateFrom&&created<new Date(`${dateFrom}T00:00:00`).getTime())return false;
    if(dateTo&&created>=new Date(`${dateTo}T00:00:00`).getTime()+24*60*60*1000)return false;
    return true;
  }),[orders,roleFilter,statusFilter,dateFrom,dateTo,now]);
  const hasFilters=roleFilter!=='all'||statusFilter!=='all'||Boolean(dateFrom)||Boolean(dateTo);
  const clearFilters=()=>{setRoleFilter('all');setStatusFilter('all');setDateFrom('');setDateTo('')};
  if(loading)return <MarketActivityLoading kind="orders" label={id?'Memuat pesanan…':'Loading your orders…'}/>;
  return <section className="market-activity-panel" aria-label={id?'Pesanan Market':'Market orders'}>
    {!!orders.length?<div className="market-order-controls" aria-label={id?'Filter pesanan':'Order filters'}>
      <div className="market-order-filter-pickers">
        <Select value={roleFilter} onValueChange={value=>setRoleFilter(value as 'all'|'buyer'|'seller')}><SelectTrigger className="market-order-filter-select" aria-label={id?'Jenis aktivitas':'Activity type'}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{id?'Pembelian & penjualan':'Purchases & sales'}</SelectItem><SelectItem value="buyer">{id?'Pembelian':'Purchases'}</SelectItem><SelectItem value="seller">{id?'Penjualan':'Sales'}</SelectItem></SelectContent></Select>
        <Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger className="market-order-filter-select market-order-status-select" aria-label={id?'Status pesanan':'Order status'}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{id?'Semua status':'All statuses'}</SelectItem>{Object.entries(statusLabels).map(([value,label])=><SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select>
        <Popover open={datesOpen} onOpenChange={setDatesOpen}><PopoverTrigger asChild><button type="button" className={`market-order-date-trigger${dateFrom||dateTo?' is-active':''}`} aria-label={id?'Filter berdasarkan tanggal':'Filter by date'}><Calendar size={15}/><span>{id?'Tanggal':'Dates'}</span>{(dateFrom||dateTo)&&<i/>}</button></PopoverTrigger><PopoverContent align="start" className="market-order-date-popover"><label><span>{id?'Dari tanggal':'From date'}</span><input type="date" value={dateFrom} max={dateTo||undefined} onChange={event=>setDateFrom(event.target.value)}/></label><label><span>{id?'Sampai tanggal':'Through date'}</span><input type="date" value={dateTo} min={dateFrom||undefined} onChange={event=>setDateTo(event.target.value)}/></label>{(dateFrom||dateTo)&&<button type="button" onClick={()=>{setDateFrom('');setDateTo('')}}>{id?'Hapus tanggal':'Clear dates'}</button>}</PopoverContent></Popover>
      </div>
      <div className="market-order-control-meta"><small>{id?`${filteredOrders.length} dari ${orders.length}`:`${filteredOrders.length} of ${orders.length}`}</small>{hasFilters&&<button type="button" className="market-order-filter-clear" onClick={clearFilters}>{id?'Hapus':'Clear'}</button>}<button type="button" className="market-activity-refresh market-order-refresh" aria-label={id?'Muat ulang pesanan':'Refresh orders'} title={id?'Muat ulang':'Refresh'} onClick={()=>void refresh()}><Refresh size={15}/></button></div>
    </div>:<div className="market-activity-toolbar"><p>{id?'Pembelian dan penjualan Anda. Checkout yang belum dibayar berakhir setelah 24 jam.':'Your purchases and sales. Unpaid checkouts expire after 24 hours.'}</p><button type="button" className="market-activity-refresh market-activity-icon-action" aria-label={id?'Muat ulang pesanan':'Refresh orders'} title={id?'Muat ulang':'Refresh'} onClick={()=>void refresh()}><Refresh size={15}/></button></div>}
    {error&&<div className="market-activity-error" role="alert"><span>{error}</span><button type="button" onClick={()=>void refresh()}>{id?'Coba lagi':'Try again'}</button></div>}
    {!orders.length?<MarketActivityEmpty title={id?'Belum ada pesanan':'No orders yet'} description={id?'Pembelian dan penjualan akan muncul di sini.':'Your purchases and sales will appear here.'}/>:!filteredOrders.length?<MarketActivityEmpty title={id?'Tidak ada pesanan yang cocok':'No matching orders'} description={id?'Ubah filter atau rentang tanggal untuk melihat pesanan lain.':'Change the filters or date range to see other orders.'} action={hasFilters?<button type="button" className="market-activity-empty-action" onClick={clearFilters}>{id?'Hapus filter':'Clear filters'}</button>:undefined}/>:<div className="market-activity-list">{filteredOrders.map(order=>{
      const expired=order.status==='PENDING_PAYMENT'&&order.expiresAt&&new Date(`${order.expiresAt.replace(' ','T')}Z`).getTime()<=now;
      const status=expired?'EXPIRED':order.status;const isExpanded=expanded===order.id;const detail=details[order.id];const activeQr=Boolean(detail?.paymentQrImage&&detail.paymentExpiresAt&&parseDate(detail.paymentExpiresAt).getTime()>now);const feeAmount=Math.max(0,order.subtotal-(order.sellerNetAmount??order.subtotal));
      return <article id={`market-order-${order.id}`} className={`market-activity-row market-order-row${initialOrderId===order.id?' is-targeted':''}${isExpanded?' is-expanded':''}`} key={order.id}>
        <div className="market-order-summary" role="button" tabIndex={0} aria-expanded={isExpanded} onClick={()=>toggleDetails(order.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggleDetails(order.id)}}}>
          <MarketCardStack cards={order.cards??[]}/>
          <div className="market-activity-row-main"><div className="market-activity-row-title"><span className={`market-activity-badge market-order-role is-${order.role}`}>{id?(order.role==='buyer'?'Pembelian':'Penjualan'):(order.role==='buyer'?'Purchase':'Sale')}</span><span className={`vault-listing-status is-${status.toLowerCase().replaceAll('_','-')}`}>{statusLabels[status]??status}</span></div><h3>{order.listingTitle||(order.kind==='PRO'?'Market Pro':id?'Pesanan Market':'Market order')}</h3><p>{dateLabel(order.createdAt,id)}</p>{status==='PENDING_PAYMENT'&&order.expiresAt&&<small>{id?'Bayar sebelum ':'Payment due '}{dateLabel(order.expiresAt,id)}</small>}</div>
          <div className="market-order-total"><small>{id?(order.role==='buyer'?'Total pesanan':'Dibayar pembeli'):(order.role==='buyer'?'Order total':'Buyer paid')}</small><strong>{money(order.amount,order.currency)}</strong><span className="market-order-expand-label">{isExpanded?(id?'Tutup':'Close'):(id?'Detail':'Details')}<CaretDown size={15}/></span></div>
        </div>
        {isExpanded&&<div className="market-order-details">
          {detailBusy===order.id&&!detail&&<p className="market-order-detail-loading">{id?'Memuat detail pesanan…':'Loading order details…'}</p>}
          {detailError&&<div className="market-activity-error" role="alert"><span>{detailError}</span><button type="button" onClick={()=>void loadDetails(order.id)}>{id?'Coba lagi':'Try again'}</button></div>}
          {detail&&<>
            <div className="market-order-detail-items"><h4>{id?'Kartu':'Cards'}</h4>{detail.items.map((item,index)=><div className="market-order-detail-item" key={`${item.printingId}-${index}`}>
              {item.card?.imageUrl?<img src={item.card.imageUrl} alt=""/>:<span className="market-order-detail-placeholder"/>}
              <div><strong>{item.card?.name??item.printingId}</strong><small>{item.card?.code??item.printingId}{item.card?.rarity?` · ${item.card.rarity}`:''}{item.card?.language?` · ${item.card.language}`:''}{item.condition?` · ${item.condition}`:''} × {item.quantity}</small></div>
              <b>{money((item.unitAmount??0)*item.quantity,detail.currency)}</b>
            </div>)}</div>
            <div className="market-order-ledger"><h4>{id?'Rincian pembayaran':'Payment breakdown'}</h4>
              <div><span>{id?'Subtotal kartu':'Cards subtotal'}</span><b>{money(detail.subtotal,detail.currency)}</b></div>
              {detail.shippingFee>0&&<div><span>{id?'Pengiriman':'Delivery'}</span><b>{money(detail.shippingFee,detail.currency)}</b></div>}{order.role==='buyer'&&detail.shippingDiscount>0&&<div className="market-order-discount"><span>{id?'Voucher pengiriman Market Pro':'Market Pro shipping voucher'}</span><b>−{money(detail.shippingDiscount,detail.currency)}</b></div>}
              {order.role==='seller'&&order.kind==='MARKET'&&<>
                <div><span>{id?`Biaya layanan penjual (${order.marketFeePercent}%)`:`Seller fee (${order.marketFeePercent}%)`}</span><b>{money(feeAmount,detail.currency)}</b></div>
                {order.marketSellerTier==='pro'&&order.marketProSavings>0&&<p className="checkout-fee-note">{id?`Pro menghemat ${money(order.marketProSavings,detail.currency)} dari biaya layanan penjual. Tarif standar ${order.marketStandardFeePercent}%.`:`Pro saved you ${money(order.marketProSavings,detail.currency)} on the seller fee. Standard rate: ${order.marketStandardFeePercent}%.`}</p>}
                <div className="market-order-ledger-total"><span>{id?'Anda terima':'You receive'}</span><b>{money(detail.sellerNetAmount??detail.subtotal,detail.currency)}</b></div>
              </>}
              {order.role==='buyer'&&<>{detail.marketBuyerFeePercent>0&&<div><span>{id?`Biaya layanan Market (${detail.marketBuyerFeePercent}%)`:`Market service fee (${detail.marketBuyerFeePercent}%)`}</span><b>{money(detail.marketBuyerFeeAmount,detail.currency)}</b></div>}<div className="market-order-ledger-total"><span>{id?(status==='PENDING_PAYMENT'?'Total pesanan':'Total dibayar'):(status==='PENDING_PAYMENT'?'Order total':'Total paid')}</span><b>{money(detail.amount,detail.currency)}</b></div></>}
            </div>
            {order.role==='buyer'&&status==='PENDING_PAYMENT'&&<section className="market-order-qris" aria-label={id?'Pembayaran QRIS':'QRIS payment'}>
              {activeQr&&detail?.paymentQrImage&&detail.paymentExpiresAt?<><div className="market-order-qris-code"><img src={`${detail.paymentQrImage}${detail.paymentQrImage.includes('?')?'&':'?'}refresh=${Math.floor(now/(5*60*1000))}`} alt={id?'Kode pembayaran QRIS':'QRIS payment code'}/></div><div className="market-order-qris-copy"><strong>{id?'Pindai untuk membayar':'Scan to pay'}</strong><span>{id?'Bayar sebelum':'Pay by'} {qrisExpiryLabel(detail.paymentExpiresAt,id)}</span></div></>:detail?.paymentExpired||detail?.paymentMethod==='qris'?<div className="market-order-qris-prompt"><span>{id?'Batas waktu pembayaran berakhir. Memeriksa status…':'Payment deadline passed. Checking status…'}</span></div>:<div className="market-order-qris-prompt"><span>{id?'Bayar pesanan ini dengan QRIS':'Pay this order with QRIS'}</span><button type="button" className="button" disabled={paymentBusy===order.id} onClick={()=>void createQris(order.id)}>{paymentBusy===order.id?(id?'Memuat QRIS…':'Loading QRIS…'):(id?'Tampilkan QRIS':'Show QRIS')}</button></div>}
            </section>}
            {detail.shipping&&<details className="market-order-shipping-detail"><summary><span>{id?'Pengiriman':'Delivery'}</span><strong>{detail.shipping.courierName}{detail.shipping.courierServiceName?` · ${detail.shipping.courierServiceName}`:''}</strong>{(detail.shipping.waybillId||detail.shipping.trackingUrl)&&<span className="market-order-shipping-summary-tracking">{detail.shipping.waybillId&&<b>{detail.shipping.waybillId}</b>}{detail.shipping.trackingUrl&&<a href={detail.shipping.trackingUrl} target="_blank" rel="noreferrer">{id?'Lacak':'Track'}<ExternalLink size={13}/></a>}</span>}</summary>{detail.shipping.addressLine&&<p>{detail.shipping.recipientName}<br/>{detail.shipping.addressLine}<br/>{detail.shipping.city} {detail.shipping.postalCode}{detail.shipping.phone?` · ${detail.shipping.phone}`:''}</p>}{detail.shipping.waybillId&&<p>{id?'Nomor resi':'Tracking number'}: {detail.shipping.waybillId}</p>}</details>}
            <div className="market-order-detail-actions">
              {order.role==='seller'&&status==='PENDING_PAYMENT'&&<span>{id?'Menunggu pembayaran pembeli':'Waiting for buyer payment'}</span>}
              {status==='PENDING_PAYMENT'&&detail.canCancel&&<button type="button" className="button secondary market-order-cancel" disabled={cancelBusy===order.id} onClick={()=>setCancelPrompt(current=>current===order.id?'':order.id)}>{id?'Batalkan pesanan':'Cancel order'}</button>}
              {order.role==='seller'&&status==='PAID'&&<button type="button" className="button" disabled={shipmentBusy===order.id} onClick={()=>shipmentOrder===order.id?void arrangeShipping(order.id):setShipmentOrder(order.id)}><Package size={15}/>{shipmentBusy===order.id?(id?'Menyiapkan…':'Preparing…'):shipmentOrder===order.id?(id?'Buat pengiriman':'Create shipment'):(id?'Atur pengiriman':'Arrange shipping')}</button>}
              {(status==='SHIPPED'||order.trackingId)&&<button type="button" className="button secondary" onClick={()=>void loadTracking(order.id)}><Truck size={15}/>{id?'Perbarui pelacakan':'Refresh tracking'}</button>}
              {order.role==='buyer'&&status==='SHIPPED'&&<button type="button" className="button" disabled={confirmBusy===order.id} onClick={()=>void confirmReceived(order.id)}><CheckCircle size={15}/>{confirmBusy===order.id?(id?'Menyimpan…':'Saving…'):(id?'Konfirmasi diterima':'Confirm delivery')}</button>}
              {order.role==='seller'&&(status==='SHIPPED'||order.trackingId)&&<a href={`/api/checkout/order/${encodeURIComponent(order.id)}/label`} target="_blank" rel="noreferrer">{id?'Cetak label':'Print label'}<ExternalLink size={14}/></a>}
            </div>
            {cancelPrompt===order.id&&status==='PENDING_PAYMENT'&&<div className="market-order-cancel-confirm" role="group" aria-label={id?'Konfirmasi pembatalan':'Confirm cancellation'}><span>{id?'Batalkan pesanan yang belum dibayar ini? Kartu akan kembali tersedia.':'Cancel this unpaid order? The cards will become available again.'}</span><button type="button" className="button market-order-cancel-confirm-action" disabled={cancelBusy===order.id} onClick={()=>void cancelOrder(order.id)}>{cancelBusy===order.id?(id?'Membatalkan…':'Cancelling…'):(id?'Ya, batalkan':'Confirm cancellation')}</button><button type="button" className="button secondary" onClick={()=>setCancelPrompt('')}>{id?'Tetap lanjut':'Keep order'}</button></div>}
            {tracking[order.id]&&<div className="market-order-tracking-history">{tracking[order.id].status&&<strong>{tracking[order.id].status}</strong>}{tracking[order.id].history?.map((event,index)=><small key={`${event.updated_at}-${index}`}>{safeDate(event.updated_at??null,id)} {event.status||event.note}</small>)}</div>}
            {order.kind==='MARKET'&&['RECEIVED','COMPLETED'].includes(status)&&<OrderReview orderId={order.id} role={order.role} language={language}/>}
          </>}
        </div>}
      </article>})}</div>}
  </section>;
}
