'use client';
import {PushNotificationPrompt} from '@/components/tcg/push-notification-settings';
import {useState} from 'react';
import Link from 'next/link';
import {HeartIcon as Heart,PlusIcon as Plus} from '@phosphor-icons/react';
import {toast} from 'sonner';
import {api,type WishlistItem} from '@/lib/client';
import {cardFor} from '@/packages/card-data/catalog';
import type {MarketCardThumbnail} from '@/lib/server/market-card-thumbnails';
interface Props{wishlist:(WishlistItem&{card?:MarketCardThumbnail|null})[];language:'EN'|'ID';onFindListings:(code:string)=>void;onAddToVault:(id:string)=>void;onRemoveFromWishlist:(id:string)=>void;onAddNewWishlistItem:()=>void;onUpdated:()=>Promise<void>}
export function WishlistTab({wishlist,language,onRemoveFromWishlist,onAddNewWishlistItem,onUpdated}:Props){
 const id=language==='ID';const [busy,setBusy]=useState('');
 const save=async(e:React.FormEvent<HTMLFormElement>,printingId:string)=>{e.preventDefault();const form=new FormData(e.currentTarget);const raw=String(form.get('targetPrice')||'');const targetPrice=raw?Number(raw):null;setBusy(printingId);try{await api('/api/wishlist',{printingId,targetPrice,targetCondition:String(form.get('condition'))||null,alerts:form.get('alerts')==='on'});await onUpdated();toast.success(id?'Preferensi disimpan':'Preferences saved')}catch{toast.error(id?'Preferensi gagal disimpan':'Could not save preferences')}finally{setBusy('')}};
 return <section><PushNotificationPrompt language={language} message="wishlist"/><header className="wishlist-header"><h2>{id?'Daftar keinginan':'Card wishlist'}</h2><button className="button secondary" onClick={onAddNewWishlistItem}><Plus size={16}/>{id?'Tambah kartu':'Add card'}</button></header>{!wishlist.length&&<div className="vault-empty-state"><Heart size={30}/><p>{id?'Simpan kartu, bahasa, dan cetakan yang ingin Anda beli':'Save the cards, languages and printings you want to buy'}</p></div>}<div className="vault-wishlist-grid">{wishlist.map(w=>{const fallback=cardFor(w.printingId);const card=w.card??fallback;return <article className="wishlist-entry" key={w.printingId}>{card?.imageUrl&&<img src={card.imageUrl} alt={card.name} loading="lazy"/>}<div><h3>{card?.name??(id?'Kartu tidak tersedia':'Card unavailable')}</h3><small>{[card?.code,card?.language,card?.variant,card?.rarity].filter(Boolean).join(' - ')}</small><form onSubmit={e=>void save(e,w.printingId)}><label>{id?'Target harga per kartu (IDR)':'Target price per card (IDR)'}<input name="targetPrice" type="number" min={1} max={100000000000} step={1} defaultValue={w.targetPrice??''}/></label><fieldset><legend>{id?'Kondisi':'Condition'}</legend><div className="wishlist-condition-options">{['','NM','LP','MP','HP','DMG'].map(c=><label key={c}><input type="radio" name="condition" value={c} defaultChecked={(w.targetCondition||'')===c}/>{c||(id?'Semua':'Any')}</label>)}</div></fieldset><label className="wishlist-alert-toggle"><input type="checkbox" name="alerts" role="switch" defaultChecked={Boolean(w.alerts)}/>{id?'Notifikasi listing yang cocok':'Matching-listing alerts'}</label><button className="button secondary" disabled={busy===w.printingId}>{id?'Simpan preferensi':'Save preferences'}</button></form><div className="market-watch-actions"><Link className="button" href={`/market?printing=${w.printingId}`}>{id?'Cari di Market':'Find in Market'}</Link><button className="button secondary" disabled={busy===w.printingId} onClick={()=>onRemoveFromWishlist(w.printingId)}>{id?'Hapus':'Remove'}</button></div></div></article>})}</div></section>;
}
