'use client';
import {PushNotificationPrompt} from '@/components/tcg/push-notification-settings';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {HeartIcon as Heart,PlusIcon as Plus,MagnifyingGlassIcon as Search,CheckIcon as Check} from '@phosphor-icons/react';
import {toast} from 'sonner';
import {api,type WishlistItem} from '@/lib/client';
import type {MarketCardThumbnail} from '@/lib/server/market-card-thumbnails';

type Printing={id:string;language:string;variant:string;rarity:string|null;set_code:string|null;set_name:string|null;printing_code:string|null;card_image_url:string|null;tcg_card_assets?:Array<{kind:string;object_key:string}>};
type Card={id:string;code:string;name:string;color?:string;card_type?:string;printings:Printing[]};
type SearchCard={id:string;code:string;name:string;color?:string;card_type?:string;imageUrl?:string};
interface Props{wishlist:(WishlistItem&{card?:MarketCardThumbnail|null})[];language:'EN'|'ID';onRemoveFromWishlist:(id:string)=>void;onUpdated:()=>Promise<void>}
const publicImage=(printing:Printing)=>{const asset=printing.tcg_card_assets?.find(item=>item.kind==='small')?.object_key;const source=asset||printing.card_image_url;if(!source)return null;if(source.startsWith('http')||source.startsWith('/'))return source;return `/${source.replace(/^one-piece\/([^/]+)\//,(_,set:string)=>`${set.replaceAll('-','')}/`)}`};
export function WishlistTab({wishlist,language,onRemoveFromWishlist,onUpdated}:Props){
 const id=language==='ID';const [busy,setBusy]=useState('');const [adding,setAdding]=useState(false);const [query,setQuery]=useState('');const [results,setResults]=useState<SearchCard[]>([]);const [searching,setSearching]=useState(false);const [selected,setSelected]=useState<Card|null>(null);const [printingId,setPrintingId]=useState('');
 const t=(en:string,indo:string)=>id?indo:en;
 useEffect(()=>{if(!adding||query.trim().length<2)return;let active=true;const timer=window.setTimeout(()=>{setSearching(true);api<{cards:SearchCard[]}>(`/api/cards/identities?q=${encodeURIComponent(query.trim())}`).then(data=>{if(active)setResults(data.cards)}).catch(()=>{if(active)setResults([])}).finally(()=>{if(active)setSearching(false)})},180);return()=>{active=false;window.clearTimeout(timer)}},[adding,query]);
 const save=async(e:FormEvent<HTMLFormElement>,target:string)=>{e.preventDefault();const form=new FormData(e.currentTarget);const raw=String(form.get('targetPrice')||'');const targetPrice=raw?Number(raw):null;setBusy(target);try{await api('/api/wishlist',{printingId:target,targetPrice,targetCondition:String(form.get('condition'))||null,alerts:form.get('alerts')==='on'});await onUpdated();toast.success(t('Preferences saved','Preferensi disimpan'))}catch(error){toast.error(error instanceof Error?error.message:t('Could not save preferences','Preferensi gagal disimpan'))}finally{setBusy('')}};
 const chooseCard=async(row:SearchCard)=>{setSearching(true);try{const data=await api<{identity:Omit<Card,'printings'>;printings:Printing[]}>(`/api/cards/${encodeURIComponent(row.code)}`);const card={...data.identity,printings:data.printings};setSelected(card);const preferred=card.printings.find(item=>item.language==='EN')??card.printings[0];setPrintingId(preferred?.id??'');setResults([])}catch(error){toast.error(error instanceof Error?error.message:t('Card details could not load','Detail kartu gagal dimuat'))}finally{setSearching(false)}};
 const addPrinting=async()=>{if(!printingId)return;setBusy('new');try{await api('/api/wishlist',{printingId,saved:true});await onUpdated();setSelected(null);setQuery('');setAdding(false);toast.success(t('Added to wishlist','Ditambahkan ke daftar keinginan'))}catch(error){toast.error(error instanceof Error?error.message:t('Could not add card','Kartu gagal ditambahkan'))}finally{setBusy('')}};
 return <section><PushNotificationPrompt language={language} message="wishlist"/><header className="wishlist-header"><h2>{t('Card wishlist','Daftar keinginan')}</h2><button type="button" className="button secondary" onClick={()=>{setAdding(value=>!value);setSelected(null);setQuery('');setResults([]);setSearching(false)}}><Plus size={16}/>{adding?t('Done','Selesai'):t('Add card','Tambah kartu')}</button></header>
 {adding&&<div className="wishlist-add-panel"><label className="wishlist-add-search"><Search size={17}/><input autoFocus value={query} onChange={event=>{const value=event.target.value;setQuery(value);setSelected(null);if(value.trim().length<2){setResults([]);setSearching(false)}}} placeholder={t('Search card name or code','Cari nama atau kode kartu')} aria-label={t('Search cards','Cari kartu')}/></label>{searching&&<p role="status">{t('Searching…','Mencari…')}</p>}{results.length>0&&<div className="wishlist-search-results">{results.map(card=><button type="button" key={card.id} onClick={()=>void chooseCard(card)}><span>{card.imageUrl&&<img src={card.imageUrl} alt=""/>}</span><b>{card.name}</b><small>{card.code}</small></button>)}</div>}{selected&&<div className="wishlist-printing-picker"><div className="wishlist-selected-card"><strong>{selected.name}</strong><small>{selected.code}</small></div><div className="wishlist-printing-options">{selected.printings.map(printing=><button type="button" key={printing.id} className={printingId===printing.id?'is-selected':''} aria-pressed={printingId===printing.id} onClick={()=>setPrintingId(printing.id)}>{publicImage(printing)&&<img src={publicImage(printing)!} alt=""/>}<span><b>{printing.language==='JP'?'日本語':printing.language==='EN'?'English':printing.language}</b><small>{[printing.variant,printing.rarity,printing.set_code,printing.printing_code].filter(Boolean).join(' · ')}</small></span>{printingId===printing.id&&<Check size={17}/>}</button>)}</div><button type="button" className="button" disabled={!printingId||busy==='new'} onClick={()=>void addPrinting()}>{busy==='new'?t('Adding…','Menambahkan…'):t('Add exact printing','Tambah cetakan ini')}</button></div>}{!searching&&query.trim().length>=2&&!results.length&&!selected&&<p>{t('No matching cards found','Kartu yang cocok tidak ditemukan')}</p>}</div>}
 {!wishlist.length&&!adding&&<div className="vault-empty-state"><Heart size={30}/><p>{t('Save the cards and printings you want to find on Market','Simpan kartu dan cetakan yang ingin Anda cari di Market')}</p></div>}
 <div className="vault-wishlist-grid">{wishlist.map(w=>{const card=w.card;return <article className="wishlist-entry" key={w.printingId}>{card?.imageUrl&&<img src={card.imageUrl} alt={card.name} loading="lazy"/>}<div><h3>{card?.name??t('Card unavailable','Kartu tidak tersedia')}</h3><small>{[card?.code,card?.language,card?.variant,card?.rarity].filter(Boolean).join(' · ')}</small><form onSubmit={e=>void save(e,w.printingId)}><label>{t('Target price per card (IDR)','Target harga per kartu (IDR)')}<input name="targetPrice" type="number" min={1} max={100000000000} step={1} defaultValue={w.targetPrice??''}/></label><fieldset><legend>{t('Condition','Kondisi')}</legend><div className="wishlist-condition-options">{['','NM','LP','MP','HP','DMG'].map(c=><label key={c}><input type="radio" name="condition" value={c} defaultChecked={(w.targetCondition||'')===c}/>{c||(id?'Semua':'Any')}</label>)}</div></fieldset><label className="wishlist-alert-toggle"><input type="checkbox" name="alerts" role="switch" defaultChecked={Boolean(w.alerts)}/>{t('Matching-listing alerts','Notifikasi listing yang cocok')}</label><button className="button secondary" disabled={busy===w.printingId}>{t('Save preferences','Simpan preferensi')}</button></form><div className="market-watch-actions"><Link className="button" href={`/market?printing=${w.printingId}`}>{t('Find in Market','Cari di Market')}</Link><button type="button" className="button secondary" disabled={busy===w.printingId} onClick={()=>onRemoveFromWishlist(w.printingId)}>{t('Remove','Hapus')}</button></div></div></article>})}</div></section>;
}
