import {db,errorResponse,HttpError,user} from '@/lib/server/store';

const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]??char));
type Address={recipientName?:string|null;addressLine?:string;city?:string;postalCode?:string;phone?:string};
export async function GET(_request:Request,{params}:{params:Promise<{id:string}>}){
  try{
    const profile=await user();const {id}=await params;const row=await db().prepare("SELECT o.seller_id AS sellerId,o.status,o.items,o.details,o.shipping_waybill_id AS waybill,o.biteship_tracking_id AS trackingId,o.shipping_tracking_url AS trackingUrl,l.title FROM checkout_orders o LEFT JOIN listings l ON l.id=o.listing_id WHERE o.id=? AND o.kind='MARKET'").bind(id).first<{sellerId:string|null;status:string;items:string;details:string|null;waybill:string|null;trackingId:string|null;trackingUrl:string|null;title:string|null}>();
    if(!row||row.sellerId!==profile.id)throw new HttpError(404,'Shipment label not found.');if(row.status!=='SHIPPED')throw new HttpError(409,'Create the shipment before printing its label.');
    let shipping:{sender?:Address;recipientName?:string;addressLine?:string;city?:string;postalCode?:string;phone?:string;courierName?:string;courierServiceName?:string;shippingLabel?:string}|undefined;try{shipping=JSON.parse(row.details||'{}') as typeof shipping}catch{}
    let cards:Array<{printingId:string;quantity:number}>=[];try{cards=JSON.parse(row.items) as typeof cards}catch{}
    const sender=shipping?.sender??{};const text=(value:string|undefined|null)=>escape(value?.trim()||'—');const cardLines=cards.map(item=>`<li>${text(item.printingId)} × ${item.quantity}</li>`).join('');const safeTrackingUrl=/^https:\/\//i.test(row.trackingUrl??'')?escape(row.trackingUrl!):'';
    const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VivrePlay Market shipping label</title><style>*{box-sizing:border-box}body{margin:0;padding:24px;font:14px/1.4 Arial,sans-serif;color:#172033}.label{max-width:760px;margin:auto;border:1px solid #111;padding:22px}.brand{font-weight:800;font-size:18px;letter-spacing:.04em;border-bottom:2px solid #111;padding-bottom:12px}.row{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:18px 0}.box{border:1px solid #9aa1aa;padding:12px;min-height:120px}.label h1{font-size:20px;margin:8px 0}.muted{color:#526071}.tracking{font-size:18px;font-weight:800;letter-spacing:.08em;border:2px dashed #111;padding:12px;margin:14px 0}.cards{margin:6px 0;padding-left:20px}@media print{body{padding:0}.label{border:0;max-width:none;width:100%;min-height:100vh}.no-print{display:none}}</style><body><main class="label"><div class="brand">VIVREPLAY | MARKET</div><h1>Shipment label</h1><div class="tracking">${text(row.waybill||row.trackingId)}</div><div><strong>${text([shipping?.courierName,shipping?.courierServiceName].filter(Boolean).join(' ')||undefined)}</strong>${safeTrackingUrl?` · <a href="${safeTrackingUrl}">Track shipment</a>`:''}</div><div class="row"><section class="box"><strong>FROM</strong><p>${text(sender.recipientName)}</p><p>${text(sender.addressLine)}<br>${text(sender.city)} ${text(sender.postalCode)}</p><p>${text(sender.phone)}</p></section><section class="box"><strong>TO</strong><p>${text(shipping?.recipientName)}</p><p>${text(shipping?.addressLine)}<br>${text(shipping?.city)} ${text(shipping?.postalCode)}</p><p>${text(shipping?.phone)}</p></section></div><strong>Package contents</strong><ul class="cards">${cardLines||'<li>Trading cards</li>'}</ul><p class="muted">Order VPM-${id.slice(0,8).toUpperCase()} · Keep cards protected from moisture and bending</p><button class="no-print" onclick="window.print()">Print label</button></main><script>window.addEventListener('load',()=>window.print())</script></body></html>`;
    return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'private, no-store','content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:; base-uri 'none'; frame-ancestors 'none'"}});
  }catch(error){return errorResponse(error)}
}
