import {db,errorResponse,HttpError} from '@/lib/server/store';
export async function GET(req:Request){try{const listingId=new URL(req.url).searchParams.get('listing');const d=db();const p=await d.prepare('SELECT seller_id AS id FROM listings WHERE id=?').bind(listingId).first<{id:string}>();if(!p)throw new HttpError(404,'Listing not found.');
const reviews=(await d.prepare(`SELECT r.rating,r.comment,r.subject_role AS role,r.created_at AS createdAt,p.display_name AS reviewer FROM market_reviews r JOIN profiles p ON p.id=r.reviewer_id WHERE r.subject_id=? ORDER BY r.created_at DESC LIMIT 20`).bind(p.id).all()).results;
const rating=(await d.prepare('SELECT subject_role AS role,COUNT(*) AS count,AVG(rating) AS average FROM market_reviews WHERE subject_id=? GROUP BY subject_role').bind(p.id).all()).results;
const completed=await d.prepare(`SELECT COUNT(*) AS count FROM checkout_orders WHERE seller_id=? AND kind='MARKET' AND status IN ('RECEIVED','COMPLETED')`).bind(p.id).first();
const responses=(await d.prepare(`SELECT o.created_at AS sentAt,(SELECT MIN(m.created_at) FROM listing_offer_messages m WHERE m.thread_id=COALESCE(o.thread_id,o.id) AND m.actor_id=l.seller_id AND m.created_at>=o.created_at) AS respondedAt FROM listing_offers o JOIN listings l ON l.id=o.listing_id WHERE l.seller_id=? AND l.type='WTS' AND o.actor_id!=? AND o.parent_offer_id IS NULL AND o.created_at>=datetime('now','-90 days') ORDER BY o.created_at DESC LIMIT 200`).bind(p.id,p.id).all<{sentAt:string;respondedAt:string|null}>()).results;
const parse=(s:string)=>Date.parse(s.replace(' ','T')+(/[zZ]|[+-]\d{2}:?\d{2}$/.test(s)?'':'Z'));const mature=responses.filter(r=>Date.now()-parse(r.sentAt)>=86400000);const answered=mature.filter(r=>r.respondedAt&&parse(r.respondedAt)-parse(r.sentAt)<=86400000);const hours=responses.flatMap(r=>r.respondedAt?[Math.max(0,(parse(r.respondedAt)-parse(r.sentAt))/3600000)]:[]).sort((a,b)=>a-b);const median=(v:number[])=>v.length?(v[Math.floor((v.length-1)/2)]+v[Math.floor(v.length/2)])/2:null;
const shipping=(await d.prepare(`SELECT paid_at AS paidAt,dispatched_at AS dispatchedAt,delivered_at AS deliveredAt FROM checkout_orders WHERE seller_id=? AND kind='MARKET' AND paid_at IS NOT NULL AND dispatched_at IS NOT NULL ORDER BY created_at DESC LIMIT 100`).bind(p.id).all<{paidAt:string;dispatchedAt:string;deliveredAt:string|null}>()).results;
const dispatch=shipping.map(r=>Math.max(0,(parse(r.dispatchedAt)-parse(r.paidAt))/3600000));const transit=shipping.flatMap(r=>r.deliveredAt?[Math.max(0,(parse(r.deliveredAt)-parse(r.dispatchedAt))/3600000)]:[]);
return Response.json({reviews,rating,completed:completed?.count??0,response:{samples:mature.length,percent:mature.length>=5?Math.round(answered.length/mature.length*100):null,medianHours:hours.length>=5?median(hours):null},shipping:{samples:dispatch.length,medianHours:dispatch.length>=3?median(dispatch):null,deliverySamples:transit.length,deliveryHours:transit.length>=3?median(transit):null}},{headers:{'Cache-Control':'public, max-age=60'}})}catch(e){return errorResponse(e)}}
