import {cards,printingFor} from '@/packages/card-data/catalog';
import type {Listing} from '@/packages/domain';

const printing=(cardIndex:number)=>printingFor(cards[cardIndex].id,'EN').id;
const ago=(hours:number)=>new Date(Date.now()-(hours*60*60*1000)).toISOString();

export const marketListingPreviews:Listing[]=[
  {id:'starter-red-core',printingId:printing(1),title:'Monkey D. Luffy SEC playset',amount:1850000,currency:'IDR',quantity:4,condition:'NM',type:'WTS',city:'Jakarta',seller:'Kaito',createdAt:ago(2),items:[{printingId:printing(1),quantity:4,condition:'NM',unitAmount:462500}]},
  {id:'starter-straw-hat',printingId:printing(2),title:'Looking for Roronoa Zoro SR playset',amount:500000,currency:'IDR',quantity:4,condition:'NM',type:'WTB',city:'Bandung',seller:'Nami',createdAt:ago(4),items:[{printingId:printing(2),quantity:4,condition:'NM',unitAmount:125000}]},
  {id:'starter-purple',printingId:printing(4),title:'Monkey D. Luffy SR ×4',amount:950000,currency:'IDR',quantity:4,condition:'NM',type:'WTS',city:'Surabaya',seller:'Rizky',createdAt:ago(7),items:[{printingId:printing(4),quantity:4,condition:'NM',unitAmount:237500}]},
  {id:'starter-sec',printingId:printing(5),title:'Roronoa Zoro SEC - near mint',amount:3000000,currency:'IDR',quantity:1,condition:'NM',type:'WTS',city:'Tangerang',seller:'Mika',createdAt:ago(11),items:[{printingId:printing(5),quantity:1,condition:'NM',unitAmount:3000000}]},
  {id:'starter-shanks-leader',printingId:printing(0),title:'Shanks Leader alternate art',amount:1750000,currency:'IDR',quantity:1,condition:'NM',type:'WTS',city:'Jakarta',seller:'Ari',createdAt:ago(16),items:[{printingId:printing(0),quantity:1,condition:'NM',unitAmount:1750000}]},
  {id:'starter-newgate-leader',printingId:printing(3),title:'Searching for Edward.Newgate Leader',amount:1200000,currency:'IDR',quantity:1,condition:'NM',type:'WTB',city:'Depok',seller:'Faris',createdAt:ago(22),items:[{printingId:printing(3),quantity:1,condition:'NM',unitAmount:1200000}]},
  {id:'starter-staples',printingId:printing(2),title:'Red competitive staples bundle',amount:880000,currency:'IDR',quantity:6,condition:'NM',type:'WTS',city:'Bekasi',seller:'Sora',createdAt:ago(29),items:[{printingId:printing(2),quantity:4,condition:'NM',unitAmount:120000},{printingId:printing(6),quantity:2,condition:'NM',unitAmount:200000}]},
  {id:'starter-shanks-core',printingId:printing(0),title:'Shanks Leader + Benn Beckman',amount:2100000,currency:'IDR',quantity:2,condition:'NM',type:'WTS',city:'Yogyakarta',seller:'Dimas',createdAt:ago(35),items:[{printingId:printing(0),quantity:1,condition:'NM',unitAmount:1500000},{printingId:printing(6),quantity:1,condition:'NM',unitAmount:600000}]},
  {id:'starter-red-collection',printingId:printing(2),title:'Red foil and Leader collection',amount:4780000,currency:'IDR',quantity:16,condition:'Mixed',type:'WTS',city:'Jakarta',seller:'Arga',createdAt:ago(39),items:[{printingId:printing(2),quantity:4,condition:'NM',unitAmount:125000},{printingId:printing(6),quantity:4,condition:'NM',unitAmount:180000},{printingId:printing(0),quantity:1,condition:'NM',unitAmount:1500000},{printingId:printing(3),quantity:1,condition:'LP',unitAmount:800000},{printingId:printing(1),quantity:2,condition:'NM',unitAmount:350000},{printingId:printing(4),quantity:4,condition:'NM',unitAmount:140000}]},
  {id:'starter-finishers-lot',printingId:printing(1),title:'SEC and SR finisher lot',amount:3940000,currency:'IDR',quantity:12,condition:'NM',type:'WTS',city:'Medan',seller:'Nico',createdAt:ago(46),items:[{printingId:printing(1),quantity:4,condition:'NM',unitAmount:470000},{printingId:printing(4),quantity:4,condition:'NM',unitAmount:235000},{printingId:printing(5),quantity:4,condition:'NM',unitAmount:280000}]},
  {id:'starter-red-playset-wtb',printingId:printing(2),title:'Looking for red playsets and Leaders',amount:4280000,currency:'IDR',quantity:14,condition:'NM',type:'WTB',city:'Makassar',seller:'Tama',createdAt:ago(52),items:[{printingId:printing(2),quantity:4,condition:'NM',unitAmount:120000},{printingId:printing(6),quantity:4,condition:'NM',unitAmount:175000},{printingId:printing(0),quantity:1,condition:'NM',unitAmount:1450000},{printingId:printing(3),quantity:1,condition:'NM',unitAmount:750000},{printingId:printing(1),quantity:2,condition:'NM',unitAmount:325000},{printingId:printing(4),quantity:2,condition:'NM',unitAmount:125000}]}
];
