'use client';

import Link from 'next/link';
import {ArrowRightIcon as ArrowRight, CardsIcon as Cards, CheckCircleIcon as CheckCircle, GameControllerIcon as GameController, GraduationCapIcon as GraduationCap, PlayCircleIcon as PlayCircle, SwordIcon as Sword, TrophyIcon as Trophy, UsersThreeIcon as UsersThree} from '@phosphor-icons/react';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@/utils/supabase/client';
import {CardArt} from './card-art';
import {DepthCarousel} from './depth-carousel';
import {displayCardName} from './card-name';
import {readLocalDecks,type LocalDeck} from './local-decks';
import type {Card} from '@/packages/card-data/catalog';

type Format='ranked'|'friendly'|'practice';
type PrintingRow={id:string;rarity:string|null;set_code:string|null;card_image_url:string|null;tcg_card_assets?:Array<{kind:string;object_key:string}>;tcg_card_identities:{code:string;name:string;color:string;card_type:Card['type'];cost:number;power:number;effect_text:string}};
const formats:Array<{id:Format;title:string;copy:string;icon:typeof Trophy;available:boolean}>=[{id:'ranked',title:'Ranked',copy:'Constructed ladder. Requires a signed-in account when matchmaking opens.',icon:Trophy,available:false},{id:'friendly',title:'Friendly',copy:'Invite a player or test a finished list without the ladder.',icon:UsersThree,available:false},{id:'practice',title:'Practice table',copy:'Open your deck at the interactive table and rehearse lines.',icon:GameController,available:true}];
const total=(deck:LocalDeck)=>Object.values(deck.entries).reduce((sum,count)=>sum+count,0);const ready=(deck:LocalDeck)=>Boolean(deck.leaderPrintingId)&&total(deck)===50;
function cardFrom(row:PrintingRow):Card{const identity=row.tcg_card_identities;return{id:row.id,code:identity.code,name:displayCardName(identity.name,identity.code),color:identity.color,type:identity.card_type,cost:identity.cost,power:identity.power,rarity:row.rarity??'',art:0,effect:identity.effect_text,imageUrl:row.card_image_url??undefined,imageSource:'external',setCode:row.set_code??undefined,assetPath:row.tcg_card_assets?.find(item=>item.kind==='small')?.object_key};}

export function ArenaLobby(){
 const [decks,setDecks]=useState<LocalDeck[]>([]);const [selectedId,setSelectedId]=useState('');const [format,setFormat]=useState<Format>('practice');const [cards,setCards]=useState<Record<string,Card>>({});const [heroFallback,setHeroFallback]=useState<Card[]>([]);
 useEffect(()=>{let active=true;void createClient().from('tcg_card_printings').select('id,rarity,set_code,card_image_url,tcg_card_assets(kind,object_key),tcg_card_identities!inner(code,name,color,card_type,cost,power,effect_text)').eq('language','EN').not('card_image_url','is',null).limit(3).then(({data})=>{if(active)setHeroFallback(((data??[]) as unknown as PrintingRow[]).map(cardFrom))});return()=>{active=false}},[]);
 useEffect(()=>{const refresh=()=>{const next=readLocalDecks().sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));setDecks(next);setSelectedId(current=>current&&next.some(deck=>deck.id===current)?current:next.find(ready)?.id??'');};refresh();window.addEventListener('vivreplay:decks-changed',refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener('vivreplay:decks-changed',refresh);window.removeEventListener('storage',refresh)}},[]);
 const playable=useMemo(()=>decks.filter(ready),[decks]);const selected=playable.find(deck=>deck.id===selectedId)??playable[0];const activeFormat=formats.find(item=>item.id===format)??formats[2];
 useEffect(()=>{const ids=[...new Set(playable.flatMap(deck=>[deck.leaderPrintingId,...Object.keys(deck.entries)].filter((id):id is string=>Boolean(id))))];if(!ids.length){setCards({});return}let active=true;void createClient().from('tcg_card_printings').select('id,rarity,set_code,card_image_url,tcg_card_assets(kind,object_key),tcg_card_identities!inner(code,name,color,card_type,cost,power,effect_text)').in('id',ids).then(({data})=>{if(active)setCards(Object.fromEntries(((data??[]) as unknown as PrintingRow[]).map(row=>[row.id,cardFrom(row)])))});return()=>{active=false}},[playable]);
 const selectedCards=selected?[selected.leaderPrintingId,...Object.keys(selected.entries)].map(id=>id?cards[selected.artworkIds[id]??id]??cards[id]:undefined).filter((card):card is Card=>Boolean(card)).slice(0,5):[];
 const deckHeroCards=playable.map(deck=>deck.leaderPrintingId?cards[deck.artworkIds[deck.leaderPrintingId]??deck.leaderPrintingId]??cards[deck.leaderPrintingId]:undefined).filter((card):card is Card=>Boolean(card)).slice(0,3);const heroCards=deckHeroCards.length?deckHeroCards:heroFallback;
 return <main className="page arena-lobby"><section className="library-intro arena-intro"><div className="library-intro-copy"><p className="kicker">ARENA</p><h1>Bring a finished deck to the table.</h1><p>Choose a legal list, select the way you want to play, then open the table with the same deck you built.</p></div><div className="library-intro-rail arena-intro-rail" aria-hidden="true"><div className="library-intro-rail-cards">{heroCards.map((card,index)=><div className={`library-intro-rail-card rail-card-${index}`} key={card.id}><CardArt card={card}/></div>)}{!heroCards.length&&Array.from({length:3},(_,index)=><i className={`library-intro-rail-skeleton rail-card-${index}`} key={index}/>)}</div></div></section>
 <section className="arena-deck-section"><header className="section-heading"><div><p className="eyebrow">YOUR PLAYABLE DECKS</p><h2>{playable.length?'Pick your main deck.':'No complete deck yet.'}</h2><p>{playable.length?'A deck needs one leader and exactly 50 cards before it can enter the Arena.':'Finish and save a deck in the builder, then come back here to play it.'}</p></div>{selected&&<Link className="text-action" href={`/decks/builder?local=${encodeURIComponent(selected.id)}`}>Edit selected deck <ArrowRight size={15}/></Link>}</header>{playable.length?<DepthCarousel className="arena-deck-carousel" label="Choose a deck for the Arena" items={playable.map(deck=>{const leader=deck.leaderPrintingId?cards[deck.artworkIds[deck.leaderPrintingId]??deck.leaderPrintingId]??cards[deck.leaderPrintingId]:undefined;return{id:deck.id,label:`Use ${deck.title} in the Arena`,onSelect:()=>setSelectedId(deck.id),content:leader?<CardArt card={leader}/>:<div className="arena-deck-card-fallback"><Cards size={22}/><b>{deck.leaderCode||'Leader'}</b></div>}})}/>:<section className="arena-empty-deck"><Cards size={25}/><div><h3>Build your first playable deck.</h3><p>Choose a leader, add 50 cards, and save the list on this device.</p></div><Link href="/decks/builder">Open deck builder <ArrowRight size={15}/></Link></section>}</section>
 <section className="arena-match-section"><header className="section-heading"><div><p className="eyebrow">MATCH SETUP</p><h2>{selected?selected.title:'Choose a deck first.'}</h2><p>{selected?`${selected.leaderCode||'Leader'} · ${total(selected)}/50 cards · ready for the table.`:'Match formats unlock once a complete saved deck is selected.'}</p></div></header><div className="arena-match-layout"><div className="arena-selected-deck">{selectedCards.length?<DepthCarousel className="arena-selected-carousel" label={`${selected?.title} card preview`} items={selectedCards.map(card=>({id:card.id,label:`View ${card.name}`,onSelect:()=>{},content:<CardArt card={card}/> }))}/>:<Cards size={25}/>}<div><p>SELECTED DECK</p><b>{selected?.title||'No deck selected'}</b><span>{selected?.leaderCode||'Leader needed'} · {selected?`${total(selected)}/50 cards`:'Complete a deck to continue'}</span>{selected&&<CheckCircle size={17}/>}</div></div><div className="arena-format-options">{formats.map(item=>{const Icon=item.icon;return <button type="button" key={item.id} className={format===item.id?'selected':''} onClick={()=>setFormat(item.id)}><Icon size={20}/><span><b>{item.title}</b><small>{item.copy}</small></span><em>{item.available?'Available':'Preparing'}</em></button>})}</div><div className="arena-launch">{selected&&activeFormat.available?<Link className="button" href={`/play/board?deck=${encodeURIComponent(selected.id)}&format=${format}`}><PlayCircle size={18}/>Open practice table</Link>:<button className="button" type="button" disabled>{selected?'Format preparing':'Choose a complete deck'}</button>}</div></div></section>
 <section className="arena-guidance"><header className="section-heading"><div><p className="eyebrow">GET READY</p><h2>Everything needed before a first match.</h2></div></header><div><article><GraduationCap size={21}/><h3>Learn the table</h3><p>Walk through zones, turns, attacks, counters, and triggers at your own pace.</p><Link href="/play/tutorial">Open tutorial <ArrowRight size={14}/></Link></article><article><Cards size={21}/><h3>Tune the list</h3><p>Use the builder’s curve, counter, colour, and subtype checks before calling a deck finished.</p><Link href="/decks/builder">Open builder <ArrowRight size={14}/></Link></article><article><Sword size={21}/><h3>Practice a line</h3><p>Use the interactive table to rehearse sequencing and decisions with your saved deck.</p>{selected?<Link href={`/play/board?deck=${encodeURIComponent(selected.id)}&format=practice`}>Open table <ArrowRight size={14}/></Link>:<span>Choose a deck above</span>}</article></div></section>
 </main>;
}

const tutorialChapters=['Basics: the table','The cards','The game begins','Your first action','Play a Character','Attack!','When you can attack','Blockers','Counters','Triggers','Choosing targets','Abilities','Keywords and costs','The table itself','The turn and its phases','Playing online'];
export function ArenaTutorialIndex(){const phases=[{title:'Read the table',range:'Chapters 1–4',copy:'Learn the zones, card types, setup, and the first decision of a turn.'},{title:'Win a battle',range:'Chapters 5–9',copy:'Play cards, attack, use Blockers, Counter, and understand Life.'},{title:'Resolve the details',range:'Chapters 10–13',copy:'Work through Triggers, targets, abilities, keywords, and costs.'},{title:'Play a full match',range:'Chapters 14–16',copy:'Put a turn together, handle the table, and take the flow online.'}];return <main className="page arena-tutorial-index tutorial-index-page"><section className="library-intro tutorial-index-intro"><div className="library-intro-copy"><p className="kicker">LEARN TO PLAY</p><h1>Learn the table, then play it.</h1><p>Start with a guided board tour. Every chapter points to the actual part of the table it explains.</p></div><Link className="tutorial-index-start" href="/play/table">Start Chapter 1 <PlayCircle size={17}/></Link></section><section className="tutorial-path"><header className="section-heading"><div><p className="eyebrow">YOUR PATH</p><h2>One complete game, in sixteen chapters.</h2><p>Chapter 1 is ready now. The rest unlock as the interactive lessons are completed.</p></div><span className="tutorial-path-status">1 of 16 ready</span></header><div className="tutorial-phase-grid">{phases.map((phase,index)=><article className={index===0?'tutorial-phase current':'tutorial-phase'} key={phase.title}><span>{String(index+1).padStart(2,'0')}</span><small>{phase.range}</small><h3>{phase.title}</h3><p>{phase.copy}</p>{index===0?<Link href="/play/table">Open Chapter 1 <ArrowRight size={14}/></Link>:<em>Coming with the next lesson</em>}</article>)}</div></section><section className="tutorial-chapters-section"><header className="section-heading"><div><p className="eyebrow">CHAPTERS</p><h2>Follow the table in order.</h2></div></header><div className="tutorial-chapter-grid">{tutorialChapters.map((title,index)=>index===0?<Link href="/play/table" key={title} className="tutorial-chapter active"><b>1</b><span>{title}</span><em>Start <PlayCircle size={15}/></em></Link>:<article key={title} className="tutorial-chapter locked"><b>{index+1}</b><span>{title}</span><em>Locked</em></article>)}</div></section></main>}
