 'use client';
import {useState} from 'react';
import {QrCodeIcon as QR,BankIcon as Bank,WalletIcon as Wallet} from '@phosphor-icons/react';
import {formatMoney} from '@/packages/domain';
export function MarketPaymentPreview({amount,currency,language}:{amount:number;currency:string;language:'EN'|'ID'}){
 const id=language==='ID';const [method,setMethod]=useState<'qris'|'va'|'ewallet'>('qris');const [channel,setChannel]=useState('bca');
 const choices=[{key:'qris' as const,name:'QRIS',icon:QR},{key:'va' as const,name:id?'Virtual account bank':'Bank virtual account',icon:Bank},{key:'ewallet' as const,name:id?'Dompet digital':'E-wallet',icon:Wallet}];
 return <section className="market-payment-preview"><header><h2>{id?'Pembayaran':'Payment'}</h2><span>{id?'Pratinjau':'Preview'}</span></header><div className="payment-preview-methods" role="group" aria-label={id?'Metode pembayaran':'Payment method'}>{choices.map(c=><button key={c.key} type="button" aria-pressed={method===c.key} onClick={()=>{setMethod(c.key);setChannel(c.key==='ewallet'?'dana':'bca')}}><c.icon size={20}/>{c.name}</button>)}</div>{method!=='qris'&&<div className="payment-preview-channels" role="group" aria-label={id?'Pilih bank atau dompet':'Choose bank or wallet'}>{(method==='va'?['bca','bni','bri','mandiri','permata']:['dana','shopeepay']).map(c=><button key={c} type="button" aria-pressed={channel===c} onClick={()=>setChannel(c)}>{c==='shopeepay'?'ShopeePay':c.toUpperCase()}</button>)}</div>}<div className="payment-preview-instructions"><strong>{formatMoney(amount,currency)}</strong>{method==='qris'?<><QR size={56} aria-hidden="true"/><p>{id?'Kode QRIS akan muncul setelah pembayaran dibuat':'Your QRIS code appears after payment is created'}</p><ol><li>{id?'Buka aplikasi bank atau dompet digital':'Open your banking or e-wallet app'}</li><li>{id?'Pindai QRIS, lalu periksa jumlah pembayaran':'Scan the QRIS code and check the amount'}</li><li>{id?'Selesaikan pembayaran di aplikasi':'Complete payment in the app'}</li></ol></>:method==='va'?<><Bank size={35} aria-hidden="true"/><p>{id?'Nomor virtual account akan muncul setelah pembayaran dibuat':'Your virtual account number appears after payment is created'}</p><ol><li>{id?'Pilih pembayaran virtual account di aplikasi bank':'Choose virtual account payment in your banking app'}</li><li>{id?'Masukkan nomor pembayaran, lalu periksa jumlahnya':'Enter the payment number and check the amount'}</li><li>{id?'Selesaikan transfer':'Complete the transfer'}</li></ol></>:<><Wallet size={35} aria-hidden="true"/><p>{id?'Lanjutkan pembayaran melalui dompet digital pilihan Anda':'Continue payment in your selected e-wallet'}</p></>}<small>{id?'Pratinjau saja, belum membuat pesanan atau menagih pembayaran':'Preview only, no order or charge is created'}</small></div><footer>{id?'Pembayaran melalui iPaymu':'Payments via iPaymu'}</footer></section>;
}
