'use client';

import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRightIcon as ArrowRight,MinusIcon as Minus,PlusIcon as Plus,ShoppingCartIcon as Cart,TrashIcon as Trash} from '@phosphor-icons/react';
import {formatMoney,Listing} from '@/packages/domain';
import {cardFor,Card} from '@/packages/card-data/catalog';
import {CardArt} from './card-art';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';

type Line={listingId:string;listingTitle:string;items:{printingId:string;quantity:number}[]};
const KEY='vivreplay-market-cart-v1';
export function MarketCartButton({locale='EN'}:{locale?:'EN'|'ID'}){
  const [open,setOpen]=useState(false);const [lines,setLines]=useState<Line[]>([]);const [count,setCount]=useState(0);const [listings,setListings]=useState<Listing[]>([]);const [loading,setLoading]=useState(false);
  const id=locale==='ID';
  const sync=()=>{try{const cart=JSON.parse(localStorage.getItem(KEY)||'null');const next:Line[]=Array.isArray(cart?.lines)?cart.lines.filter((line:Line)=>line?.listingId&&Array.isArray(line.items)):[];setLines(next);setCount(next.reduce((total:number,line:Line)=>total+line.items.reduce((sum:number,item)=>sum+item.quantity,0),0));}catch{setLines([]);setCount(0)}};
  useEffect(()=>{sync();const update=()=>sync();const show=()=>{sync();setOpen(true)};window.addEventListener('vivreplay:market-cart-updated',update);window.addEventListener('vivreplay:open-market-cart',show);window.addEventListener('storage',update);return()=>{window.removeEventListener('vivreplay:market-cart-updated',update);window.removeEventListener('vivreplay:open-market-cart',show);window.removeEventListener('storage',update)}},[]);
  useEffect(()=>{if(!open)return;let active=true;setLoading(true);fetch('/api/listings',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error('Listings could not load');return await response.json() as {listings?:Listing[]}}).then(payload=>{if(active)setListings(payload.listings??[])}).catch(()=>{if(active)setListings([])}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[open]);
  const listingMap=new Map(listings.map(listing=>[listing.id,listing]));
  const total=useMemo(()=>lines.reduce((sum,line)=>{const listing=listingMap.get(line.listingId);return sum+line.items.reduce((lineTotal,item)=>{const entry=listing?.items?.find(card=>card.printingId===item.printingId);const units=listing?.items?.reduce((n,card)=>n+card.quantity,0)||listing?.quantity||1;const unit=entry?.unitAmount??Math.floor((listing?.amount??0)/units);return lineTotal+unit*item.quantity},0)},0),[lines,listings]);
  const update=(listingId:string,printingId:string,quantity:number)=>{const next=lines.map(line=>line.listingId===listingId?{...line,items:line.items.map(item=>item.printingId===printingId?{...item,quantity:Math.max(0,Math.min(99,quantity))}:item).filter(item=>item.quantity>0)}:line).filter(line=>line.items.length);localStorage.setItem(KEY,JSON.stringify({sellerId:listings[0]?.sellerId??'',lines:next}));setLines(next);window.dispatchEvent(new Event('vivreplay:market-cart-updated'))};
  const clear=()=>{localStorage.removeItem(KEY);setLines([]);window.dispatchEvent(new Event('vivreplay:market-cart-updated'))};
  return <><button type="button" className="market-store-link market-cart-link" aria-label={id?`Keranjang, ${count} kartu`:`Cart, ${count} cards`} onClick={()=>{sync();setOpen(true)}}><Cart size={17}/><span>{id?'Keranjang':'Cart'}</span>{count>0&&<b>{count}</b>}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="market-cart-drawer" showCloseButton><DialogHeader className="market-cart-header"><DialogTitle>{id?'Keranjang':'Your cart'}</DialogTitle><span>{count} {id?'kartu':'cards'}</span></DialogHeader><div className="market-cart-lines">{loading?<div className="market-cart-empty">{id?'Memuat keranjang…':'Loading cart…'}</div>:!lines.length?<div className="market-cart-empty"><Cart size={25}/><p>{id?'Keranjang masih kosong.':'Your cart is empty.'}</p><Link href="/market" onClick={()=>setOpen(false)}>{id?'Jelajahi Market':'Browse Market'} <ArrowRight size={15}/></Link></div>:lines.map(line=>{const listing=listingMap.get(line.listingId);return <section className="market-cart-listing" key={line.listingId}><Link href={`/market/${line.listingId}`} className="market-cart-listing-title" onClick={()=>setOpen(false)}>{listing?.title??line.listingTitle}</Link>{line.items.map(item=>{const entry=listing?.items?.find(card=>card.printingId===item.printingId);const card=(entry?.card??(listing?.printingId===item.printingId?listing.card:cardFor(item.printingId))) as Card|undefined;const units=listing?.items?.reduce((n,card)=>n+card.quantity,0)||listing?.quantity||1;const unit=entry?.unitAmount??Math.floor((listing?.amount??0)/units);return <div className="market-cart-item" key={item.printingId}>{card&&<CardArt card={{...card,id:item.printingId}} small/>}<div className="market-cart-item-copy"><strong>{card?.name??item.printingId}</strong><small>{formatMoney(unit,listing?.currency??'IDR')} each</small><div className="market-cart-quantity"><button type="button" aria-label="Decrease quantity" onClick={()=>update(line.listingId,item.printingId,item.quantity-1)}><Minus size={13}/></button><span>{item.quantity}</span><button type="button" aria-label="Increase quantity" onClick={()=>update(line.listingId,item.printingId,item.quantity+1)}><Plus size={13}/></button></div></div><strong className="market-cart-line-total">{formatMoney(unit*item.quantity,listing?.currency??'IDR')}</strong><button type="button" className="market-cart-remove" aria-label="Remove item" onClick={()=>update(line.listingId,item.printingId,0)}><Trash size={15}/></button></div>})}</section>})}</div>{lines.length>0&&<footer className="market-cart-footer"><div><span>{id?'Subtotal kartu':'Cards subtotal'}</span><strong>{formatMoney(total,'IDR')}</strong></div><Link href="/checkout/market?cart=1" className="button" onClick={()=>setOpen(false)}>{id?'Lanjut ke checkout':'Continue to checkout'} <ArrowRight size={17}/></Link><button type="button" className="market-cart-clear" onClick={clear}>{id?'Kosongkan keranjang':'Clear cart'}</button></footer>}</DialogContent></Dialog></>;
}
