'use client';

import Link from 'next/link';
import {ArrowRightIcon,ChartBarIcon,SwordIcon,TrophyIcon} from '@phosphor-icons/react';
import {useEffect,useState} from 'react';

type Finish={place:number;playerName:string;leaderCode:string|null;archetype:string|null;deckSourceUrl:string;listStatus:string;cards:number;cardCount:number};
type MatchSummary={id:string;round:string;bestOf:number;leaderOneCode:string;archetypeOne:string;playerOneName:string|null;leaderTwoCode:string;archetypeTwo:string;playerTwoName:string|null;scoreOne:number;scoreTwo:number;winnerLeaderCode:string;winnerSide:number;seriesComplete:number;scoreComplete:number;summary:string;sourceName:string;sourceUrl:string;evidenceStatus:string};
type MatchupStat={leaderOneCode:string;archetypeOne:string;leaderTwoCode:string;archetypeTwo:string;matches:number;leaderOneWins:number;leaderTwoWins:number;games:number;leaderOneGameWins:number;leaderTwoGameWins:number;leaderOneWinRate:number;leaderTwoWinRate:number;leaderOneGameWinRate:number;leaderTwoGameWinRate:number;sources:string[]};
type TournamentEvent={id:string;name:string;eventDate:string;playerCount:number|null;publishedDecklistCount:number;sourceName:string;sourceUrl:string;finishes:Finish[];matchSummaries:MatchSummary[];leaders:{leaderCode:string;archetype:string;finishes:number}[]};
type TournamentFeed={events:TournamentEvent[];matchRecords:number;matchSummaries:number;matchupStats:MatchupStat[]};

export function MetaExperience(){
  const [language,setLanguage]=useState<'EN'|'ID'>('EN');
  const [feed,setFeed]=useState<TournamentFeed|null>(null);
  useEffect(()=>{
    const syncLocale=()=>setLanguage(window.localStorage.getItem('vivreplay-locale')==='ID'?'ID':'EN');
    const onLocale=(event:globalThis.Event)=>setLanguage((event as CustomEvent<'EN'|'ID'>).detail);
    syncLocale();window.addEventListener('vivreplay:locale',onLocale);
    let active=true;void fetch('/api/meta/tournaments').then(response=>response.ok?response.json():null).then(data=>{if(active&&data)setFeed(data as TournamentFeed)}).catch(()=>{});
    return()=>{active=false;window.removeEventListener('vivreplay:locale',onLocale)};
  },[]);
  const id=language==='ID';
  const event=feed?.events[0];
  const verifiedLists=event?.finishes.filter(finish=>finish.listStatus==='VERIFIED').length??0;
  const matchSummaries=feed?.events.flatMap(tournament=>tournament.matchSummaries.map(match=>({...match,eventName:tournament.name})))??[];
  return <main className="page meta-page">
    <header className="meta-hero"><div className="meta-hero-copy"><p className="eyebrow"><ChartBarIcon size={15}/> {id?'Meta Turnamen':'Tournament meta'}</p><h1>{id?'Hasil turnamen terverifikasi, tanpa menebak matchup.':'Verified tournament results, without guessing matchups.'}</h1><p>{id?'Peringkat menunjukkan hasil akhir dan contoh deck. Data itu sendiri tidak membuktikan tingkat kemenangan antar-leader.':'Placements show final results and deck examples. They do not establish win rates between leaders.'}</p><div className="meta-summary"><span><b>{feed?.events.length??'—'}</b> {id?'event':'events'}</span><span><b>{event?.publishedDecklistCount??'—'}</b> {id?'decklist terbit':'published lists'}</span><span><b>{feed?.matchRecords??'—'}</b> {id?'hasil matchup terverifikasi':'verified match results'}</span><span><b>{feed?.matchSummaries??'—'}</b> {id?'ringkasan video':'video summaries'}</span></div></div></header>
    {event?<>
      <section className="meta-preview" aria-labelledby="event-results-title"><header><div><p className="eyebrow"><TrophyIcon size={15}/> {id?'Event terbaru':'Latest event'}</p><h2 id="event-results-title">{event.name}</h2></div><a href={event.sourceUrl} target="_blank" rel="noreferrer">{id?'Sumber event':'Event source'} <ArrowRightIcon size={16}/></a></header><p className="meta-event-note">{new Date(`${event.eventDate}T00:00:00Z`).toLocaleDateString(id?'id-ID':'en-US',{dateStyle:'long',timeZone:'UTC'})} · {event.playerCount?.toLocaleString()} {id?'peserta':'entrants'} · {verifiedLists}/{event.finishes.length} {id?'decklist terverifikasi':'decklists verified'}</p>
        <div className="meta-results-table-wrap"><table className="meta-results-table"><thead><tr><th>{id?'Posisi':'Place'}</th><th>{id?'Pemain':'Player'}</th><th>Leader</th><th>{id?'Daftar deck':'Decklist'}</th></tr></thead><tbody>{event.finishes.map(finish=><tr key={finish.place}><td>{finish.place}</td><td>{finish.playerName}</td><td>{finish.archetype??finish.leaderCode??'—'}</td><td><a href={finish.deckSourceUrl} target="_blank" rel="noreferrer">{finish.listStatus==='VERIFIED'?(id?'Tersimpan & terverifikasi':'Stored · verified'):(id?'Buka sumber':'View source')} <ArrowRightIcon size={13}/></a></td></tr>)}</tbody></table></div>
      </section>
      <section className="meta-next"><div><p className="eyebrow"><SwordIcon size={15}/> {id?'Catatan matchup':'Matchup evidence'}</p><h2>{feed?.matchRecords?`${feed.matchRecords} ${id?'hasil laga terverifikasi':'verified head-to-head records'}`:(id?'Belum ada hasil laga terverifikasi.':'No verified head-to-head results yet.')}</h2><p>{id?'Analisis video yang disetujui masuk ke statistik matchup. Jumlah seri dan game ditampilkan bersama win rate.':'User-approved video analyses contribute to matchup stats. Win rates show their series and game sample counts.'}</p></div><Link href="/decks/builder">{id?'Buka deck builder':'Open deck builder'} <ArrowRightIcon size={16}/></Link></section>
      {feed?.matchupStats.length? <section className="meta-matchup-stats"><header><p className="eyebrow"><SwordIcon size={15}/> {id?'Win rate matchup':'Matchup win rates'}</p><p>{id?'Seri dan game terhitung terpisah; jumlah sampel selalu ditampilkan.':'Series and game results are counted separately; sample sizes are shown.'}</p></header><div>{feed.matchupStats.map(stat=><article key={`${stat.leaderOneCode}-${stat.archetypeOne}-${stat.leaderTwoCode}-${stat.archetypeTwo}`}><div><h3>{stat.archetypeOne} <span>vs</span> {stat.archetypeTwo}</h3><small>{stat.matches} {id?'seri':'series'} · {stat.games} {id?'game':'games'}</small></div><section><p><b>{Math.round(stat.leaderOneWinRate*100)}%</b><span>{stat.leaderOneWins}–{stat.leaderTwoWins} {id?'seri':'series'}</span><small>{stat.archetypeOne}</small></p><p><b>{Math.round(stat.leaderOneGameWinRate*100)}%</b><span>{stat.leaderOneGameWins}–{stat.leaderTwoGameWins} {id?'game':'games'}</span><small>{stat.archetypeOne}</small></p><p><b>{Math.round(stat.leaderTwoWinRate*100)}%</b><span>{stat.leaderTwoWins}–{stat.leaderOneWins} {id?'seri':'series'}</span><small>{stat.archetypeTwo}</small></p><p><b>{Math.round(stat.leaderTwoGameWinRate*100)}%</b><span>{stat.leaderTwoGameWins}–{stat.leaderOneGameWins} {id?'game':'games'}</span><small>{stat.archetypeTwo}</small></p></section></article>)}</div></section>:null}
      {matchSummaries.length>0&&<section className="meta-video-summaries" aria-label={id?'Ringkasan pertandingan dari video':'Video match records'}><header><p className="eyebrow"><SwordIcon size={15}/> {id?'Analisis video':'Video match analysis'}</p><h2>{id?'Hasil pertandingan':'Match records'} <span>{id?'terverifikasi · bersumber dari ringkasan video':'verified · sourced from video analysis'}</span></h2></header>{matchSummaries.map(match=><article className="meta-video-summary" key={match.id}><div className="meta-video-summary-heading"><div><p>{match.eventName} · {match.round} · {match.scoreComplete?'Best of '+match.bestOf:(id?'skor parsial':'partial score')}</p><h3>{match.seriesComplete?`${match.archetypeOne} ${match.scoreOne}–${match.scoreTwo} ${match.archetypeTwo}`:`${match.archetypeOne} ${match.scoreOne}–${match.scoreTwo} ${match.archetypeTwo} · ${id?'belum selesai':'incomplete'}`}</h3></div><a href={match.sourceUrl} target="_blank" rel="noreferrer">{id?'Sumber turnamen':'Tournament source'} <ArrowRightIcon size={14}/></a></div><p>{match.summary}</p><small>{match.sourceName} · {match.seriesComplete?(id?'hasil seri dihitung dalam statistik matchup':'series result included in matchup stats'):(id?'hanya game yang terlihat dihitung; win rate seri menunggu hasil akhir':'observed games count; series win rate waits for the final result')}</small></article>)}</section>}
    </>:<section className="meta-next"><div><p className="eyebrow">{id?'Data turnamen':'Tournament data'}</p><h2>{id?'Data turnamen belum tersedia.':'Tournament records are not available yet.'}</h2><p>{id?'Terapkan migrasi tournament untuk memuat hasil terverifikasi.':'Apply the tournament data migration to load verified results.'}</p></div></section>}
  </main>;
}
