'use client';
import {useState} from 'react';
import Link from 'next/link';
import {UserIcon as UserRound, GlobeIcon as Globe, ShieldCheckIcon as ShieldCheck, FloppyDiskIcon as Save} from '@phosphor-icons/react';
import {toast} from 'sonner';
import {api,useAccount} from '@/lib/client';
import {Picker} from './catalog';
import {AccountStatus} from './status';
export function Profile(){const {data,error,refresh}=useAccount();if(!data)return <main className="page"><AccountStatus error={error} retry={refresh}/></main>;return <ProfileForm profile={data.profile} refresh={refresh}/>}
function ProfileForm({profile,refresh}:{profile:Record<string,string>;refresh:()=>Promise<void>}){const [currency,setCurrency]=useState(profile.currency);const [locale,setLocale]=useState(profile.locale);const [busy,setBusy]=useState(false);return <main className="page"><div className="page-heading"><div><p className="eyebrow">YOUR TCG IDENTITY</p><h1>Player profile</h1><p>One identity for everything you collect and play.</p></div></div><div className="profile-layout"><section className="profile-card"><div className="profile-emblem"><UserRound size={44}/></div><h2>{profile.display_name}</h2><p>@{profile.username}</p><span className="badge">COLLECTOR · EARLY ACCESS</span><div className="profile-facts"><span><Globe size={15}/>{profile.region} · {profile.timezone}</span><span><ShieldCheck size={15}/>Collection private by default</span></div><Link className="button secondary" href={`/players/${profile.username}`}>View profile</Link></section><form className="form-stack settings-panel" onSubmit={async e=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await api('/api/profile',{username:String(f.get('username')),displayName:String(f.get('displayName')),region:String(f.get('region')).toUpperCase(),timezone:String(f.get('timezone')),currency,locale});await refresh();toast.success('Profile updated')}catch(err){toast.error((err as Error).message)}finally{setBusy(false)}}}><h2>Make it yours</h2><div className="form-row"><label>Display name<input name="displayName" defaultValue={profile.display_name} minLength={2} maxLength={50} required/></label><label>Username<input name="username" defaultValue={profile.username} pattern="[a-z0-9_-]{3,30}" required/></label></div><div className="form-row"><label>Region (country code)<input name="region" defaultValue={profile.region} minLength={2} maxLength={2} required/></label><label>Timezone<input name="timezone" defaultValue={profile.timezone} required/></label></div><div className="form-row"><label>Display currency<Picker label="Display currency" value={currency} onChange={setCurrency} options={['IDR','USD','JPY']}/></label><label>Preferred UI language<Picker label="UI language preference" value={locale} onChange={setLocale} options={['en','id']}/></label></div><p className="notice">Language preference is saved. This first release uses English UI. Original seller prices remain visible; FX conversion awaits a verified rate source.</p><div className="privacy-note"><ShieldCheck size={20}/><div><strong>Your collection, your choice.</strong><p>Set each collectible’s visibility in Vault. Your purchase costs and portfolio value are never published automatically.</p></div></div><button className="button" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save preferences'}</button></form></div></main>}
