'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeftIcon as ArrowLeft, ArrowSquareOutIcon as ArrowSquareOut, CalendarIcon as Calendar, StackIcon as Layers3} from '@phosphor-icons/react';
import {createClient} from '@/utils/supabase/client';
import {CardArt} from './card-art';
import {displayCardName} from './card-name';
import type {Card} from '@/packages/card-data/catalog';
import {isPlayableSet} from '@/packages/domain/release-availability';

type SetRow={external_set_id:string;name:string;set_kind:string;release_date:string|null;description:string|null;official_url:string|null;product_image_url:string|null};
type PrintingRow={id:string;set_code:string;set_name:string;language:string;rarity:string|null;printing_code:string|null;card_image_url:string|null;tcg_card_assets?:Array<{kind:string;object_key:string}>;tcg_card_identities:{code:string;name:string;color:string;card_type:Card['type'];cost:number;power:number;effect_text:string}};
function toCard(row:PrintingRow):Card{const identity=row.tcg_card_identities;return{id:row.id,code:identity.code,name:displayCardName(identity.name,identity.code),color:identity.color,type:identity.card_type,cost:identity.cost,power:identity.power,rarity:row.rarity??'',art:0,effect:identity.effect_text,imageUrl:row.card_image_url??undefined,imageSource:'external',setCode:row.set_code,language:row.language,printingCode:row.printing_code??undefined,assetPath:row.tcg_card_assets?.find(asset=>asset.kind==='small')?.object_key};}

export function SetDetail({code}:{code:string}){const [set,setSet]=useState<SetRow>();const [cards,setCards]=useState<Card[]>([]);const available=isPlayableSet(code);useEffect(()=>{if(!available)return;let live=true;const client=createClient();Promise.all([client.from('tcg_sets').select('external_set_id,name,set_kind,release_date,description,official_url,product_image_url').eq('external_set_id',code).maybeSingle(),client.from('tcg_card_printings').select('id,set_code,set_name,language,rarity,printing_code,card_image_url,tcg_card_assets(kind,object_key),tcg_card_identities!inner(code,name,color,card_type,cost,power,effect_text)').eq('set_code',code).eq('language','EN').not('card_image_url','is',null).limit(120)]).then(([setResult,cardResult])=>{if(!live)return;setSet((setResult.data??undefined) as SetRow|undefined);const unique=new Map<string,Card>();for(const row of (cardResult.data??[]) as unknown as PrintingRow[]){const card=toCard(row);if(!unique.has(card.code))unique.set(card.code,card);}setCards([...unique.values()]);});return()=>{live=false};},[available,code]);if(!available)return <main className="set-detail page"><Link href="/sets" className="back-link"><ArrowLeft size={16}/>Set archive</Link><header className="set-detail-hero"><div><p>Set archive</p><h1>{code} is being prepared.</h1><p className="set-detail-description">This release is unavailable until its card data and rules have been completed.</p></div></header></main>;const title=set?.name||cards[0]?.setCode||code;return <main className="set-detail page"><Link href="/sets" className="back-link"><ArrowLeft size={16}/>Set archive</Link><header className="set-detail-hero"><div><p>Set information</p><h1>{title}</h1><span>{code}{set?.set_kind&&<> · {set.set_kind}</>}</span>{set?.description&&<p className="set-detail-description">{set.description}</p>}<div className="set-detail-meta">{set?.release_date&&<span><Calendar size={15}/>{new Intl.DateTimeFormat('en',{year:'numeric',month:'long',day:'numeric'}).format(new Date(`${set.release_date}T00:00:00`))}</span>}<span><Layers3 size={15}/>{cards.length} cards</span>{set?.official_url&&<a href={set.official_url} target="_blank" rel="noreferrer">Official set page <ArrowSquareOut size={14}/></a>}</div></div>{set?.product_image_url&&<img src={set.product_image_url} alt=""/>}</header><section className="set-detail-cards" aria-label={`${title} cards`}>{!cards.length?<p>Loading set cards…</p>:cards.map(card=><Link key={card.id} href={`/cards/${card.code}?lang=${card.language}`}><CardArt card={card}/></Link>)}</section></main>;}
