'use client';

import {useEffect, useMemo, useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowUpRightIcon as ArrowUpRight, MagnifyingGlassIcon as Search, XIcon as X} from '@phosphor-icons/react';
import {createClient} from '@/utils/supabase/client';
import {CardArt} from './card-art';
import {displayCardName} from './card-name';
import {DepthCarousel} from './depth-carousel';
import type {Card} from '@/packages/card-data/catalog';
import {isPlayableSet} from '@/packages/domain/release-availability';

type Row={id:string;set_code:string;set_name:string;card_image_url:string|null;rarity:string|null;variant:string|null;printing_code:string|null;language:string;tcg_card_assets?:Array<{kind:string;object_key:string}>;tcg_card_identities:{code:string;name:string;color:string;card_type:Card['type'];cost:number;power:number;effect_text:string}};
type Release={code:string;name:string;count:number;cards:Card[]};
type SetFamily='all'|'OP'|'EB'|'ST'|'other';
const featuredReleaseOrder=['OP-17','ST-30','ST-29'];
function rank(code:string){const featured=featuredReleaseOrder.indexOf(code.toUpperCase());if(featured>=0)return 1_000_000-featured;const m=code.toUpperCase().match(/^(OP|EB|ST|PRB)[-_ ]?0*(\d+)/);return m?(m[1]==='OP'?600:m[1]==='EB'?500:m[1]==='ST'?400:300)*1000+Number(m[2]):0}
function family(code:string):Exclude<SetFamily,'all'>{const prefix=code.toUpperCase().match(/^[A-Z]+/)?.[0]??'other';return prefix==='OP'||prefix==='EB'||prefix==='ST'?prefix:'other'}
function rarityScore(row:Row){const rarity=(row.rarity??'').toUpperCase();const base=rarity==='SP'?100:rarity==='SEC'?90:rarity==='L'?80:rarity==='SR'?70:rarity==='R'?50:rarity==='UC'?30:rarity==='C'?20:rarity==='PR'?65:10;return base+(/parallel|alternate|alt.?art|_p\d+/i.test(row.variant??'')?8:0)}
function card(row:Row):Card{const i=row.tcg_card_identities;return{id:row.id,code:i.code,name:displayCardName(i.name,i.code),color:i.color,type:i.card_type,cost:i.cost,power:i.power,rarity:row.rarity??'',art:0,effect:i.effect_text,imageUrl:row.card_image_url??undefined,imageSource:'external',setCode:row.set_code,language:row.language,printingCode:row.printing_code??i.code,assetPath:row.tcg_card_assets?.find(asset=>asset.kind==='small')?.object_key}}
function ReleaseTile({release}:{release:Release}){const router=useRouter();return <article className="set-release"><header><div><span>{release.code}</span><h3>{release.name}</h3></div><small>{release.count} cards</small></header><DepthCarousel className="set-card-carousel" label={`${release.code} featured cards`} items={release.cards.map(item=>({id:item.id,label:`Open ${item.name}`,onSelect:()=>router.push(`/cards/${item.code}?lang=${item.language}`),content:<CardArt card={item}/>}))}/><Link href={`/sets/${encodeURIComponent(release.code)}`} className="set-all-link">View all {release.code} cards <ArrowUpRight size={15}/></Link></article>}

export function SetsExperience({compact=false}:{compact?:boolean}){
  const [rows,setRows]=useState<Row[]>([]);const [query,setQuery]=useState('');const [setFamily,setSetFamily]=useState<SetFamily>('all');
  useEffect(()=>{let live=true;const load=async()=>{try{const client=createClient();const all:Row[]=[];for(let from=0;;from+=1000){const {data,error}=await client.from('tcg_card_printings').select('id,set_code,set_name,card_image_url,rarity,variant,printing_code,language,tcg_card_assets(kind,object_key),tcg_card_identities!inner(code,name,color,card_type,cost,power,effect_text)').eq('language','EN').not('card_image_url','is',null).range(from,from+999);if(error||!data)break;all.push(...(data as unknown as Row[]).filter(row=>isPlayableSet(row.set_code)));if(data.length<1000)break}if(live)setRows(all)}catch(err){console.warn('Failed to load sets:',err)}};void load();return()=>{live=false}},[]);
  const sets=useMemo<Release[]>(()=>{const groups=new Map<string,Row[]>();rows.forEach(row=>groups.set(row.set_code,[...(groups.get(row.set_code)??[]),row]));return [...groups.entries()].map(([code,cards])=>{const bestByIdentity=new Map<string,Row>();for(const printing of [...cards].sort((a,b)=>rarityScore(b)-rarityScore(a)||a.id.localeCompare(b.id))){if(!bestByIdentity.has(printing.tcg_card_identities.code))bestByIdentity.set(printing.tcg_card_identities.code,printing)}return {code,name:cards[0].set_name,count:new Set(cards.map(item=>item.tcg_card_identities.code)).size,cards:[...bestByIdentity.values()].slice(0,4).map(card)}}).sort((a,b)=>rank(b.code)-rank(a.code))},[rows]);
  const visible=useMemo(()=>sets.filter(set=>(setFamily==='all'||family(set.code)===setFamily)&&`${set.code} ${set.name}`.toLowerCase().includes(query.trim().toLowerCase())),[sets,query,setFamily]);
  const shown=compact?sets.slice(0,6):visible;
  return <section className={compact?'home-sets home-reveal':'sets-page page'}><div className={`section-heading${compact?'':' page-intro-surface'}`}><div><p className="eyebrow">SET ARCHIVE</p><h2>{compact?'Latest releases, up close.':'Every release, card by card.'}</h2><p>{compact?'Browse the standout cards in each release, then open its complete live card pool.':'Search by set name or code, filter the release family, then open the exact card pool.'}</p></div>{compact&&<Link className="text-action" href="/sets">View all sets <ArrowUpRight size={15}/></Link>}</div>{!compact&&<div className="sets-controls" aria-label="Set archive controls"><label><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Find a set by name or code"/></label><div className="sets-family" role="group" aria-label="Set family">{([['all','All releases'],['OP','Main sets'],['EB','Extra boosters'],['ST','Starter decks'],['other','Other releases']] as const).map(([value,label])=><button type="button" key={value} aria-pressed={setFamily===value} onClick={()=>setSetFamily(value)}>{label}</button>)}</div>{(query||setFamily!=='all')&&<button className="sets-clear" type="button" onClick={()=>{setQuery('');setSetFamily('all')}}><X size={14}/>Clear</button>}</div>}{!rows.length?<div className="sets-skeleton" aria-label="Loading sets"><i/><i/><i/></div>:<div className="set-release-grid">{shown.map(release=><ReleaseTile key={release.code} release={release}/>)}</div>}{!compact&&rows.length>0&&!shown.length&&<div className="sets-empty"><h2>No releases match that filter.</h2><button type="button" onClick={()=>{setQuery('');setSetFamily('all')}}>Reset set filters</button></div>}</section>
}
