import type {Metadata} from 'next';
import {LegalDocument,LegalSection} from '@/components/tcg/legal-document';
import {isIndonesianRequest} from '@/lib/locale';

export async function generateMetadata():Promise<Metadata>{const id=await isIndonesianRequest();const title=id?'Kebijakan Privasi':'Privacy Policy';const description=id?'Cara VivrePlay menggunakan informasi akun, koleksi, Market, dan analitik.':'How VivrePlay uses account, collection, Market, and analytics information.';return {title,description,alternates:{canonical:id?'/id/legal/privacy':'/legal/privacy',languages:{'en-US':'/legal/privacy','id-ID':'/id/legal/privacy'}},openGraph:{type:'article',title,description,url:id?'/id/legal/privacy':'/legal/privacy'}}}

export default async function PrivacyPage(){
  const id=await isIndonesianRequest();
  const sections:LegalSection[]=id?[
    {title:'Informasi yang kami simpan',body:<p>VivrePlay menyimpan informasi yang dibutuhkan untuk akun dan fitur yang Anda gunakan, seperti detail akun, deck tersimpan, entri Vault, listing, serta pesanan. Preferensi tampilan, bahasa, dan cookie dapat disimpan di browser.</p>},
    {title:'Deck Coach',body:<p>Saat Anda menggunakan Deck Coach, permintaan, bahasa, identitas akun bila tersedia, alamat IP, user-agent, model, dan hasil layanan dapat dicatat untuk keamanan, keandalan, dan administrasi.</p>},
    {title:'Analitik dan akuisisi',body:<p>Jika Anda menyetujui analitik opsional, VivrePlay memuat Google Analytics dan mencatat sesi landing untuk laporan akuisisi internal. Data dapat mencakup tag kampanye UTM dan ID klik iklan, path halaman landing, asal situs perujuk, ID sesi acak tab browser, serta kode negara yang diberikan Cloudflare. Laporan internal tidak menyimpan email, ID akun, atau alamat IP mentah. Catatan kunjungan mentah dihapus setelah 180 hari. Google Analytics tunduk pada praktik data Google sendiri. Jangan masukkan informasi pribadi ke tag kampanye atau ID klik.</p>},
    {title:'Cara informasi digunakan',body:<p>Informasi digunakan untuk menjalankan layanan, menyimpan pekerjaan Anda, mencegah penyalahgunaan, memproses fitur yang dipilih, dan memperbaiki keandalan. Kami tidak menjual informasi pribadi.</p>},
    {title:'Pembagian informasi',body:<p>Informasi hanya dibagikan bila dibutuhkan untuk fitur yang Anda pilih, memenuhi kewajiban hukum, atau melindungi layanan dan penggunanya. Listing publik menampilkan informasi yang Anda pilih untuk dicantumkan. Pembayaran checkout diproses oleh iPaymu sesuai kebijakan mereka.</p>},
    {title:'Pilihan dan permintaan Anda',body:<p>Anda dapat mengubah preferensi cookie dari footer. Untuk bertanya tentang data akun atau meminta bantuan terkait informasi Anda, hubungi <a href="mailto:support@vivreplay.com">support@vivreplay.com</a>.</p>},
    {title:'Pembaruan',body:<p>Kebijakan ini dapat diperbarui seiring perkembangan VivrePlay. Versi dan tanggal terbaru selalu tersedia di halaman ini.</p>},
  ]:[
    {title:'Information we store',body:<p>VivrePlay stores information needed for your account and the features you use, such as account details, saved decks, Vault entries, listings, and orders. Display, language, and cookie preferences may be stored in your browser.</p>},
    {title:'Deck Coach',body:<p>When you use Deck Coach, the request, chosen language, account identifier when available, IP address, user-agent, model, and service result may be recorded for security, reliability, and administration.</p>},
    {title:'Analytics and acquisition',body:<p>If you accept optional analytics, VivrePlay loads Google Analytics and records landing sessions for an internal acquisition report. This may include UTM campaign tags and advertising click IDs, landing-page path, referring-site origin, a random browser-tab session ID, and the country code provided by Cloudflare. The internal report does not store your email, account ID, or raw IP address. Raw visit records are deleted after 180 days. Google Analytics is subject to Google’s own data practices. Do not put personal information in campaign tags or click IDs.</p>},
    {title:'How we use information',body:<p>Information is used to operate the service, preserve your work, prevent misuse, provide features you choose, and improve reliability. We do not sell personal information.</p>},
    {title:'Sharing',body:<p>Information is shared only when needed to run a feature you choose, comply with a legal obligation, or protect the service and its users. Public listings show information you choose to publish. Checkout payments are processed by iPaymu under its own policies.</p>},
    {title:'Your choices and requests',body:<p>You can change cookie preferences in the footer. To ask about your account information or request help with it, contact <a href="mailto:support@vivreplay.com">support@vivreplay.com</a>.</p>},
    {title:'Updates',body:<p>This policy may change as VivrePlay develops. The current version and revision date are available on this page.</p>},
  ];
  return <LegalDocument id={id} title={id?'Kebijakan Privasi':'Privacy Policy'} description={id?'Cara VivrePlay menggunakan informasi akun, koleksi, Market, dan analitik.':'How VivrePlay uses account, collection, Market, and analytics information.'} lead={id?'Kami menggunakan informasi yang diperlukan untuk menyediakan layanan dan fitur pilihan Anda.':'We use the information needed to provide the service and the features you choose.'} sections={sections} updated="2 October 2026"/>;
}
