import {notFound} from 'next/navigation';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db} from '@/lib/server/store';
import {cardFor} from '@/packages/card-data/catalog';
import {CardArt} from '@/components/tcg/card-art';
import {SlabPhotos} from '@/components/tcg/slab-photos';
import {ShareButton} from '@/components/tcg/share';
export const dynamic='force-dynamic';
export const metadata={title:'Slab collection',robots:{index:false,follow:false}};
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const auth=await getChatGPTUser();const row=await db().prepare(`SELECT c.printing_id,c.visibility,g.grade,g.certification,g.verification_status,g.verification_source,pr.name AS provider,p.auth_subject FROM collectible_instances c JOIN graded_cards g ON g.instance_id=c.id JOIN grading_providers pr ON pr.id=g.provider_id JOIN profiles p ON p.id=c.owner_id WHERE c.id=? AND c.deleted_at IS NULL`).bind(id).first<{printing_id:string;visibility:string;grade:string;certification:string;verification_status:string;verification_source:string;provider:string;auth_subject:string}>();if(!row||row.visibility!=='public'&&row.auth_subject!==auth?.userId)notFound();const c=cardFor(row.printing_id)!;const photos=(await db().prepare('SELECT id,role FROM collectible_photos WHERE instance_id=?').bind(id).all<{id:string;role:string}>()).results;return <main className="page"><div className="detail-layout"><div className="detail-art"><div className="slab-label"><b>{row.provider}</b><strong>{row.grade}</strong><small>{row.certification}</small></div><CardArt card={c}/><p>Illustration only · See uploaded slab photos</p></div><div className="detail-info"><p className="eyebrow">UNIQUE COLLECTIBLE · {row.visibility}</p><h1>{c.name}</h1><div className="detail-stats"><div><small>GRADER</small><strong>{row.provider}</strong></div><div><small>GRADE</small><strong>{row.grade}</strong></div></div><div className="effect-block"><h3>Certification {row.certification}</h3><p>{row.verification_source} · {row.verification_status}</p></div><p className="notice mb-6">Certification details are user-entered and have not been verified by the platform or grading provider.</p><ShareButton title={`${c.name} · ${row.provider} ${row.grade}`} path={`/slabs/${id}`} privateEntity={row.visibility!=='public'}/><SlabPhotos id={id} photos={photos} owner={row.auth_subject===auth?.userId}/></div></div></main>}
