'use client';
import {useCallback,useEffect,useState} from 'react';

type Request={id:string;sellerId:string;seller:string;amount:number;currency:string;status:'REQUESTED'|'PROCESSING'|'PAID'|'FAILED';transactionReference:string|null;failureReason:string|null;createdAt:string;bank:{bankName:string;accountHolder:string;accountNumber:string}};
const money=(amount:number)=>new Intl.NumberFormat('en-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(amount);

export function PayoutManager(){
 const [requests,setRequests]=useState<Request[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [reference,setReference]=useState<Record<string,string>>({});const [reason,setReason]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/admin/payouts',{cache:'no-store'});const body=await response.json() as {requests?:Request[];error?:string};if(!response.ok)throw new Error(body.error||'Withdrawal requests could not be loaded.');setRequests(body.requests??[])}catch(cause){setError(cause instanceof Error?cause.message:'Withdrawal requests could not be loaded.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const update=async(request:Request,status:'PROCESSING'|'PAID'|'FAILED')=>{setBusy(request.id);setError('');try{const response=await fetch('/api/admin/payouts',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:request.id,status,transactionReference:reference[request.id],failureReason:reason[request.id]})});const body=await response.json() as {error?:string};if(!response.ok)throw new Error(body.error||'Withdrawal could not be updated.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'Withdrawal could not be updated.')}finally{setBusy('')}};
 return <section className="admin-payout-manager"><header><div><p className="eyebrow">MARKET PAYOUTS</p><h2>Withdrawal requests</h2><p>Review saved bank details, record transfers, and close requests.</p></div><button className="admin-refresh" type="button" onClick={()=>void load()} disabled={loading}>Refresh</button></header>{error&&<p className="admin-error" role="alert">{error}</p>}{loading&&!requests.length?<p role="status">Loading withdrawal requests…</p>:!requests.length?<p className="admin-payout-empty">No withdrawal requests yet.</p>:<div className="admin-payout-list">{requests.map(request=><article key={request.id}><div className="admin-payout-top"><div><small>{request.seller} · {new Date(request.createdAt.replace(' ','T')+'Z').toLocaleString()}</small><h3>{money(request.amount)}</h3></div><span className={`payout-status is-${request.status.toLowerCase()}`}>{request.status}</span></div><dl><div><dt>Bank</dt><dd>{request.bank.bankName}</dd></div><div><dt>Account holder</dt><dd>{request.bank.accountHolder}</dd></div><div><dt>Account number</dt><dd className="admin-payout-account">{request.bank.accountNumber}</dd></div><div><dt>Seller</dt><dd>{request.seller} ({request.sellerId})</dd></div></dl>{request.status==='REQUESTED'&&<button type="button" className="button" disabled={busy===request.id} onClick={()=>void update(request,'PROCESSING')}>{busy===request.id?'Saving…':'Mark as processing'}</button>}{request.status==='PROCESSING'&&<div className="admin-payout-actions"><label>Transfer reference<input value={reference[request.id]??request.transactionReference??''} onChange={event=>setReference(current=>({...current,[request.id]:event.target.value}))} maxLength={160}/></label><button type="button" className="button" disabled={busy===request.id||!(reference[request.id]??request.transactionReference)?.trim()} onClick={()=>void update(request,'PAID')}>{busy===request.id?'Saving…':'Mark as paid'}</button><label>Failure reason<input value={reason[request.id]??''} onChange={event=>setReason(current=>({...current,[request.id]:event.target.value}))} minLength={3} maxLength={500}/></label><button type="button" className="button secondary" disabled={busy===request.id||!(reason[request.id]??'').trim()} onClick={()=>void update(request,'FAILED')}>Mark failed</button></div>}</article>)}</div>}</section>
}
