import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const secret = process.env.SUPABASE_SECRET_KEY;
if (!url || !secret) throw new Error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY.');
const supabase = createClient(url, secret, { auth: { persistSession: false, autoRefreshToken: false } });
const bucket = 'tcg-card-images';
const concurrency = Math.max(1, Number(process.env.PARALLEL_CONCURRENCY || 8));
const maxSuffix = Math.max(1, Number(process.env.PARALLEL_MAX_SUFFIX || 12));
const wantedCodes = new Set((process.env.PARALLEL_CODES || '').split(',').map(value => value.trim().toUpperCase()).filter(Boolean));
const offset = Math.max(0, Number(process.env.PARALLEL_OFFSET || 0));
const limit = Math.max(0, Number(process.env.PARALLEL_LIMIT || 0));
const imageVariants = [['thumb', 180, 72], ['small', 420, 78], ['large', 960, 84]] as const;

type Row = { id: string; identity_id: string; language: string; set_id: string | null; set_code: string; set_name: string; rarity: string | null; source_kind: string | null; life: number | null; sub_types: string | null; counter_amount: number | null; attribute: string | null; source_payload: Record<string, unknown> | null; tcg_card_identities: { code: string } | { code: string }[] };
type Candidate = { base: Row; code: string; language: string; suffix: number; folder: string; sourceUrl: string };
const identity = (row: Row) => Array.isArray(row.tcg_card_identities) ? row.tcg_card_identities[0] : row.tcg_card_identities;
const setSlug = (code: string) => code.toUpperCase().replaceAll('-', '');

async function rows() { const all: Row[] = []; for (let from = 0;; from += 1000) { const { data, error } = await supabase.from('tcg_card_printings').select('id,identity_id,language,set_id,set_code,set_name,rarity,source_kind,life,sub_types,counter_amount,attribute,source_payload,tcg_card_identities!inner(code)').eq('variant', 'Standard').in('language', ['EN', 'JP']).range(from, from + 999); if (error) throw error; all.push(...data as unknown as Row[]); if (data.length < 1000) break; } const unique = new Map<string, Row>(); for (const row of all) { const code = identity(row)?.code?.toUpperCase(); const key = `${row.identity_id}:${row.language}`; if (code && (!wantedCodes.size || wantedCodes.has(code)) && !unique.has(key)) unique.set(key, row); } const scoped = [...unique.values()].sort((a, b) => identity(a).code.localeCompare(identity(b).code)); return limit ? scoped.slice(offset, offset + limit) : scoped.slice(offset); }
async function fetchImage(url: string) { try { const response = await fetch(url, { headers: { accept: 'image/webp,image/*;q=0.8' }, signal: AbortSignal.timeout(15_000) }); return response.ok ? Buffer.from(await response.arrayBuffer()) : null; } catch { return null; } }
async function bounded<T, R>(items: T[], fn: (item: T) => Promise<R>) { const results: R[] = []; let cursor = 0; let complete = 0; await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, async () => { while (cursor < items.length) { const index = cursor++; results[index] = await fn(items[index]); complete++; if (complete === items.length || complete % 100 === 0) console.log(JSON.stringify({ progress: complete, total: items.length })); } })); return results; }
function candidates(base: Row) { const code = identity(base).code.toUpperCase(); const primary = code.split('-')[0]; const folders = [...new Set([primary, 'PROMO'])]; return Array.from({ length: maxSuffix }, (_, i) => i + 1).flatMap(suffix => folders.map(folder => ({ base, code, language: base.language, suffix, folder, sourceUrl: `https://cards.oplaytcg.com/${folder}/${base.language.toLowerCase()}/small/${code}_p${suffix}.webp` }))); }
async function store(candidate: Candidate) { const source = await fetchImage(candidate.sourceUrl); if (!source) return null; const printingCode = `${candidate.code}_p${candidate.suffix}`; const root = `one-piece/${setSlug(candidate.base.set_code)}/${candidate.language.toLowerCase()}`; const assets: Record<string, string> = {}; for (const [kind, width, quality] of imageVariants) { const body = await sharp(source).rotate().resize({ width, withoutEnlargement: true }).webp({ quality, effort: 4 }).toBuffer(); const objectKey = `${root}/${kind}/${printingCode}.webp`; const { error } = await supabase.storage.from(bucket).upload(objectKey, body, { contentType: 'image/webp', cacheControl: '31536000', upsert: true }); if (error) throw new Error(error.message); assets[kind] = objectKey; }
  const variant = `Alt art · ${candidate.folder} · p${candidate.suffix}`;
  const payload = { identity_id: candidate.base.identity_id, language: candidate.language, set_id: candidate.base.set_id, set_code: candidate.base.set_code, set_name: candidate.base.set_name, printing_code: printingCode, rarity: candidate.base.rarity, variant, source_kind: candidate.base.source_kind, life: candidate.base.life, sub_types: candidate.base.sub_types, counter_amount: candidate.base.counter_amount, attribute: candidate.base.attribute, card_image_id: printingCode, card_image_url: candidate.sourceUrl, source_payload: { ...(candidate.base.source_payload ?? {}), alt_art: true, oplay_folder: candidate.folder, oplay_variant: printingCode, reconciled_parallel: true } };
  const { error: printingError } = await supabase.from('tcg_card_printings').upsert(payload, { onConflict: 'identity_id,language,set_code,variant' }); if (printingError) throw new Error(printingError.message);
  const { data: printing, error: lookupError } = await supabase.from('tcg_card_printings').select('id').eq('identity_id', candidate.base.identity_id).eq('language', candidate.language).eq('set_code', candidate.base.set_code).eq('variant', variant).maybeSingle(); if (lookupError || !printing) throw new Error(lookupError?.message ?? 'parallel row missing after upsert');
  const { error: assetError } = await supabase.from('tcg_card_assets').upsert(imageVariants.map(([kind, width]) => ({ printing_id: printing.id, kind, object_key: assets[kind], width })), { onConflict: 'printing_id,kind' }); if (assetError) throw new Error(assetError.message);
  await supabase.from('tcg_card_asset_sources').upsert({ printing_id: printing.id, source_type: 'oplaytcg', source_url: candidate.sourceUrl, rights_status: 'user_requested_import_pending_review', storage_path: assets.small, storage_variants: assets, stored_format: 'webp', approved_for_display: false, approved_for_storage: false }, { onConflict: 'source_url' });
  return { code: candidate.code, language: candidate.language, suffix: candidate.suffix, folder: candidate.folder };
}

const { data: run, error: runError } = await supabase.from('tcg_import_runs').insert({ source: 'oplaytcg-parallel-reconcile', status: 'running' }).select('id').single();
if (runError) throw runError;
try { const bases = await rows(); const allCandidates = bases.flatMap(candidates); console.log(JSON.stringify({ bases: bases.length, candidates: allCandidates.length, maxSuffix, offset, limit, scoped: wantedCodes.size > 0 })); const results = await bounded(allCandidates, async candidate => { try { return await store(candidate); } catch (error) { return { error: error instanceof Error ? error.message : 'store failed', code: candidate.code, language: candidate.language, suffix: candidate.suffix }; } }); const found = results.filter(result => result && !('error' in result)); const errors = results.filter(result => result && 'error' in result); const summary = { bases: bases.length, candidates: allCandidates.length, discovered: found.length, failures: errors.length, errors: errors.slice(0, 20) }; await supabase.from('tcg_import_runs').update({ status: errors.length ? 'completed_with_gaps' : 'completed', summary, completed_at: new Date().toISOString() }).eq('id', run.id); console.log(JSON.stringify(summary, null, 2)); } catch (error) { await supabase.from('tcg_import_runs').update({ status: 'failed', summary: { error: error instanceof Error ? error.message : 'unknown' }, completed_at: new Date().toISOString() }).eq('id', run.id); throw error; }
