import {createClient} from '@supabase/supabase-js';
import sharp from 'sharp';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const secret=process.env.SUPABASE_SECRET_KEY;
if(!url||!secret) throw new Error('Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY.');
const supabase=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});
const bucket='tcg-card-images';
const concurrency=Math.max(1,Number(process.env.STANDARD_RECONCILE_CONCURRENCY||8));
const variants=[['thumb',180,72],['small',420,78],['large',960,84]] as const;
type Identity={code:string};
type Printing={id:string;identity_id:string;language:string;set_id:string|null;set_code:string;set_name:string;rarity:string|null;variant:string|null;source_kind:string|null;life:number|null;sub_types:string|null;counter_amount:number|null;attribute:string|null;source_payload:Record<string,unknown>|null;card_image_url:string|null;tcg_card_identities:Identity|Identity[]};
type Repair={seed:Printing;code:string;language:string;reason:'missing-row'|'wrong-art'};

async function allRows(){const rows:Printing[]=[];for(let from=0;;from+=1000){const {data,error}=await supabase.from('tcg_card_printings').select('id,identity_id,language,set_id,set_code,set_name,rarity,variant,source_kind,life,sub_types,counter_amount,attribute,source_payload,card_image_url,tcg_card_identities!inner(code)').in('language',['EN','JP']).range(from,from+999);if(error)throw error;rows.push(...data as unknown as Printing[]);if(data.length<1000)return rows;}}
const identity=(printing:Printing)=>Array.isArray(printing.tcg_card_identities)?printing.tcg_card_identities[0]:printing.tcg_card_identities;
async function bounded<T,R>(items:T[],fn:(item:T)=>Promise<R>){const output:R[]=[];let cursor=0;let complete=0;await Promise.all(Array.from({length:Math.min(concurrency,items.length)},async()=>{while(cursor<items.length){const index=cursor++;output[index]=await fn(items[index]);complete++;if(complete===items.length||complete%5===0)console.log(JSON.stringify({progress:complete,total:items.length}));}}));return output;}
async function fetchImage(source:string){try{const response=await fetch(source,{headers:{accept:'image/webp,image/*;q=0.8'},signal:AbortSignal.timeout(20_000)});return response.ok?Buffer.from(await response.arrayBuffer()):null;}catch{return null;}}
function sourceCandidates(code:string,language:string){const primary=code.split('-')[0].toUpperCase();return [...new Set([primary,'PROMO'])].map(folder=>`https://cards.oplaytcg.com/${folder}/${language.toLowerCase()}/small/${code}.webp`);}
const setSlug=(setCode:string)=>setCode.toUpperCase().replaceAll('-','');
async function repair(item:Repair){let sourceUrl='';let source:Buffer|null=null;for(const candidate of sourceCandidates(item.code,item.language)){source=await fetchImage(candidate);if(source){sourceUrl=candidate;break;}}if(!source)return {ok:false,item,reason:'source unavailable'};const pathRoot=`one-piece/${setSlug(item.seed.set_code)}/${item.language.toLowerCase()}`;const assets=[] as Array<{kind:string;object_key:string;width:number}>;for(const [kind,width,quality] of variants){const body=await sharp(source).rotate().resize({width,withoutEnlargement:true}).webp({quality,effort:4}).toBuffer();const objectKey=`${pathRoot}/${kind}/${item.code}.webp`;const {error}=await supabase.storage.from(bucket).upload(objectKey,body,{contentType:'image/webp',cacheControl:'31536000',upsert:true});if(error)return {ok:false,item,reason:error.message};assets.push({kind,object_key:objectKey,width});}
  const row={identity_id:item.seed.identity_id,language:item.language,set_id:item.seed.set_id,set_code:item.seed.set_code,set_name:item.seed.set_name,printing_code:item.code,rarity:item.seed.rarity,variant:'Standard',source_kind:item.seed.source_kind,life:item.seed.life,sub_types:item.seed.sub_types,counter_amount:item.seed.counter_amount,attribute:item.seed.attribute,card_image_id:item.code,card_image_url:sourceUrl,source_payload:{...(item.seed.source_payload??{}),reconciled_standard:true,image_source:'oplaytcg'}};
  const {error:printingError}=await supabase.from('tcg_card_printings').upsert(row,{onConflict:'identity_id,language,set_code,variant'});if(printingError)return {ok:false,item,reason:printingError.message};
  const {data:printing,error:lookupError}=await supabase.from('tcg_card_printings').select('id').eq('identity_id',item.seed.identity_id).eq('language',item.language).eq('set_code',item.seed.set_code).eq('variant','Standard').maybeSingle();if(lookupError||!printing)return {ok:false,item,reason:lookupError?.message??'standard row not found'};
  const {error:assetError}=await supabase.from('tcg_card_assets').upsert(assets.map(asset=>({...asset,printing_id:printing.id})),{onConflict:'printing_id,kind'});if(assetError)return {ok:false,item,reason:assetError.message};
  await supabase.from('tcg_card_asset_sources').upsert({printing_id:printing.id,source_type:'oplaytcg',source_url:sourceUrl,rights_status:'user_requested_import_pending_review',storage_path:assets.find(asset=>asset.kind==='small')?.object_key,storage_variants:Object.fromEntries(assets.map(asset=>[asset.kind,asset.object_key])),stored_format:'webp',approved_for_display:false,approved_for_storage:false},{onConflict:'source_url'});
  return {ok:true,item};
}

const {data:run,error:runError}=await supabase.from('tcg_import_runs').insert({source:'oplaytcg-standard-reconcile',status:'running'}).select('id').single();
if(runError)throw runError;
try{const rows=await allRows();const groups=new Map<string,Printing[]>();for(const row of rows){const key=`${row.identity_id}:${row.language}`;const group=groups.get(key)??[];group.push(row);groups.set(key,group);}const repairs:Repair[]=[];for(const group of groups.values()){const code=identity(group[0])?.code?.toUpperCase();if(!code)continue;const standard=group.find(row=>/^(standard|base)$/i.test(row.variant??''));if(!standard)repairs.push({seed:group[0],code,language:group[0].language,reason:'missing-row'});else if(!standard.card_image_url||/_p\d+\.webp/i.test(standard.card_image_url))repairs.push({seed:standard,code,language:standard.language,reason:'wrong-art'});}console.log(JSON.stringify({groups:groups.size,repairs:repairs.length}));const results=await bounded(repairs,repair);const failures=results.filter(result=>!result.ok);const summary={checked:repairs.length,repaired:results.length-failures.length,failed:failures.length,failures:failures.slice(0,20).map(result=>({code:result.item.code,language:result.item.language,reason:result.reason}))};const {error:updateError}=await supabase.from('tcg_import_runs').update({status:'completed',summary,completed_at:new Date().toISOString()}).eq('id',run.id);if(updateError)throw updateError;console.log(JSON.stringify(summary,null,2));if(failures.length)process.exitCode=1;}catch(error){await supabase.from('tcg_import_runs').update({status:'failed',summary:{error:error instanceof Error?error.message:'unknown'},completed_at:new Date().toISOString()}).eq('id',run.id);throw error;}
