import {createClient} from '@supabase/supabase-js';

type ParseCard = {card_code?:unknown; card_name?:unknown; price?:unknown; card_url?:unknown};
type Printing = {id:string;printing_code:string|null;variant:string|null;language:string;tcg_card_identities:{code:string}};
type SourceRecord = {id:string;source_key:string};
const endpoint='https://api.parse.bot/scraper/1d31f593-ebaf-4791-a047-2c9751946cee/get_all_cards';
const key=process.env.PARSE_API_KEY;const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const serviceRole=process.env.SUPABASE_SERVICE_ROLE_KEY;
if(!key||!url||!serviceRole)throw new Error('PARSE_API_KEY, NEXT_PUBLIC_SUPABASE_URL, and SUPABASE_SERVICE_ROLE_KEY are required.');
const argument=(name:string)=>{const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined};const version=argument('--version');if(!version)throw new Error('Use --version op16 [--page 1].');const page=argument('--page')??'1';
let response:Response|undefined;for(let attempt=0;attempt<5;attempt++){response=await fetch(`${endpoint}?${new URLSearchParams({version,page})}`,{headers:{'X-API-Key':key}});if(response.ok||response.status!==429)break;await new Promise(resolve=>setTimeout(resolve,Math.min(15000,2500*(attempt+1))));}if(!response?.ok)throw new Error(`Parse request failed (${response?.status??'network'}).`);const payload=await response.json() as {data?:{cards?:ParseCard[]};cards?:ParseCard[]};const cards=payload.data?.cards??payload.cards??[];
const supabase=createClient(url,serviceRole);const printings:Printing[]=[];for(let from=0;;from+=1000){const {data,error}=await supabase.from('tcg_card_printings').select('id,printing_code,variant,language,tcg_card_identities!inner(code)').in('language',['JP','EN']).range(from,from+999);if(error)throw error;printings.push(...((data??[]) as unknown as Printing[]));if((data??[]).length<1000)break;}
const normalize=(value:string)=>value.trim().toUpperCase().replace(/\s+/g,'');const isStandard=(printing:Printing)=>/^(standard|base)$/i.test(printing.variant??'standard')&&(!printing.printing_code||normalize(printing.printing_code)===normalize(printing.tcg_card_identities.code));const parallel=(card:ParseCard)=>/パラレル|parallel/i.test(typeof card.card_name==='string'?card.card_name:'');const parallelOrder=(printing:Printing)=>Number(printing.printing_code?.match(/_p(\d+)$/i)?.[1]??999);const observedAt=new Date().toISOString();const records=cards.filter(card=>typeof card.card_url==='string'&&card.card_url.startsWith('https://yuyu-tei.jp/')).map(card=>({source:'yuyutei',source_key:card.card_url as string,payload:card,observed_at:observedAt}));
for(let start=0;start<records.length;start+=200){const {error}=await supabase.from('tcg_source_records').upsert(records.slice(start,start+200),{onConflict:'source,source_key,observed_at'});if(error)throw error;}
const sourceByUrl=new Map<string,string>();for(let start=0;;start+=1000){const {data,error}=await supabase.from('tcg_source_records').select('id,source_key').eq('source','yuyutei').eq('observed_at',observedAt).range(start,start+999);if(error)throw error;for(const row of (data??[]) as SourceRecord[])sourceByUrl.set(row.source_key,row.id);if((data??[]).length<1000)break;}
const observations=[] as Array<{printing_id:string;source:string;source_kind:string;amount:number;currency:string;observed_at:string;source_record_id?:string}>;const unmatched:string[]=[];
const observation=(printing:Printing,card:ParseCard)=>({printing_id:printing.id,source:'yuyutei',source_kind:'market_price',amount:Number(card.price),currency:'JPY',observed_at:observedAt,source_record_id:typeof card.card_url==='string'?sourceByUrl.get(card.card_url):undefined});
const cardsByCode=new Map<string,ParseCard[]>();for(const card of cards){const code=typeof card.card_code==='string'?normalize(card.card_code):'';const amount=Number(card.price);if(!code||!Number.isFinite(amount)||amount<0)continue;cardsByCode.set(code,[...(cardsByCode.get(code)??[]),card]);}
for(const [code,sourceRows] of cardsByCode){const matching=printings.filter(printing=>normalize(printing.tcg_card_identities.code)===code);const candidates=matching.some(printing=>printing.language==='JP')?matching.filter(printing=>printing.language==='JP'):matching.filter(printing=>printing.language==='EN');const standard=candidates.find(isStandard);const alternates=candidates.filter(printing=>!isStandard(printing)).sort((a,b)=>parallelOrder(a)-parallelOrder(b));const sourceStandard=sourceRows.find(card=>!parallel(card));const sourceAlternates=sourceRows.filter(parallel);if(sourceStandard&&standard)observations.push(observation(standard,sourceStandard));else if(sourceStandard)unmatched.push(code);sourceAlternates.forEach((card,index)=>{const printing=alternates[index];if(!printing){unmatched.push(code);return}observations.push(observation(printing,card));});}
const uniqueObservations=[...new Map(observations.map(observation=>[observation.printing_id,observation])).values()];
for(let start=0;start<uniqueObservations.length;start+=200){const {error}=await supabase.from('tcg_price_observations').upsert(uniqueObservations.slice(start,start+200),{onConflict:'printing_id,source,source_kind,observed_at'});if(error)throw error;}
console.log(JSON.stringify({version,page,received:cards.length,imported:uniqueObservations.length,linked:uniqueObservations.filter(item=>item.source_record_id).length,unmatched},null,2));
