import type {Metadata} from 'next';
import {LegalDocument,LegalSection} from '@/components/tcg/legal-document';
import {isIndonesianRequest} from '@/lib/locale';

export async function generateMetadata():Promise<Metadata>{const id=await isIndonesianRequest();const title=id?'Syarat & Ketentuan':'Terms & Conditions';const description=id?'Ketentuan penggunaan VivrePlay, fitur komunitas, dan Market.':'Terms for using VivrePlay, its card tools, community features, and Market.';return {title,description,alternates:{canonical:id?'/id/legal/terms':'/legal/terms',languages:{'en-US':'/legal/terms','id-ID':'/id/legal/terms'}},openGraph:{type:'article',title,description,url:id?'/id/legal/terms':'/legal/terms'}}}

export default async function TermsPage(){
  const id=await isIndonesianRequest();
  const sections:LegalSection[]=id?[
    {title:'1. Tentang VivrePlay',body:<p>VivrePlay menyediakan katalog kartu, pembuat deck, koleksi kartu, Arena simulasi, dan Market komunitas. Dengan mengakses atau menggunakan layanan ini, Anda menyetujui Syarat & Ketentuan ini. Jika tidak setuju, jangan gunakan layanan.</p>},
    {title:'2. Akun dan keamanan',body:<p>Berikan informasi akun yang benar, jaga kerahasiaan kredensial, dan segera beri tahu kami bila ada penggunaan tanpa izin. Anda bertanggung jawab atas aktivitas melalui akun Anda. Kami dapat membatasi akses bila diperlukan untuk melindungi pengguna, layanan, atau mematuhi hukum.</p>},
    {title:'3. Market dan transaksi',body:<><p>Market menghubungkan pengguna yang menawarkan kartu dengan pengguna yang ingin membelinya. Penjual bertanggung jawab atas kepemilikan, keaslian, kondisi, jumlah, harga, foto, dan keterangan kartu yang dicantumkan. Pembeli bertanggung jawab memeriksa detail listing sebelum membayar.</p><p>Checkout yang belum dibayar menahan kartu selama masa pembayaran yang ditampilkan, hingga 24 jam. Jika batas waktu berakhir tanpa pembayaran terkonfirmasi, pesanan ditutup dan kartu tersedia kembali. Pesanan masuk ke daftar penjual setelah pembayaran dikonfirmasi. Dana pesanan ditahan sampai pembeli mengonfirmasi penerimaan; hasil penjualan tersedia untuk diminta setelahnya. Pembeli yang mengalami masalah harus melaporkannya dari detail pesanan sebelum mengonfirmasi penerimaan. Kami meninjau laporan dan bukti yang tersedia, tetapi pengembalian dana atau hasil sengketa tidak otomatis dijamin. VivrePlay menyimpan status dan rincian pesanan, bukan nomor kartu atau kata sandi pembayaran.</p><p>Penjual wajib mengirim pesanan yang telah dibayar sesuai listing dan menyimpan bukti pengiriman. Pembeli harus memberikan alamat dan kontak penerima yang benar serta mengonfirmasi penerimaan hanya setelah pesanan tiba. Untuk transaksi yang diatur langsung di luar checkout VivrePlay, pembayaran dan pengiriman menjadi tanggung jawab para pihak.</p></>},
    {title:'4. Biaya, Market Pro, dan listing',body:<><p>Biaya dihitung dari subtotal kartu: pembeli akun Free membayar biaya layanan 0,75%, sedangkan anggota Market Pro membayar 0,5%. Biaya penjual adalah 1,5% untuk Free dan 0,75% untuk Pro. Ongkir dan biaya lain yang berlaku ditampilkan sebelum pembayaran; rincian pada halaman pesanan menjadi acuan untuk transaksi tersebut.</p><p>Satu Market Pro berlaku untuk aktivitas membeli dan menjual pada akun selama masa aktif yang ditampilkan saat checkout. Manfaat saat ini mencakup batas listing yang lebih tinggi, listing lebih lama, biaya layanan yang lebih rendah, dan dua voucher ongkir per bulan. Setiap voucher menanggung 50% tarif reguler hingga Rp5.000 untuk subtotal kartu minimal Rp200.000; voucher yang tidak digunakan tidak dibawa ke bulan berikutnya. Paket tidak diperpanjang otomatis kecuali checkout menyatakan sebaliknya. Pengembalian dana mengikuti Kebijakan Pengembalian Dana.</p></>},
    {title:'5. Perilaku dan konten',body:<p>Jangan menipu, memanipulasi harga atau transaksi, menyamar sebagai orang lain, mencantumkan barang yang tidak dimiliki, mengganggu layanan, atau mengunggah konten yang melanggar hukum maupun hak orang lain. Kami dapat menghapus konten dan membatasi akun yang melanggar ketentuan ini.</p>},
    {title:'6. Ketersediaan dan hak kekayaan intelektual',body:<p>Kami berupaya menjaga layanan tetap tersedia dan informasi tetap akurat, namun fitur dan katalog dapat berubah atau mengalami gangguan. Nama, ilustrasi kartu, merek, dan materi permainan adalah milik pemegang hak masing-masing; VivrePlay adalah proyek komunitas independen dan tidak berafiliasi dengan Bandai.</p>},
    {title:'7. Hukum dan perubahan ketentuan',body:<p>Ketentuan ini ditafsirkan menurut hukum Republik Indonesia. Kami dapat memperbaruinya untuk mencerminkan perubahan layanan, aturan, atau cara kerja transaksi. Versi terbaru dan tanggal pembaruan tersedia di halaman ini. Penggunaan berkelanjutan setelah pembaruan berarti Anda menerima versi terbaru.</p>},
  ]:[
    {title:'1. About VivrePlay',body:<p>VivrePlay provides a card catalog, deck builder, collection Vault, Arena simulator, and community Market. By accessing or using the service, you agree to these Terms & Conditions. If you do not agree, do not use the service.</p>},
    {title:'2. Accounts and security',body:<p>Keep your account information accurate, protect your credentials, and tell us promptly about unauthorized use. You are responsible for activity through your account. We may restrict access when needed to protect users or the service, or to comply with law.</p>},
    {title:'3. Market and transactions',body:<><p>Market connects users offering cards with users seeking to buy them. Sellers are responsible for ownership, authenticity, condition, quantity, price, images, and listing details. Buyers are responsible for checking a listing before paying.</p><p>An unpaid checkout reserves the cards for the payment window shown, up to 24 hours. If payment is not confirmed before the deadline, the order closes and the cards become available again. An order appears in the seller’s order list after the buyer’s payment is confirmed. Order funds are held until the buyer confirms delivery; sale proceeds can be requested for withdrawal after that. If there is a problem, the buyer should report it from the order details before confirming receipt. We review reports and available evidence, but refunds and dispute outcomes are not automatic or guaranteed. VivrePlay stores order and payment status, not full card numbers or payment passwords.</p><p>Sellers must ship paid orders as described and keep proof of shipment. Buyers must provide a correct delivery address and contact details, then confirm receipt only after the order arrives. For transactions arranged outside VivrePlay checkout, the parties handle payment and delivery themselves.</p></>},
    {title:'4. Fees, Market Pro, and listings',body:<><p>Fees are calculated on the card subtotal: Free buyers pay a 0.75% service fee and Market Pro buyers pay 0.5%. Seller fees are 1.5% for Free and 0.75% for Pro. Delivery and any other applicable charges are shown before payment; the order breakdown is the record for that transaction.</p><p>One Market Pro membership covers buying and selling on the account for the term shown at checkout. Current benefits include higher listing limits, longer listing periods, lower service fees, and two shipping vouchers per month. Each voucher covers 50% of regular delivery, up to Rp5,000, on orders with a card subtotal of at least Rp200,000. Unused vouchers do not roll over. The plan does not renew automatically unless checkout says otherwise. Refunds are governed by the Refund Policy.</p></>},
    {title:'5. Conduct and content',body:<p>Do not deceive users, manipulate prices or transactions, impersonate another person, list items you do not own, disrupt the service, or upload unlawful content or material that violates another person’s rights. We may remove content and restrict accounts that violate these terms.</p>},
    {title:'6. Availability and intellectual property',body:<p>We work to keep the service available and information accurate, but features and catalog data may change or experience interruptions. Card names, artwork, trademarks, and game materials belong to their respective owners; VivrePlay is an independent community project and is not affiliated with Bandai.</p>},
    {title:'7. Governing law and updates',body:<p>These terms are governed by the laws of the Republic of Indonesia. We may update them to reflect service, legal, or transaction changes. The current version and revision date appear on this page. Continued use after an update means you accept the current version.</p>},
  ];
  return <LegalDocument id={id} title={id?'Syarat & Ketentuan':'Terms & Conditions'} description={id?'Ketentuan penggunaan VivrePlay dan layanan Market.':'Terms for using VivrePlay and its Market service.'} lead={id?'Ketentuan ini menjelaskan aturan penggunaan akun, fitur, dan transaksi di VivrePlay.':'These terms explain how accounts, features, and transactions on VivrePlay work.'} sections={sections} updated="8 October 2026"/>;
}
