import type {Metadata} from 'next';
import {LegalDocument,LegalSection} from '@/components/tcg/legal-document';
import {isIndonesianRequest} from '@/lib/locale';

export async function generateMetadata():Promise<Metadata>{const id=await isIndonesianRequest();const title=id?'Syarat & Ketentuan':'Terms & Conditions';const description=id?'Ketentuan penggunaan VivrePlay, fitur komunitas, dan Market.':'Terms for using VivrePlay, its card tools, community features, and Market.';return {title,description,alternates:{canonical:id?'/id/legal/terms':'/legal/terms',languages:{'en-US':'/legal/terms','id-ID':'/id/legal/terms'}},openGraph:{type:'article',title,description,url:id?'/id/legal/terms':'/legal/terms'}}}

export default async function TermsPage(){
  const id=await isIndonesianRequest();
  const sections:LegalSection[]=id?[
    {title:'1. Tentang VivrePlay',body:<p>VivrePlay menyediakan katalog kartu, pembuat deck, koleksi kartu, Arena simulasi, dan Market komunitas. Dengan mengakses atau menggunakan layanan ini, Anda menyetujui Syarat & Ketentuan ini. Jika tidak setuju, jangan gunakan layanan.</p>},
    {title:'2. Akun dan keamanan',body:<p>Berikan informasi akun yang benar, jaga kerahasiaan kredensial, dan segera beri tahu kami bila ada penggunaan tanpa izin. Anda bertanggung jawab atas aktivitas melalui akun Anda. Kami dapat membatasi akses bila diperlukan untuk melindungi pengguna, layanan, atau mematuhi hukum.</p>},
    {title:'3. Market dan transaksi',body:<><p>Market menghubungkan pengguna yang menawarkan kartu dengan pengguna yang ingin membelinya. Penjual bertanggung jawab atas kepemilikan, keaslian, kondisi, jumlah, harga, foto, dan keterangan kartu yang dicantumkan. Pembeli bertanggung jawab memeriksa detail listing sebelum membayar.</p><p>Pesanan online hanya terbentuk ketika checkout tersedia dan pembayaran dikonfirmasi oleh iPaymu. Pembayaran diproses oleh iPaymu berdasarkan ketentuan dan kebijakan mereka. VivrePlay tidak menyimpan data lengkap kartu pembayaran Anda. Untuk transaksi yang disepakati langsung antar pengguna di luar checkout VivrePlay, pembayaran dan pengiriman diatur sendiri oleh para pihak.</p><p>Penjual wajib mengirimkan pesanan yang telah dibayar sesuai listing dan menyimpan bukti pengiriman. Pembeli harus memberikan alamat dan kontak penerima yang benar serta mengonfirmasi penerimaan hanya setelah pesanan tiba. Kami dapat membantu meneruskan laporan sengketa, tetapi tidak menjamin hasil sengketa atau keaslian barang yang tidak pernah kami periksa secara fisik.</p></>},
    {title:'4. Biaya, Market Pro, dan listing',body:<p>Biaya layanan, durasi listing, batas listing, dan manfaat Market Pro ditampilkan sebelum Anda menerbitkan listing atau membeli paket. Kebijakan Market yang berlaku dapat berubah dan ditampilkan pada halaman terkait. Satu paket Market Pro berlaku untuk aktivitas membeli dan menjual pada akun selama periode yang dibeli. Voucher pengiriman memiliki batas jumlah, nilai, dan minimum belanja yang ditampilkan di halaman paket. Paket tidak otomatis diperpanjang kecuali halaman checkout secara jelas menyatakan sebaliknya. Pengembalian dana mengikuti Kebijakan Pengembalian Dana.</p>},
    {title:'5. Perilaku dan konten',body:<p>Jangan menipu, memanipulasi harga atau transaksi, menyamar sebagai orang lain, mencantumkan barang yang tidak dimiliki, mengganggu layanan, atau mengunggah konten yang melanggar hukum maupun hak orang lain. Kami dapat menghapus konten dan membatasi akun yang melanggar ketentuan ini.</p>},
    {title:'6. Ketersediaan dan hak kekayaan intelektual',body:<p>Kami berupaya menjaga layanan tetap tersedia dan informasi tetap akurat, namun fitur dan katalog dapat berubah atau mengalami gangguan. Nama, ilustrasi kartu, merek, dan materi permainan adalah milik pemegang hak masing-masing; VivrePlay adalah proyek komunitas independen dan tidak berafiliasi dengan Bandai.</p>},
    {title:'7. Hukum dan perubahan ketentuan',body:<p>Ketentuan ini ditafsirkan menurut hukum Republik Indonesia. Kami dapat memperbaruinya untuk mencerminkan perubahan layanan, aturan, atau cara kerja transaksi. Versi terbaru dan tanggal pembaruan tersedia di halaman ini. Penggunaan berkelanjutan setelah pembaruan berarti Anda menerima versi terbaru.</p>},
  ]:[
    {title:'1. About VivrePlay',body:<p>VivrePlay provides a card catalog, deck builder, collection Vault, Arena simulator, and community Market. By accessing or using the service, you agree to these Terms & Conditions. If you do not agree, do not use the service.</p>},
    {title:'2. Accounts and security',body:<p>Keep your account information accurate, protect your credentials, and tell us promptly about unauthorized use. You are responsible for activity through your account. We may restrict access when needed to protect users or the service, or to comply with law.</p>},
    {title:'3. Market and transactions',body:<><p>Market connects users offering cards with users seeking to buy them. Sellers are responsible for ownership, authenticity, condition, quantity, price, images, and listing details. Buyers are responsible for checking a listing before paying.</p><p>An online order is formed only when checkout is available and iPaymu confirms payment. iPaymu processes payment under its own terms and policies. VivrePlay does not store your full payment-card details. For transactions arranged directly between users outside VivrePlay checkout, the parties arrange payment and delivery themselves.</p><p>Sellers must ship paid orders as described and keep proof of shipment. Buyers must provide a correct delivery address and contact details, and confirm receipt only after the order arrives. We may help route a dispute report, but cannot guarantee its outcome or verify items we have not physically inspected.</p></>},
    {title:'4. Fees, Market Pro, and listings',body:<p>Service fees, listing duration, listing caps, and Market Pro benefits are shown before you publish a listing or purchase a plan. Current Market policy may change and is displayed on the relevant page. One Market Pro plan covers buying and selling on the account for the purchased period. Delivery vouchers have monthly quantity, value, and minimum-spend limits shown on the plan page. The plan does not renew automatically unless checkout clearly says otherwise. Refunds are governed by the Refund Policy.</p>},
    {title:'5. Conduct and content',body:<p>Do not deceive users, manipulate prices or transactions, impersonate another person, list items you do not own, disrupt the service, or upload unlawful content or material that violates another person’s rights. We may remove content and restrict accounts that violate these terms.</p>},
    {title:'6. Availability and intellectual property',body:<p>We work to keep the service available and information accurate, but features and catalog data may change or experience interruptions. Card names, artwork, trademarks, and game materials belong to their respective owners; VivrePlay is an independent community project and is not affiliated with Bandai.</p>},
    {title:'7. Governing law and updates',body:<p>These terms are governed by the laws of the Republic of Indonesia. We may update them to reflect service, legal, or transaction changes. The current version and revision date appear on this page. Continued use after an update means you accept the current version.</p>},
  ];
  return <LegalDocument id={id} title={id?'Syarat & Ketentuan':'Terms & Conditions'} description={id?'Ketentuan penggunaan VivrePlay dan layanan Market.':'Terms for using VivrePlay and its Market service.'} lead={id?'Ketentuan ini menjelaskan aturan penggunaan akun, fitur, dan transaksi di VivrePlay.':'These terms explain how accounts, features, and transactions on VivrePlay work.'} sections={sections} updated="2 October 2026"/>;
}
