'use client';

import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {ArrowBendUpLeft,ArrowLeft,CheckCircle,PaperPlaneRight,Camera,UploadSimple,XCircle} from '@phosphor-icons/react';
import {toast} from 'sonner';
import {PushNotificationPrompt} from '@/components/tcg/push-notification-settings';

type Language='EN'|'ID';
type Round={id:string;parentOfferId:string|null;actorId:string;type:string;items:Array<{printingId:string;quantity:number;unitAmount?:number;card?:{name:string;code:string;imageUrl:string|null}}> ;amount:number;currency:string;status:string;createdAt:string;expiresAt:string|null;actorName:string|null};
type Message={id:string;offerId:string|null;actorId:string;kind:string;body:string|null;createdAt:string;actorName:string|null;attachments:Array<{id:string;mime:string;byteSize:number;url:string}>};
type Conversation={threadId:string;listingId:string;currentOfferId:string;viewerId:string;sellerId:string;buyerId:string;supplierId:string;listingType:string;negotiable?:boolean;listingStatus:string;listingExpiresAt:string|null;rounds:Round[];messages:Message[]};
const money=(amount:number,currency:string,locale:string)=>new Intl.NumberFormat(locale,{style:'currency',currency:currency||'IDR',maximumFractionDigits:0}).format(amount);

export function OfferConversation({offerId,language,open,onOpenChange,onChanged,presentation='dialog'}:{offerId:string;language:Language;open:boolean;onOpenChange:(open:boolean)=>void;onChanged?:()=>void;presentation?:'dialog'|'panel'}){
  const id=language==='ID';const [data,setData]=useState<Conversation|null>(null);const dataRef=useRef<Conversation|null>(null);const pollBusy=useRef(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [body,setBody]=useState('');const [counterItems,setCounterItems]=useState<Array<{printingId:string;quantity:number;unitAmount:number;card?:Round['items'][number]['card']}>>([]);const [countering,setCountering]=useState(false);const [busy,setBusy]=useState(false);const [now,setNow]=useState(0);
  const copy=id?{title:'Percakapan penawaran',desc:'Negosiasikan harga dan detail kartu di sini.',send:'Kirim',write:'Tulis pesan…',photoRequest:'Minta foto kartu',share:'Bagikan foto',shareMore:'Bagikan foto lainnya',photos:'Foto hanya terlihat oleh kedua pihak dalam percakapan ini.',counter:'Ajukan harga baru',accept:'Terima penawaran',decline:'Tolak',respond:'Balas penawaran',amount:'Harga total',sendCounter:'Kirim penawaran balik',sent:'Anda',retry:'Coba lagi',pending:'Menunggu',accepted:'Diterima',declined:'Ditolak',countered:'Dibalas dengan penawaran baru',counterLabel:'Penawaran balik',expired:'Kedaluwarsa',expires:'Berakhir',checkout:'Lanjut ke checkout',photoLabel:'Foto kartu',requestLabel:'Meminta foto kartu',photosRequested:'Permintaan foto terkirim. Penjual dapat membagikan foto di sini.',photosShared:'Foto kartu sudah dibagikan.',load:'Memuat percakapan…',back:'Kembali ke penawaran',counterLimit:'Maksimal tiga penawaran balik per orang.',closed:'Penawaran ini kedaluwarsa atau sudah ditutup. Pesan baru tidak dapat dikirim.'}:{title:'Offer conversation',desc:'Discuss the price and card details here.',send:'Send',write:'Write a message…',photoRequest:'Request card photos',share:'Share photos',shareMore:'Share more photos',photos:'Photos are private to both people in this conversation.',counter:'Make a counteroffer',accept:'Accept offer',decline:'Decline',respond:'Respond to offer',amount:'Total price',sendCounter:'Send counteroffer',sent:'You',retry:'Try again',pending:'Pending',accepted:'Accepted',declined:'Declined',countered:'Counteroffer sent',counterLabel:'Counteroffer',expired:'Expired',expires:'Expires',checkout:'Continue to checkout',photoLabel:'Card photo',requestLabel:'Requested card photos',photosRequested:'Photo request sent. The seller can share photos here.',photosShared:'Card photos have been shared.',load:'Loading conversation…',back:'Back to offers',counterLimit:'Up to three counteroffers per person.',closed:'This offer has expired or closed. New messages are disabled.'};
  const latest=useMemo(()=>data?.rounds.at(-1)??null,[data]);
  const localizeError=(message:string)=>id&&message.toLowerCase().includes('firm price')?'Listing ini menggunakan harga pas dan tidak menerima penawaran balik.':id&&message.includes('three-counteroffer limit')?copy.counterLimit:id&&message.toLowerCase().includes('expired')?copy.closed:id&&message.toLowerCase().includes('listing')&&message.toLowerCase().includes('available')?'Listing ini sudah tidak tersedia.':message;
  const listingAvailable=Boolean(data&&data.listingStatus==='ACTIVE'&&(!data.listingExpiresAt||new Date(`${data.listingExpiresAt.replace(' ','T')}Z`).getTime()>now));
  const canRespond=Boolean(latest&&latest.status==='PENDING'&&latest.actorId!==data?.viewerId&&listingAvailable&&(!latest.expiresAt||new Date(`${latest.expiresAt.replace(' ','T')}Z`).getTime()>now));const canCounter=canRespond&&(data?.listingType!=='WTS'||data.negotiable!==false);
  const offerExpired=Boolean(latest&&(latest.status==='EXPIRED'||(latest.status==='PENDING'&&latest.expiresAt&&new Date(`${latest.expiresAt.replace(' ','T')}Z`).getTime()<=now)));
  const conversationOpen=Boolean(latest?.status==='PENDING'&&!offerExpired&&listingAvailable);
  const conversationClosed=Boolean(data&&!conversationOpen);
  const photoRequested=Boolean(data?.messages.some(message=>message.kind==='PHOTO_REQUEST'&&message.actorId===data.buyerId));
  const photosShared=Boolean(data?.messages.some(message=>message.actorId===data.supplierId&&message.attachments.length>0));
  const canRequestPhotos=Boolean(data&&latest?.status==='PENDING'&&listingAvailable&&data.viewerId===data.buyerId&&!photoRequested&&!photosShared);
  const canSharePhotos=Boolean(data&&latest?.status==='PENDING'&&listingAvailable&&data.viewerId===data.supplierId&&photoRequested);
  const counterTotal=counterItems.reduce((total,item)=>total+item.quantity*item.unitAmount,0);
  const refresh=useCallback(async(silent=false)=>{if(pollBusy.current)return;pollBusy.current=true;if(!silent&&!dataRef.current)setLoading(true);if(!silent)setError('');try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/conversation`,{cache:'no-store'});const result=await response.json() as Conversation&{error?:string};if(!response.ok)throw new Error(result.error||'Conversation could not be loaded.');const previous=dataRef.current;if(previous){const oldMessages=new Set(previous.messages.map(message=>message.id));const incoming=result.messages.filter(message=>!oldMessages.has(message.id)&&message.actorId!==result.viewerId);for(const message of incoming){const label=message.attachments.length?(id?'Foto kartu baru dibagikan':'New card photos shared'):message.kind==='PHOTO_REQUEST'?(id?'Foto kartu diminta':'Card photos requested'):message.kind.startsWith('OFFER_')?(id?'Penawaran diperbarui':'Offer updated'):(id?'Pesan baru':'New message');toast.info(label)}const oldRound=previous.rounds.at(-1);const newRound=result.rounds.at(-1);if(newRound&&newRound.actorId!==result.viewerId&&newRound.id!==oldRound?.id&&!incoming.some(message=>message.offerId===newRound.id))toast.info(id?'Penawaran balik baru':'New counteroffer');}dataRef.current=result;setData(result);setNow(Date.now());}catch(reason){if(!silent||!dataRef.current)setError(reason instanceof Error?reason.message:'Conversation could not be loaded.');}finally{pollBusy.current=false;setLoading(false)}},[id,offerId]);
  // Fetching remote conversation state is the effect's external synchronization work.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(!open)return;void refresh();const timer=window.setInterval(()=>void refresh(true),4_000);return()=>window.clearInterval(timer)},[open,refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),60_000);return()=>window.clearInterval(timer)},[]);
  const post=async(kind:'MESSAGE'|'PHOTO_REQUEST'='MESSAGE')=>{const text=body.trim();if(kind==='MESSAGE'&&!text)return;setBusy(true);try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,body:text})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Message could not be sent.');setBody('');await refresh();}catch(reason){toast.error(localizeError(reason instanceof Error?reason.message:'Message could not be sent.'))}finally{setBusy(false)}};
  const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]);event.target.value='';if(!files.length)return;const form=new FormData();files.slice(0,4).forEach(file=>form.append('photos',file));if(files.length>4){toast.error(id?'Pilih maksimal empat foto.':'Choose up to four photos.');return}setBusy(true);try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/messages`,{method:'POST',body:form});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Photos could not be shared.');await refresh();}catch(reason){toast.error(localizeError(reason instanceof Error?reason.message:'Photos could not be shared.'))}finally{setBusy(false)}};
  const respond=async(action:'accept'|'decline'|'counter')=>{if(action==='counter'&&(!counterItems.length||counterItems.some(item=>!Number.isSafeInteger(item.unitAmount)||item.unitAmount<1)||counterTotal<1)){toast.error(id?'Masukkan harga per kartu yang valid.':'Enter a valid unit price for each card.');return}setBusy(true);try{const payload=action==='counter'?{action,amount:counterTotal,items:counterItems.map(({printingId,quantity,unitAmount})=>({printingId,quantity,unitAmount}))}:{action};const response=await fetch(`/api/listings/offers/${encodeURIComponent(data?.currentOfferId||offerId)}/respond`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {error?:string;status?:string};if(!response.ok)throw new Error(result.error||'Offer could not be updated.');setCountering(false);toast.success(action==='accept'?(id?'Penawaran diterima':'Offer accepted'):action==='decline'?(id?'Penawaran ditolak':'Offer declined'):(id?'Penawaran balik dikirim':'Counteroffer sent'));await refresh();onChanged?.();}catch(reason){toast.error(localizeError(reason instanceof Error?reason.message:'Offer could not be updated.'))}finally{setBusy(false)}};
  const conversationBody=<>
    {data&&<PushNotificationPrompt language={language} message="activity"/>}
    {loading&&!data?<div className="market-offer-conversation-state">{copy.load}</div>:error&&!data?<div className="market-offer-conversation-state" role="alert"><span>{error}</span><button type="button" onClick={()=>void refresh()}>{copy.retry}</button></div>:data&&<>
      <div className="market-offer-rounds" aria-label={id?'Riwayat penawaran':'Offer history'}>{data.rounds.map(round=><article className={`market-offer-round ${round.actorId===data.viewerId?'is-mine':''}`} key={round.id}><div><b>{round.actorId===data.viewerId?copy.sent:round.actorName|| (id?'Kolektor':'Collector')}</b><span>{round.status==='PENDING'?copy.pending:round.status==='ACCEPTED'?copy.accepted:round.status==='DECLINED'?copy.declined:round.status==='EXPIRED'?copy.expired:round.parentOfferId?copy.counterLabel:copy.countered}</span>{round.status==='PENDING'&&round.expiresAt&&<small>{copy.expires} {new Date(`${round.expiresAt.replace(' ','T')}Z`).toLocaleString(id?'id-ID':'en-US')}</small>}</div><strong>{money(round.amount,round.currency,id?'id-ID':'en-US')}</strong></article>)}</div>
      {offerExpired&&<p className="market-offer-private-note" role="status">{id?'Penawaran ini kedaluwarsa setelah 24 jam atau saat listing berakhir.':'This offer expired after 24 hours or when the listing ended.'}</p>}
      {conversationClosed&&!offerExpired&&<p className="market-offer-private-note" role="status">{copy.closed}</p>}
      {latest?.status==='ACCEPTED'&&data.viewerId===data.buyerId&&data.listingType==='WTS'&&<Link className="market-activity-primary" href={`/checkout/market?${new URLSearchParams({listing:data.listingId,items:JSON.stringify(latest.items),offer:latest.id}).toString()}`}>{copy.checkout}</Link>}
      {canRespond&&<div className="market-offer-response"><p>{copy.respond}</p>{countering?<div className="market-offer-counter-form"><div className="market-counter-lines">{(latest?.items??[]).map((item,index)=>{const line=counterItems[index];return <label className="market-counter-line" key={`${item.printingId}-${index}`}><span className="market-counter-card">{item.card?.imageUrl?<img src={item.card.imageUrl} alt=""/>:<span aria-hidden="true"/>}<span><b>{item.card?.name??item.card?.code??item.printingId}</b><small>{item.quantity} {id?'kartu':'cards'} · {item.card?.code??item.printingId}</small></span></span><span className="market-counter-price"><small>{id?`Harga per kartu (${latest?.currency??'IDR'})`:`Unit price (${latest?.currency??'IDR'})`}</small><input type="number" min="1" step="1" inputMode="numeric" value={line?.unitAmount??''} onChange={event=>setCounterItems(current=>current.map((entry,entryIndex)=>entryIndex===index?{...entry,unitAmount:event.target.value===''?0:Number(event.target.value)}:entry))}/></span></label>})}</div><div className="market-counter-total"><span>{id?'Total penawaran':'Counteroffer total'}</span><strong>{money(counterTotal,latest?.currency??'IDR',id?'id-ID':'en-US')}</strong></div><button type="button" disabled={busy||!counterItems.length||counterItems.some(item=>!Number.isSafeInteger(item.unitAmount)||item.unitAmount<1)} onClick={()=>void respond('counter')}>{copy.sendCounter}</button><button type="button" className="is-quiet" disabled={busy} onClick={()=>setCountering(false)} aria-label={id?'Batal':'Cancel'}><XCircle size={17}/></button></div>:<div className="market-offer-response-actions"><button type="button" className="is-accept" disabled={busy} onClick={()=>void respond('accept')}><CheckCircle size={17}/>{copy.accept}</button>{canCounter&&<button type="button" onClick={()=>{setCounterItems((latest?.items??[]).map(item=>({...item,unitAmount:item.unitAmount??Math.max(1,Math.floor((latest?.amount??0)/Math.max(1,(latest?.items??[]).reduce((sum,line)=>sum+line.quantity,0))))})));setCountering(true)}}><ArrowBendUpLeft size={17}/>{copy.counter}</button>}<button type="button" className="is-decline" disabled={busy} onClick={()=>void respond('decline')}><XCircle size={17}/>{copy.decline}</button></div>}</div>}
      <div className="market-offer-messages" aria-live="polite">{data.messages.map(message=><article className={`market-offer-message ${message.actorId===data.viewerId?'is-mine':''}`} key={message.id}><small>{message.actorId===data.viewerId?copy.sent:message.actorName|| (id?'Kolektor':'Collector')} · {new Date(`${message.createdAt.replace(' ','T')}Z`).toLocaleString(id?'id-ID':'en-US')}</small>{message.kind==='PHOTO_REQUEST'?<p>{copy.requestLabel}</p>:message.kind.startsWith('OFFER_')?<p>{message.kind==='OFFER_COUNTERED'?copy.countered:message.kind==='OFFER_ACCEPTED'?copy.accepted:copy.declined}</p>:message.body&&<p>{message.body}</p>}{message.attachments.map(file=><a key={file.id} href={file.url} target="_blank" rel="noreferrer"><img src={file.url} alt={copy.photoLabel}/></a>)}</article>)}</div>
      <p className="market-offer-private-note">{copy.photos}</p>
      {(canRequestPhotos||canSharePhotos||photoRequested||photosShared)&&<div className="market-offer-photo-actions">
        {canRequestPhotos&&<button type="button" disabled={busy} onClick={()=>void post('PHOTO_REQUEST')}><Camera size={17}/>{copy.photoRequest}</button>}
        {canSharePhotos&&<label className="market-offer-upload"><UploadSimple size={17}/>{photosShared?copy.shareMore:copy.share}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={event=>void upload(event)}/></label>}
        {photoRequested&&!photosShared&&data.viewerId===data.buyerId&&<small>{copy.photosRequested}</small>}
        {photosShared&&<small>{id?'Foto sudah dibagikan. Penjual dapat membagikan foto tambahan.':'Photos are shared. The seller can add more photos anytime.'}</small>}
      </div>}
      {conversationOpen&&<form className="market-offer-compose" onSubmit={event=>{event.preventDefault();void post()}}><textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000} placeholder={copy.write} aria-label={copy.write}/><div className="market-offer-compose-actions"><button type="submit" className="is-send" disabled={busy||!body.trim()}><PaperPlaneRight size={17}/>{copy.send}</button></div></form>}
    </>}
  </>;
  if(presentation==='panel')return <section className="market-offer-conversation market-offer-conversation-panel">
    <header className="market-offer-conversation-panel-heading"><button type="button" onClick={()=>onOpenChange(false)}><ArrowLeft size={16}/>{copy.back}</button><div><h2>{copy.title}</h2><p>{copy.desc}</p></div></header>
    {conversationBody}
  </section>;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="market-offer-conversation"><DialogHeader><DialogTitle>{copy.title}</DialogTitle><DialogDescription>{copy.desc}</DialogDescription></DialogHeader>{conversationBody}</DialogContent></Dialog>;
}
