'use client';

import {useCallback,useEffect,useMemo,useState} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {ArrowBendUpLeft,ArrowLeft,CheckCircle,PaperPlaneRight,Camera,UploadSimple,XCircle} from '@phosphor-icons/react';
import {toast} from 'sonner';

type Language='EN'|'ID';
type Round={id:string;parentOfferId:string|null;actorId:string;type:string;items:unknown[];amount:number;currency:string;status:string;createdAt:string;actorName:string|null};
type Message={id:string;offerId:string|null;actorId:string;kind:string;body:string|null;createdAt:string;actorName:string|null;attachments:Array<{id:string;mime:string;byteSize:number;url:string}>};
type Conversation={threadId:string;listingId:string;currentOfferId:string;viewerId:string;sellerId:string;buyerId:string;supplierId:string;listingType:string;listingStatus:string;listingExpiresAt:string|null;rounds:Round[];messages:Message[]};
const money=(amount:number,currency:string,locale:string)=>new Intl.NumberFormat(locale,{style:'currency',currency:currency||'IDR',maximumFractionDigits:0}).format(amount);

export function OfferConversation({offerId,language,open,onOpenChange,onChanged,presentation='dialog'}:{offerId:string;language:Language;open:boolean;onOpenChange:(open:boolean)=>void;onChanged?:()=>void;presentation?:'dialog'|'panel'}){
  const id=language==='ID';const [data,setData]=useState<Conversation|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [body,setBody]=useState('');const [amount,setAmount]=useState('');const [countering,setCountering]=useState(false);const [busy,setBusy]=useState(false);
  const copy=id?{title:'Percakapan penawaran',desc:'Negosiasikan harga dan detail kartu di sini.',send:'Kirim',write:'Tulis pesan…',photoRequest:'Minta foto kartu',share:'Bagikan foto',photos:'Foto hanya terlihat oleh kedua pihak dalam percakapan ini.',counter:'Ajukan harga baru',accept:'Terima penawaran',decline:'Tolak',respond:'Balas penawaran',amount:'Harga total',sendCounter:'Kirim penawaran balik',sent:'Anda',retry:'Coba lagi',pending:'Menunggu balasan',accepted:'Disepakati',declined:'Ditolak',countered:'Dibalas dengan penawaran baru',counterLabel:'Penawaran balik',photoLabel:'Foto kartu',requestLabel:'Meminta foto kartu',photosRequested:'Permintaan foto terkirim. Penjual dapat membagikan foto di sini.',photosShared:'Foto kartu sudah dibagikan.',load:'Memuat percakapan…',back:'Kembali ke penawaran'}:{title:'Offer conversation',desc:'Discuss the price and card details here.',send:'Send',write:'Write a message…',photoRequest:'Request card photos',share:'Share photos',photos:'Photos are private to both people in this conversation.',counter:'Make a counteroffer',accept:'Accept offer',decline:'Decline',respond:'Respond to offer',amount:'Total price',sendCounter:'Send counteroffer',sent:'You',retry:'Try again',pending:'Waiting for a response',accepted:'Agreed',declined:'Declined',countered:'Counteroffer sent',counterLabel:'Counteroffer',photoLabel:'Card photo',requestLabel:'Requested card photos',photosRequested:'Photo request sent. The seller can share photos here.',photosShared:'Card photos have been shared.',load:'Loading conversation…',back:'Back to offers'};
  const latest=useMemo(()=>data?.rounds.at(-1)??null,[data]);
  const listingAvailable=Boolean(data&&data.listingStatus==='ACTIVE'&&(!data.listingExpiresAt||new Date(`${data.listingExpiresAt.replace(' ','T')}Z`).getTime()>Date.now()));
  const canRespond=Boolean(latest&&latest.status==='PENDING'&&latest.actorId!==data?.viewerId&&listingAvailable);
  const photoRequested=Boolean(data?.messages.some(message=>message.kind==='PHOTO_REQUEST'&&message.actorId===data.buyerId));
  const photosShared=Boolean(data?.messages.some(message=>message.actorId===data.supplierId&&message.attachments.length>0));
  const canRequestPhotos=Boolean(data&&latest?.status==='PENDING'&&listingAvailable&&data.viewerId===data.buyerId&&!photoRequested&&!photosShared);
  const canSharePhotos=Boolean(data&&latest?.status==='PENDING'&&listingAvailable&&data.viewerId===data.supplierId&&photoRequested&&!photosShared);
  const refresh=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/conversation`,{cache:'no-store'});const result=await response.json() as Conversation&{error?:string};if(!response.ok)throw new Error(result.error||'Conversation could not be loaded.');setData(result);setAmount(String(result.rounds.at(-1)?.amount??''));}catch(reason){setError(reason instanceof Error?reason.message:'Conversation could not be loaded.');}finally{setLoading(false)}},[offerId]);
  useEffect(()=>{if(open)void refresh()},[open,refresh]);
  const post=async(kind:'MESSAGE'|'PHOTO_REQUEST'='MESSAGE')=>{const text=body.trim();if(kind==='MESSAGE'&&!text)return;setBusy(true);try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,body:text})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Message could not be sent.');setBody('');await refresh();}catch(reason){toast.error(reason instanceof Error?reason.message:'Message could not be sent.')}finally{setBusy(false)}};
  const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]);event.target.value='';if(!files.length)return;const form=new FormData();files.slice(0,4).forEach(file=>form.append('photos',file));if(files.length>4){toast.error(id?'Pilih maksimal empat foto.':'Choose up to four photos.');return}setBusy(true);try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(offerId)}/messages`,{method:'POST',body:form});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Photos could not be shared.');await refresh();}catch(reason){toast.error(reason instanceof Error?reason.message:'Photos could not be shared.')}finally{setBusy(false)}};
  const respond=async(action:'accept'|'decline'|'counter')=>{if(action==='counter'&&(!Number.isFinite(Number(amount))||Number(amount)<=0)){toast.error(id?'Masukkan harga yang valid.':'Enter a valid price.');return}setBusy(true);try{const response=await fetch(`/api/listings/offers/${encodeURIComponent(data?.currentOfferId||offerId)}/respond`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(action==='counter'?{action,amount:Math.round(Number(amount))}:{action})});const result=await response.json() as {error?:string;status?:string};if(!response.ok)throw new Error(result.error||'Offer could not be updated.');setCountering(false);toast.success(action==='accept'?(id?'Penawaran disepakati':'Offer accepted'):action==='decline'?(id?'Penawaran ditolak':'Offer declined'):(id?'Penawaran balik dikirim':'Counteroffer sent'));await refresh();onChanged?.();}catch(reason){toast.error(reason instanceof Error?reason.message:'Offer could not be updated.')}finally{setBusy(false)}};
  const conversationBody=<>
    {loading&&!data?<div className="market-offer-conversation-state">{copy.load}</div>:error&&!data?<div className="market-offer-conversation-state" role="alert"><span>{error}</span><button type="button" onClick={()=>void refresh()}>{copy.retry}</button></div>:data&&<>
      <div className="market-offer-rounds" aria-label={id?'Riwayat penawaran':'Offer history'}>{data.rounds.map(round=><article className={`market-offer-round ${round.actorId===data.viewerId?'is-mine':''}`} key={round.id}><div><b>{round.actorId===data.viewerId?copy.sent:round.actorName|| (id?'Kolektor':'Collector')}</b><span>{round.parentOfferId?copy.counterLabel:round.status==='PENDING'?copy.pending:round.status==='ACCEPTED'?copy.accepted:round.status==='DECLINED'?copy.declined:copy.countered}</span></div><strong>{money(round.amount,round.currency,id?'id-ID':'en-US')}</strong></article>)}</div>
      {canRespond&&<div className="market-offer-response"><p>{copy.respond}</p>{countering?<div className="market-offer-counter-form"><label>{copy.amount}<input type="number" min="1" step="1" value={amount} onChange={event=>setAmount(event.target.value)}/></label><button type="button" disabled={busy} onClick={()=>void respond('counter')}>{copy.sendCounter}</button><button type="button" className="is-quiet" disabled={busy} onClick={()=>setCountering(false)}><XCircle size={17}/></button></div>:<div className="market-offer-response-actions"><button type="button" className="is-accept" disabled={busy} onClick={()=>void respond('accept')}><CheckCircle size={17}/>{copy.accept}</button><button type="button" onClick={()=>setCountering(true)}><ArrowBendUpLeft size={17}/>{copy.counter}</button><button type="button" className="is-decline" disabled={busy} onClick={()=>void respond('decline')}><XCircle size={17}/>{copy.decline}</button></div>}</div>}
      <div className="market-offer-messages" aria-live="polite">{data.messages.map(message=><article className={`market-offer-message ${message.actorId===data.viewerId?'is-mine':''}`} key={message.id}><small>{message.actorId===data.viewerId?copy.sent:message.actorName|| (id?'Kolektor':'Collector')} · {new Date(`${message.createdAt.replace(' ','T')}Z`).toLocaleString(id?'id-ID':'en-US')}</small>{message.kind==='PHOTO_REQUEST'?<p>{copy.requestLabel}</p>:message.kind.startsWith('OFFER_')?<p>{message.kind==='OFFER_COUNTERED'?copy.countered:message.kind==='OFFER_ACCEPTED'?copy.accepted:copy.declined}</p>:message.body&&<p>{message.body}</p>}{message.attachments.map(file=><a key={file.id} href={file.url} target="_blank" rel="noreferrer"><img src={file.url} alt={copy.photoLabel}/></a>)}</article>)}</div>
      <p className="market-offer-private-note">{copy.photos}</p>
      {(canRequestPhotos||canSharePhotos||photoRequested||photosShared)&&<div className="market-offer-photo-actions">
        {canRequestPhotos&&<button type="button" disabled={busy} onClick={()=>void post('PHOTO_REQUEST')}><Camera size={17}/>{copy.photoRequest}</button>}
        {canSharePhotos&&<label className="market-offer-upload"><UploadSimple size={17}/>{copy.share}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={event=>void upload(event)}/></label>}
        {photoRequested&&!photosShared&&data.viewerId===data.buyerId&&<small>{copy.photosRequested}</small>}
        {photosShared&&<small>{copy.photosShared}</small>}
      </div>}
      <form className="market-offer-compose" onSubmit={event=>{event.preventDefault();void post()}}><textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000} placeholder={copy.write} aria-label={copy.write}/><div className="market-offer-compose-actions"><button type="submit" className="is-send" disabled={busy||!body.trim()}><PaperPlaneRight size={17}/>{copy.send}</button></div></form>
    </>}
  </>;
  if(presentation==='panel')return <section className="market-offer-conversation market-offer-conversation-panel">
    <header className="market-offer-conversation-panel-heading"><button type="button" onClick={()=>onOpenChange(false)}><ArrowLeft size={16}/>{copy.back}</button><div><h2>{copy.title}</h2><p>{copy.desc}</p></div></header>
    {conversationBody}
  </section>;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="market-offer-conversation"><DialogHeader><DialogTitle>{copy.title}</DialogTitle><DialogDescription>{copy.desc}</DialogDescription></DialogHeader>{conversationBody}</DialogContent></Dialog>;
}
