import {notFound} from 'next/navigation';
import {getCurrentUser} from '@/lib/server/auth';
import {db} from '@/lib/server/store';
import {cards} from '@/packages/card-data/catalog';
import {CardArt} from '@/components/tcg/card-art';
import {ShareButton} from '@/components/tcg/share';
export const dynamic='force-dynamic';
async function read(id:string){const auth=await getCurrentUser();const d=await db().prepare(`SELECT d.id,d.name,d.visibility,p.auth_subject,v.id AS versionId,v.number,v.leader_id AS leaderId FROM decks d JOIN profiles p ON p.id=d.owner_id JOIN deck_versions v ON v.deck_id=d.id WHERE d.id=? AND d.deleted_at IS NULL ORDER BY v.number DESC LIMIT 1`).bind(id).first<{id:string;name:string;visibility:string;auth_subject:string;versionId:string;number:number;leaderId:string}>();if(!d||d.visibility!=='public'&&d.auth_subject!==auth?.id)return null;return d;}
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const d=await read(id);return {title:d?`${d.name} · Deck`:'Private deck',description:d?`Version ${d.number} deck list.`:undefined,robots:{index:false,follow:false},openGraph:d?.visibility==='public'?{title:d.name,description:`Deck version ${d.number}`}:undefined};}
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;const d=await read(id);if(!d)notFound();const entries=(await db().prepare('SELECT card_id AS cardId,quantity FROM deck_entries WHERE version_id=?').bind(d.versionId).all<{cardId:string;quantity:number}>()).results;return <main className="page"><div className="page-heading"><div><p className="eyebrow">DECK VERSION {d.number} · {d.visibility}</p><h1>{d.name}</h1><p>{entries.reduce((n,e)=>n+e.quantity,0)} / 50 cards</p></div><ShareButton title={d.name} path={`/decks/${d.id}`} privateEntity={d.visibility!=='public'}/></div><div className="card-grid">{[...([{cardId:d.leaderId,quantity:1}]),...entries].map(e=>{const c=cards.find(c=>c.id===e.cardId)!;return <div key={c.id}><CardArt card={c}/><h3 className="mt-3">{e.quantity} × {c.name}</h3></div>})}</div></main>}
