import type {Metadata} from 'next';
import type {ReactNode} from 'react';
import Link from 'next/link';
import {isIndonesianRequest} from '@/lib/locale';

type FaqItem={question:string;answer:ReactNode;plainAnswer:string};
type FaqGroup={title:string;items:FaqItem[]};

export async function generateMetadata():Promise<Metadata>{
  const id=await isIndonesianRequest();
  const title=id?'Tanya jawab':'FAQ';
  const description=id?'Jawaban tentang akun, koleksi, biaya Market, dan pesanan.':'Answers about accounts, your collection, Market fees, and orders.';
  return {title,description,alternates:{canonical:id?'/id/faq':'/faq',languages:{'en-US':'/faq','id-ID':'/id/faq'}},openGraph:{type:'article',title,description,url:id?'/id/faq':'/faq'}};
}

export default async function FaqPage(){
  const id=await isIndonesianRequest();
  const groups:FaqGroup[]=id?[
    {title:'Akun dan koleksi',items:[
      {question:'Apakah VivrePlay berafiliasi dengan Bandai?',answer:'Tidak. VivrePlay adalah proyek komunitas independen dan tidak berafiliasi dengan atau didukung oleh Bandai.',plainAnswer:'Tidak. VivrePlay adalah proyek komunitas independen dan tidak berafiliasi dengan atau didukung oleh Bandai.'},
      {question:'Fitur apa yang bisa digunakan tanpa akun?',answer:'Katalog kartu dan halaman publik dapat dibuka tanpa akun. Masuk untuk menyinkronkan koleksi dan daftar keinginan atau menggunakan fitur akun lainnya.',plainAnswer:'Katalog kartu dan halaman publik dapat dibuka tanpa akun. Masuk untuk menyinkronkan koleksi dan daftar keinginan atau menggunakan fitur akun lainnya.'},
      {question:'Bagaimana cara melaporkan data kartu yang keliru?',answer:'Gunakan Masukan & laporan di halaman kartu. Sertakan kode kartu, bahasa, set, dan cetakannya agar kami dapat memeriksanya.',plainAnswer:'Gunakan Masukan & laporan di halaman kartu. Sertakan kode kartu, bahasa, set, dan cetakannya agar kami dapat memeriksanya.'},
    ]},
    {title:'Market dan pesanan',items:[
      {question:'Berapa biaya transaksi Market?',answer:'Pembeli akun Free dikenai biaya layanan 0,75% dari subtotal kartu; anggota Market Pro dikenai 0,5%. Biaya penjual adalah 1,5% untuk Free dan 0,75% untuk Pro. Ongkir dan biaya yang berlaku ditampilkan sebelum pembayaran.',plainAnswer:'Pembeli akun Free dikenai biaya layanan 0,75% dari subtotal kartu; anggota Market Pro dikenai 0,5%. Biaya penjual adalah 1,5% untuk Free dan 0,75% untuk Pro. Ongkir dan biaya yang berlaku ditampilkan sebelum pembayaran.'},
      {question:'Apa yang termasuk dalam Market Pro?',answer:'Satu langganan Market Pro berlaku untuk aktivitas membeli dan menjual pada akun yang sama. Harga dan masa aktif ditampilkan saat checkout. Manfaat saat ini mencakup biaya layanan yang lebih rendah, batas listing lebih tinggi, masa listing lebih panjang, dan dua voucher ongkir bulanan. Setiap voucher menanggung 50% ongkir reguler, maksimal Rp5.000, untuk pesanan dengan subtotal kartu minimal Rp200.000. Voucher yang tidak dipakai tidak dibawa ke bulan berikutnya.',plainAnswer:'Satu langganan Market Pro berlaku untuk aktivitas membeli dan menjual pada akun yang sama. Harga dan masa aktif ditampilkan saat checkout. Manfaat saat ini mencakup biaya layanan yang lebih rendah, batas listing lebih tinggi, masa listing lebih panjang, dan dua voucher ongkir bulanan. Setiap voucher menanggung 50% ongkir reguler, maksimal Rp5.000, untuk pesanan dengan subtotal kartu minimal Rp200.000. Voucher yang tidak dipakai tidak dibawa ke bulan berikutnya.'},
      {question:'Kapan pesanan muncul untuk penjual?',answer:'Penjual melihat pesanan setelah pembayaran pembeli dikonfirmasi. Pesanan yang belum dibayar tetap terlihat oleh pembeli selama masa pembayaran, dan kartu terkait tidak tersedia untuk dibeli orang lain.',plainAnswer:'Penjual melihat pesanan setelah pembayaran pembeli dikonfirmasi. Pesanan yang belum dibayar tetap terlihat oleh pembeli selama masa pembayaran, dan kartu terkait tidak tersedia untuk dibeli orang lain.'},
      {question:'Berapa lama pembeli punya waktu untuk membayar?',answer:'Batas pembayaran ditampilkan di halaman pesanan. Checkout yang belum dibayar ditutup setelah 24 jam; kartu yang dipesan akan tersedia kembali. Jika pembayaran sudah dimulai, ikuti batas waktu yang ditampilkan pada transaksi.',plainAnswer:'Batas pembayaran ditampilkan di halaman pesanan. Checkout yang belum dibayar ditutup setelah 24 jam; kartu yang dipesan akan tersedia kembali. Jika pembayaran sudah dimulai, ikuti batas waktu yang ditampilkan pada transaksi.'},
      {question:'Bagaimana mengajukan laporan pesanan?',answer:<>Setelah kurir menandai pesanan terkirim, laporkan masalah dalam 48 jam dari detail pesanan. Sertakan video unboxing dan foto yang relevan. Penjual dapat menanggapi; tim VivrePlay mengambil keputusan akhir. <Link href="/legal/refund">Baca Kebijakan Pengembalian Dana</Link>.</>,plainAnswer:'Setelah kurir menandai pesanan terkirim, laporkan masalah dalam 48 jam dari detail pesanan. Sertakan video unboxing dan foto yang relevan. Penjual dapat menanggapi; tim VivrePlay mengambil keputusan akhir. Baca Kebijakan Pengembalian Dana.'},
      {question:'Apa yang harus dilakukan jika pesanan bermasalah?',answer:<>Buka detail pesanan untuk menghubungi pihak terkait atau melaporkan masalah. Hubungi kami di <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> atau WhatsApp <a href="https://wa.me/6287892660993">+62 878-9266-0993</a>. Sertakan nomor pesanan. <Link href="/legal/refund">Baca Kebijakan Pengembalian Dana</Link>.</>,plainAnswer:'Buka detail pesanan untuk menghubungi pihak terkait atau melaporkan masalah. Hubungi support@vivreplay.com atau WhatsApp +62 878-9266-0993. Sertakan nomor pesanan. Baca Kebijakan Pengembalian Dana.'},
      {question:'Kapan kartu masuk ke Koleksi saya?',answer:'Setelah penjual mengirim kartu dan Anda mengonfirmasi penerimaan di detail pesanan, kartu akan dipindahkan ke Koleksi Anda.',plainAnswer:'Setelah penjual mengirim kartu dan Anda mengonfirmasi penerimaan di detail pesanan, kartu akan dipindahkan ke Koleksi Anda.'},
    ]},
  ]:[
    {title:'Account and collection',items:[
      {question:'Is VivrePlay affiliated with Bandai?',answer:'No. VivrePlay is an independent community project and is not affiliated with or endorsed by Bandai.',plainAnswer:'No. VivrePlay is an independent community project and is not affiliated with or endorsed by Bandai.'},
      {question:'What can I use without an account?',answer:'You can browse the card catalog and public pages without an account. Sign in to sync your collection and wishlist or use other account features.',plainAnswer:'You can browse the card catalog and public pages without an account. Sign in to sync your collection and wishlist or use other account features.'},
      {question:'How do I report incorrect card data?',answer:'Use Feedback & reports on the card page. Include the card code, language, set, and printing so we can check it.',plainAnswer:'Use Feedback & reports on the card page. Include the card code, language, set, and printing so we can check it.'},
    ]},
    {title:'Market and orders',items:[
      {question:'What are the Market transaction fees?',answer:'Free buyers pay 1.5% on the card subtotal, up to Rp100,000 per order. Pro buyers pay 0.75%, up to Rp100,000. Seller fees are 0.75% for Free and 0.5% for Pro. Delivery is separate; checkout shows the total before payment.',plainAnswer:'Free buyers pay 1.5% on the card subtotal, up to Rp100,000 per order. Pro buyers pay 0.75%, up to Rp100,000. Seller fees are 0.75% for Free and 0.5% for Pro. Delivery is separate; checkout shows the total before payment.'},
      {question:'What does Market Pro include?',answer:'One Market Pro membership covers buying and selling on the same account. The price and term appear at checkout. Current benefits include lower service fees, higher listing limits, longer listing periods, and two monthly shipping vouchers. Each voucher covers 50% of regular delivery, up to Rp5,000, on orders with a card subtotal of at least Rp200,000. Unused vouchers do not roll over.',plainAnswer:'One Market Pro membership covers buying and selling on the same account. The price and term appear at checkout. Current benefits include lower service fees, higher listing limits, longer listing periods, and two monthly shipping vouchers. Each voucher covers 50% of regular delivery, up to Rp5,000, on orders with a card subtotal of at least Rp200,000. Unused vouchers do not roll over.'},
      {question:'When does an order appear for the seller?',answer:'Sellers see an order after the buyer’s payment is confirmed. Unpaid checkouts remain visible to the buyer during the payment window, and the reserved cards cannot be bought by someone else.',plainAnswer:'Sellers see an order after the buyer’s payment is confirmed. Unpaid checkouts remain visible to the buyer during the payment window, and the reserved cards cannot be bought by someone else.'},
      {question:'How long does the buyer have to pay?',answer:'The payment deadline appears on the order page. Unpaid checkouts close after 24 hours, and the reserved cards become available again. If payment has already started, use the deadline shown for that transaction.',plainAnswer:'The payment deadline appears on the order page. Unpaid checkouts close after 24 hours, and the reserved cards become available again. If payment has already started, use the deadline shown for that transaction.'},
      {question:'How do I report an order problem?',answer:<>After the courier marks the order delivered, report a problem from the order details within 48 hours. Include an unboxing video and relevant photos. The seller can respond; VivrePlay staff make the final decision. <Link href="/legal/refund">Read the Refund Policy</Link>.</>,plainAnswer:'After the courier marks the order delivered, report a problem from the order details within 48 hours. Include an unboxing video and relevant photos. The seller can respond; VivrePlay staff make the final decision. Read the Refund Policy.'},
      {question:'What should I do if there is a problem with an order?',answer:<>Open the order details to contact the other party or report a problem. Contact us at <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> or WhatsApp <a href="https://wa.me/6287892660993">+62 878-9266-0993</a>. Include your order number. <Link href="/legal/refund">Read the Refund Policy</Link>.</>,plainAnswer:'Open the order details to contact the other party or report a problem. Contact support@vivreplay.com or WhatsApp +62 878-9266-0993. Include your order number. Read the Refund Policy.'},
      {question:'When will the cards move to my Vault?',answer:'After the seller ships the cards and you confirm delivery in the order details, the cards move to your Vault.',plainAnswer:'After the seller ships the cards and you confirm delivery in the order details, the cards move to your Vault.'},
    ]},
  ];
  const structuredData={'@context':'https://schema.org','@type':'FAQPage',mainEntity:groups.flatMap(group=>group.items).map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.plainAnswer}}))};
  return <main className="page faq-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/>
    <header className="faq-heading"><h1>{id?'Tanya jawab':'FAQ'}</h1><p>{id?'Jawaban tentang akun, koleksi, biaya Market, dan pesanan.':'Answers about accounts, your collection, Market fees, and orders.'}</p></header>
    <nav className="faq-jump-links" aria-label={id?'Topik FAQ':'FAQ topics'}>{groups.map((group,index)=><a key={group.title} href={`#faq-group-${index}`}>{group.title}</a>)}</nav>
    {groups.map((group,index)=><section className="faq-group" id={`faq-group-${index}`} key={group.title} aria-labelledby={`faq-group-heading-${index}`}>
      <h2 id={`faq-group-heading-${index}`}>{group.title}</h2>
      <div className="faq-accordion">{group.items.map(item=><details className="faq-item" key={item.question}>
        <summary>{item.question}<span aria-hidden="true" className="faq-chevron"/></summary><div className="faq-answer"><p>{item.answer}</p></div>
      </details>)}</div>
    </section>)}
  </main>;
}
