import type {Metadata} from 'next';
import {LegalDocument,LegalSection} from '@/components/tcg/legal-document';
import {isIndonesianRequest} from '@/lib/locale';

export async function generateMetadata():Promise<Metadata>{const id=await isIndonesianRequest();const title=id?'Kebijakan Pengembalian Dana':'Refund Policy';const description=id?'Cara meminta bantuan atas pembayaran atau pesanan Market di VivrePlay.':'Refund eligibility and how to request help with a VivrePlay payment or Market order.';return {title,description,alternates:{canonical:id?'/id/legal/refund':'/legal/refund',languages:{'en-US':'/legal/refund','id-ID':'/id/legal/refund'}},openGraph:{type:'article',title,description,url:id?'/id/legal/refund':'/legal/refund'}}}

export default async function RefundPolicyPage(){
  const id=await isIndonesianRequest();
  const sections:LegalSection[]=id?[
    {title:'Kapan pengembalian dana dapat diajukan',body:<p>Anda dapat menghubungi kami jika pembayaran terduplikasi, jumlah yang ditagihkan tidak sesuai dengan checkout, pesanan dibatalkan sebelum dikirim, atau ada masalah transaksi lain yang perlu diperiksa. Untuk Market Pro, hubungi kami bila pembayaran berhasil tetapi manfaat paket tidak aktif atau terjadi tagihan ganda.</p>},
    {title:'Pesanan kartu Market',body:<><p>Checkout yang belum dibayar ditutup saat batas waktu yang tertera berakhir (maksimal 24 jam). Jika pembayaran berhasil tetapi pesanan berubah menjadi kedaluwarsa atau dibatalkan, jangan membayar lagi. Kirim nomor pesanan dan bukti pembayaran agar kami dapat memeriksa statusnya.</p><p>Setelah kurir menandai pesanan terkirim, Anda punya 48 jam untuk memeriksa kartu dan melaporkan masalah dari detail pesanan. Sertakan video saat membuka paket, foto yang relevan, serta jumlah kartu yang terdampak. Penjual dapat memberikan tanggapan. Tim VivrePlay meninjau kedua sisi dan mengambil keputusan akhir.</p><p>Jika pengembalian untuk kartu tertentu disetujui, pengembalian mencakup harga kartu yang terdampak. Biaya layanan Market tidak dikembalikan. Ongkir tetap berlaku untuk pengembalian sebagian; pengembalian ongkir dipertimbangkan jika seluruh pesanan gagal karena penjual, misalnya pesanan tidak dikirim. Biaya proses pembayaran yang tidak dapat dikembalikan ditanggung VivrePlay. Refund dikirim manual ke metode pembayaran asal; waktu masuk bergantung pada bank atau dompet digital.</p></>},
    {title:'Kartu sudah dikirim atau diterima',body:<p>Periksa kondisi, jumlah, dan edisi kartu segera setelah paket diterima. Simpan kemasan dan bukti pengiriman. Jangan mengirim barang kembali sebelum metode dan alamat pengembalian disepakati melalui detail pesanan. Pengembalian dana tidak otomatis diberikan hanya karena berubah pikiran setelah penjual mengirim pesanan.</p>},
    {title:'Market Pro dan pembatalan',body:<p>Paket Market Pro memberikan akses selama periode yang ditampilkan saat checkout dan tidak diperpanjang otomatis kecuali dinyatakan secara jelas. Perubahan pikiran atau manfaat yang tidak digunakan tidak otomatis memenuhi syarat pengembalian. Kami akan meninjau tagihan ganda, pembayaran yang berhasil tetapi paket tidak aktif, dan kesalahan jumlah tagihan.</p>},
    {title:'Cara meminta bantuan',body:<p>Hubungi kami di <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> atau WhatsApp <a href="https://wa.me/6287892660993?text=Hi%20VivrePlay%20support%2C%20I%20need%20help%20with%3A%20">+62 878-9266-0993</a>. Sertakan nomor pesanan, tanggal dan jumlah pembayaran, nama pada transaksi, serta bukti pembayaran. Jangan kirim nomor kartu penuh, PIN, kata sandi, atau kode OTP. Kami akan meninjau laporan dan memberi kabar melalui email atau WhatsApp. Pengembalian yang disetujui dikirim ke metode pembayaran asal; waktu masuk bergantung pada bank atau dompet digital.</p>},
  ]:[
    {title:'When you can request a refund',body:<p>Contact us if you were charged more than once, the charged amount differs from checkout, an order is cancelled before shipment, or another transaction issue needs review. For Market Pro, contact us if payment succeeds but the plan does not activate, or if you were charged more than once.</p>},
    {title:'Market card orders',body:<><p>Unpaid checkouts close when the displayed payment deadline passes (up to 24 hours). If payment succeeds but the order changes to expired or cancelled, do not pay again. Send us the order number and payment proof so we can check its status.</p><p>After the courier marks an order delivered, you have 48 hours to check the cards and report a problem from the order details. Include an unboxing video, relevant photos, and the affected card quantities. The seller can respond. VivrePlay staff review both sides and make the final decision.</p><p>If a refund for specific cards is approved, it covers the affected card price. The Market service fee is not refunded. Delivery remains charged for a partial refund; delivery may be refunded when the seller is responsible for the entire failed order, such as an order that was never shipped. VivrePlay absorbs payment processing costs that cannot be recovered. Refunds are sent manually to the original payment method; posting time depends on your bank or e-wallet.</p></>},
    {title:'After shipment or delivery',body:<p>Check card condition, quantity, and printing as soon as the package arrives. Keep the packaging and shipment evidence. Do not return anything until the return method and address are agreed through the order details. A change of mind after shipment does not automatically qualify for a refund.</p>},
    {title:'Market Pro and cancellations',body:<p>Market Pro provides access for the term shown at checkout and does not renew automatically unless clearly stated. A change of mind or unused benefit does not automatically qualify for a refund. We will review duplicate charges, a successful payment that did not activate the plan, and incorrect charge amounts.</p>},
    {title:'How to contact us',body:<p>Contact us at <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> or WhatsApp <a href="https://wa.me/6287892660993?text=Hi%20VivrePlay%20support%2C%20I%20need%20help%20with%3A%20">+62 878-9266-0993</a>. Include your order number, payment date and amount, the name on the transaction, and proof of payment. Never send a full card number, PIN, password, or one-time code. We will review your report and reply by email or WhatsApp. Approved refunds go back to the original payment method; posting time depends on your bank or e-wallet.</p>},
  ];
  return <LegalDocument id={id} title={id?'Kebijakan Pengembalian Dana':'Refund Policy'} description={id?'Informasi pengajuan bantuan dan pengembalian pembayaran VivrePlay.':'How to request help with a VivrePlay payment or Market order.'} lead={id?'Kami meninjau laporan berdasarkan status pembayaran, pesanan, dan bukti yang tersedia.':'We review requests against the payment status, order details, and available evidence.'} sections={sections} updated="8 October 2026"/>;
}
