import type {Metadata} from 'next';
import {LegalDocument,LegalSection} from '@/components/tcg/legal-document';
import {isIndonesianRequest} from '@/lib/locale';

export async function generateMetadata():Promise<Metadata>{const id=await isIndonesianRequest();const title=id?'Kebijakan Pengembalian Dana':'Refund Policy';const description=id?'Cara meminta bantuan atas pembayaran atau pesanan Market di VivrePlay.':'Refund eligibility and how to request help with a VivrePlay payment or Market order.';return {title,description,alternates:{canonical:id?'/id/legal/refund':'/legal/refund',languages:{'en-US':'/legal/refund','id-ID':'/id/legal/refund'}},openGraph:{type:'article',title,description,url:id?'/id/legal/refund':'/legal/refund'}}}

export default async function RefundPolicyPage(){
  const id=await isIndonesianRequest();
  const sections:LegalSection[]=id?[
    {title:'Kapan pengembalian dana dapat diajukan',body:<p>Anda dapat menghubungi kami jika pembayaran terduplikasi, jumlah yang ditagihkan tidak sesuai dengan checkout, pesanan dibatalkan sebelum dikirim, atau ada masalah transaksi lain yang perlu diperiksa. Untuk Market Pro, hubungi kami bila pembayaran berhasil tetapi manfaat paket tidak aktif atau terjadi tagihan ganda.</p>},
    {title:'Pesanan kartu Market',body:<p>Jika penjual tidak dapat mengirimkan pesanan, hubungi penjual melalui informasi pesanan dan laporkan kepada kami dengan nomor pesanan. Kami akan memeriksa status pembayaran dan informasi yang tersedia, lalu menghubungi pihak terkait untuk membantu penyelesaian. Jika pengembalian disetujui, dana dikembalikan melalui proses iPaymu atau metode yang mereka sediakan. Waktu dana masuk bergantung pada iPaymu dan penyedia pembayaran Anda.</p>},
    {title:'Kartu sudah dikirim atau diterima',body:<p>Periksa kondisi, jumlah, dan edisi kartu segera setelah pesanan diterima. Jika barang tidak sesuai atau rusak, simpan kemasan, foto barang, dan bukti pengiriman; lalu hubungi penjual dan support VivrePlay sesegera mungkin. Jangan mengirim barang kembali sebelum cara pengembalian disepakati dengan penjual. Pengembalian dana tidak otomatis diberikan hanya karena berubah pikiran setelah penjual mengirim pesanan.</p>},
    {title:'Market Pro dan pembatalan',body:<p>Paket Market Pro memberikan akses selama periode yang ditampilkan saat checkout. Setelah manfaat paket aktif, perubahan pikiran atau tidak menggunakan manfaat tersebut tidak otomatis memenuhi syarat pengembalian. Kami akan meninjau tagihan ganda, pembayaran gagal yang tetap terdebit, atau manfaat yang tidak aktif. Paket tidak diperpanjang otomatis kecuali checkout secara jelas menyatakan demikian.</p>},
    {title:'Cara meminta bantuan',body:<p>Kirim email ke <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> dari alamat email akun Anda. Sertakan nomor pesanan, tanggal dan jumlah pembayaran, nama pada transaksi, serta bukti pembayaran. Jangan kirim nomor kartu penuh, PIN, kata sandi, atau kode OTP. Kami akan meninjau laporan dan memberi kabar melalui email. Pengembalian yang disetujui diproses kembali melalui iPaymu atau penyedia pembayaran terkait.</p>},
    {title:'Penyedia pembayaran',body:<p>Pembayaran checkout diproses oleh iPaymu. Permintaan pengembalian mungkin memerlukan verifikasi atau proses dari iPaymu maupun bank/dompet digital Anda. Kebijakan ini tidak mengubah hak konsumen yang diberikan oleh hukum yang berlaku.</p>},
  ]:[
    {title:'When you can request a refund',body:<p>Contact us if you were charged more than once, the charged amount differs from checkout, an order is cancelled before shipment, or another transaction issue needs review. For Market Pro, contact us if payment succeeds but the plan does not activate, or if you were charged more than once.</p>},
    {title:'Market card orders',body:<p>If a seller cannot ship an order, contact the seller using the order information and report it to us with your order number. We will review the payment status and available information, then contact the relevant parties to help resolve it. If a refund is approved, it will be returned through iPaymu or a method they provide. Posting time depends on iPaymu and your payment provider.</p>},
    {title:'After shipment or delivery',body:<p>Check card condition, quantity, and printing promptly after delivery. If an item is incorrect or damaged, keep the packaging, take photos of the item, and retain shipment evidence; then contact the seller and VivrePlay support as soon as possible. Do not return an item until the return method is agreed with the seller. A change of mind after shipment does not automatically qualify for a refund.</p>},
    {title:'Market Pro and cancellations',body:<p>Market Pro provides access for the period shown at checkout. Once the plan is active, a change of mind or non-use does not automatically qualify for a refund. We will review duplicate charges, a failed payment that was still debited, or a plan that did not activate. Plans do not renew automatically unless checkout clearly says otherwise.</p>},
    {title:'How to contact us',body:<p>Email <a href="mailto:support@vivreplay.com">support@vivreplay.com</a> from your account email. Include your order number, payment date and amount, the name on the transaction, and proof of payment. Never send a full card number, PIN, password, or one-time code. We will review the report and reply by email. Approved refunds are sent back through iPaymu or the relevant payment provider.</p>},
    {title:'Payment provider',body:<p>Checkout payments are processed by iPaymu. A refund may require verification or processing by iPaymu and your bank or e-wallet provider. This policy does not limit consumer rights provided by applicable law.</p>},
  ];
  return <LegalDocument id={id} title={id?'Kebijakan Pengembalian Dana':'Refund Policy'} description={id?'Informasi pengajuan bantuan dan pengembalian pembayaran VivrePlay.':'How to request help with a VivrePlay payment or Market order.'} lead={id?'Kami meninjau laporan berdasarkan status pembayaran, pesanan, dan bukti yang tersedia.':'We review requests against the payment status, order details, and available evidence.'} sections={sections} updated="2 October 2026"/>;
}
